/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IdentityRouteRouteImport } from './routes/_identity/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IdentityWalletRouteImport } from './routes/_identity/wallet'
import { Route as IdentitySettingsRouteImport } from './routes/_identity/settings'
import { Route as IdentityRegisterRouteImport } from './routes/_identity/register'
import { Route as IdentityRecentProofsRouteImport } from './routes/_identity/recent-proofs'
import { Route as IdentityLoginRouteImport } from './routes/_identity/login'
import { Route as IdentityCallbackRouteImport } from './routes/_identity/callback'
import { Route as IdentityAddProviderRouteImport } from './routes/_identity/add-provider'

const IdentityRouteRoute = IdentityRouteRouteImport.update({
  id: '/_identity',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IdentityWalletRoute = IdentityWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => IdentityRouteRoute,
} as any)
const IdentitySettingsRoute = IdentitySettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => IdentityRouteRoute,
} as any)
const IdentityRegisterRoute = IdentityRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => IdentityRouteRoute,
} as any)
const IdentityRecentProofsRoute = IdentityRecentProofsRouteImport.update({
  id: '/recent-proofs',
  path: '/recent-proofs',
  getParentRoute: () => IdentityRouteRoute,
} as any)
const IdentityLoginRoute = IdentityLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => IdentityRouteRoute,
} as any)
const IdentityCallbackRoute = IdentityCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => IdentityRouteRoute,
} as any)
const IdentityAddProviderRoute = IdentityAddProviderRouteImport.update({
  id: '/add-provider',
  path: '/add-provider',
  getParentRoute: () => IdentityRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add-provider': typeof IdentityAddProviderRoute
  '/callback': typeof IdentityCallbackRoute
  '/login': typeof IdentityLoginRoute
  '/recent-proofs': typeof IdentityRecentProofsRoute
  '/register': typeof IdentityRegisterRoute
  '/settings': typeof IdentitySettingsRoute
  '/wallet': typeof IdentityWalletRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add-provider': typeof IdentityAddProviderRoute
  '/callback': typeof IdentityCallbackRoute
  '/login': typeof IdentityLoginRoute
  '/recent-proofs': typeof IdentityRecentProofsRoute
  '/register': typeof IdentityRegisterRoute
  '/settings': typeof IdentitySettingsRoute
  '/wallet': typeof IdentityWalletRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_identity': typeof IdentityRouteRouteWithChildren
  '/_identity/add-provider': typeof IdentityAddProviderRoute
  '/_identity/callback': typeof IdentityCallbackRoute
  '/_identity/login': typeof IdentityLoginRoute
  '/_identity/recent-proofs': typeof IdentityRecentProofsRoute
  '/_identity/register': typeof IdentityRegisterRoute
  '/_identity/settings': typeof IdentitySettingsRoute
  '/_identity/wallet': typeof IdentityWalletRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add-provider'
    | '/callback'
    | '/login'
    | '/recent-proofs'
    | '/register'
    | '/settings'
    | '/wallet'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add-provider'
    | '/callback'
    | '/login'
    | '/recent-proofs'
    | '/register'
    | '/settings'
    | '/wallet'
  id:
    | '__root__'
    | '/'
    | '/_identity'
    | '/_identity/add-provider'
    | '/_identity/callback'
    | '/_identity/login'
    | '/_identity/recent-proofs'
    | '/_identity/register'
    | '/_identity/settings'
    | '/_identity/wallet'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IdentityRouteRoute: typeof IdentityRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_identity': {
      id: '/_identity'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof IdentityRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_identity/wallet': {
      id: '/_identity/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof IdentityWalletRouteImport
      parentRoute: typeof IdentityRouteRoute
    }
    '/_identity/settings': {
      id: '/_identity/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof IdentitySettingsRouteImport
      parentRoute: typeof IdentityRouteRoute
    }
    '/_identity/register': {
      id: '/_identity/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof IdentityRegisterRouteImport
      parentRoute: typeof IdentityRouteRoute
    }
    '/_identity/recent-proofs': {
      id: '/_identity/recent-proofs'
      path: '/recent-proofs'
      fullPath: '/recent-proofs'
      preLoaderRoute: typeof IdentityRecentProofsRouteImport
      parentRoute: typeof IdentityRouteRoute
    }
    '/_identity/login': {
      id: '/_identity/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof IdentityLoginRouteImport
      parentRoute: typeof IdentityRouteRoute
    }
    '/_identity/callback': {
      id: '/_identity/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof IdentityCallbackRouteImport
      parentRoute: typeof IdentityRouteRoute
    }
    '/_identity/add-provider': {
      id: '/_identity/add-provider'
      path: '/add-provider'
      fullPath: '/add-provider'
      preLoaderRoute: typeof IdentityAddProviderRouteImport
      parentRoute: typeof IdentityRouteRoute
    }
  }
}

interface IdentityRouteRouteChildren {
  IdentityAddProviderRoute: typeof IdentityAddProviderRoute
  IdentityCallbackRoute: typeof IdentityCallbackRoute
  IdentityLoginRoute: typeof IdentityLoginRoute
  IdentityRecentProofsRoute: typeof IdentityRecentProofsRoute
  IdentityRegisterRoute: typeof IdentityRegisterRoute
  IdentitySettingsRoute: typeof IdentitySettingsRoute
  IdentityWalletRoute: typeof IdentityWalletRoute
}

const IdentityRouteRouteChildren: IdentityRouteRouteChildren = {
  IdentityAddProviderRoute: IdentityAddProviderRoute,
  IdentityCallbackRoute: IdentityCallbackRoute,
  IdentityLoginRoute: IdentityLoginRoute,
  IdentityRecentProofsRoute: IdentityRecentProofsRoute,
  IdentityRegisterRoute: IdentityRegisterRoute,
  IdentitySettingsRoute: IdentitySettingsRoute,
  IdentityWalletRoute: IdentityWalletRoute,
}

const IdentityRouteRouteWithChildren = IdentityRouteRoute._addFileChildren(
  IdentityRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IdentityRouteRoute: IdentityRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
