/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IdentityRouteRouteImport } from './routes/_identity/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IdentityRegisterRouteImport } from './routes/_identity/register'
import { Route as IdentityPassportRouteImport } from './routes/_identity/passport'
import { Route as IdentityLoginRouteImport } from './routes/_identity/login'
import { Route as IdentityLockedRouteImport } from './routes/_identity/locked'
import { Route as IdentityCreateIdentityRouteImport } from './routes/_identity/create-identity'
import { Route as IdentityCallbackRouteImport } from './routes/_identity/callback'

const IdentityRouteRoute = IdentityRouteRouteImport.update({
  id: '/_identity',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IdentityRegisterRoute = IdentityRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => IdentityRouteRoute,
} as any)
const IdentityPassportRoute = IdentityPassportRouteImport.update({
  id: '/passport',
  path: '/passport',
  getParentRoute: () => IdentityRouteRoute,
} as any)
const IdentityLoginRoute = IdentityLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => IdentityRouteRoute,
} as any)
const IdentityLockedRoute = IdentityLockedRouteImport.update({
  id: '/locked',
  path: '/locked',
  getParentRoute: () => IdentityRouteRoute,
} as any)
const IdentityCreateIdentityRoute = IdentityCreateIdentityRouteImport.update({
  id: '/create-identity',
  path: '/create-identity',
  getParentRoute: () => IdentityRouteRoute,
} as any)
const IdentityCallbackRoute = IdentityCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => IdentityRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/callback': typeof IdentityCallbackRoute
  '/create-identity': typeof IdentityCreateIdentityRoute
  '/locked': typeof IdentityLockedRoute
  '/login': typeof IdentityLoginRoute
  '/passport': typeof IdentityPassportRoute
  '/register': typeof IdentityRegisterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/callback': typeof IdentityCallbackRoute
  '/create-identity': typeof IdentityCreateIdentityRoute
  '/locked': typeof IdentityLockedRoute
  '/login': typeof IdentityLoginRoute
  '/passport': typeof IdentityPassportRoute
  '/register': typeof IdentityRegisterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_identity': typeof IdentityRouteRouteWithChildren
  '/_identity/callback': typeof IdentityCallbackRoute
  '/_identity/create-identity': typeof IdentityCreateIdentityRoute
  '/_identity/locked': typeof IdentityLockedRoute
  '/_identity/login': typeof IdentityLoginRoute
  '/_identity/passport': typeof IdentityPassportRoute
  '/_identity/register': typeof IdentityRegisterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/callback'
    | '/create-identity'
    | '/locked'
    | '/login'
    | '/passport'
    | '/register'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/callback'
    | '/create-identity'
    | '/locked'
    | '/login'
    | '/passport'
    | '/register'
  id:
    | '__root__'
    | '/'
    | '/_identity'
    | '/_identity/callback'
    | '/_identity/create-identity'
    | '/_identity/locked'
    | '/_identity/login'
    | '/_identity/passport'
    | '/_identity/register'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IdentityRouteRoute: typeof IdentityRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_identity': {
      id: '/_identity'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof IdentityRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_identity/register': {
      id: '/_identity/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof IdentityRegisterRouteImport
      parentRoute: typeof IdentityRouteRoute
    }
    '/_identity/passport': {
      id: '/_identity/passport'
      path: '/passport'
      fullPath: '/passport'
      preLoaderRoute: typeof IdentityPassportRouteImport
      parentRoute: typeof IdentityRouteRoute
    }
    '/_identity/login': {
      id: '/_identity/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof IdentityLoginRouteImport
      parentRoute: typeof IdentityRouteRoute
    }
    '/_identity/locked': {
      id: '/_identity/locked'
      path: '/locked'
      fullPath: '/locked'
      preLoaderRoute: typeof IdentityLockedRouteImport
      parentRoute: typeof IdentityRouteRoute
    }
    '/_identity/create-identity': {
      id: '/_identity/create-identity'
      path: '/create-identity'
      fullPath: '/create-identity'
      preLoaderRoute: typeof IdentityCreateIdentityRouteImport
      parentRoute: typeof IdentityRouteRoute
    }
    '/_identity/callback': {
      id: '/_identity/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof IdentityCallbackRouteImport
      parentRoute: typeof IdentityRouteRoute
    }
  }
}

interface IdentityRouteRouteChildren {
  IdentityCallbackRoute: typeof IdentityCallbackRoute
  IdentityCreateIdentityRoute: typeof IdentityCreateIdentityRoute
  IdentityLockedRoute: typeof IdentityLockedRoute
  IdentityLoginRoute: typeof IdentityLoginRoute
  IdentityPassportRoute: typeof IdentityPassportRoute
  IdentityRegisterRoute: typeof IdentityRegisterRoute
}

const IdentityRouteRouteChildren: IdentityRouteRouteChildren = {
  IdentityCallbackRoute: IdentityCallbackRoute,
  IdentityCreateIdentityRoute: IdentityCreateIdentityRoute,
  IdentityLockedRoute: IdentityLockedRoute,
  IdentityLoginRoute: IdentityLoginRoute,
  IdentityPassportRoute: IdentityPassportRoute,
  IdentityRegisterRoute: IdentityRegisterRoute,
}

const IdentityRouteRouteWithChildren = IdentityRouteRoute._addFileChildren(
  IdentityRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IdentityRouteRoute: IdentityRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
