/* tslint:disable */
/* eslint-disable */
/**
 * OwlID Issuer Service
 * Identity verification and credential issuance
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime.js'
import type { IssueCredentialRequest, IssueCredentialResponse } from '../models/index.js'
import {
  IssueCredentialRequestFromJSON,
  IssueCredentialRequestToJSON,
  IssueCredentialResponseFromJSON,
  IssueCredentialResponseToJSON,
} from '../models/index.js'

export interface IssueCredentialOperationRequest {
  id: string
  issueCredentialRequest: IssueCredentialRequest
}

/**
 * CredentialsApi - interface
 *
 * @export
 * @interface CredentialsApiInterface
 */
export interface CredentialsApiInterface {
  /**
   *
   * @summary Issue a credential from verified claims
   * @param {string} id Session ID
   * @param {IssueCredentialRequest} issueCredentialRequest
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof CredentialsApiInterface
   */
  issueCredentialRaw(
    requestParameters: IssueCredentialOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<IssueCredentialResponse>>

  /**
   * Issue a credential from verified claims
   */
  issueCredential(
    requestParameters: IssueCredentialOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<IssueCredentialResponse>
}

/**
 *
 */
export class CredentialsApi extends runtime.BaseAPI implements CredentialsApiInterface {
  /**
   * Issue a credential from verified claims
   */
  async issueCredentialRaw(
    requestParameters: IssueCredentialOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<IssueCredentialResponse>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling issueCredential().',
      )
    }

    if (requestParameters['issueCredentialRequest'] == null) {
      throw new runtime.RequiredError(
        'issueCredentialRequest',
        'Required parameter "issueCredentialRequest" was null or undefined when calling issueCredential().',
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters['Content-Type'] = 'application/json'

    const response = await this.request(
      {
        path: `/sessions/{id}/issue`.replace(
          `{${'id'}}`,
          encodeURIComponent(String(requestParameters['id'])),
        ),
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: IssueCredentialRequestToJSON(requestParameters['issueCredentialRequest']),
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      IssueCredentialResponseFromJSON(jsonValue),
    )
  }

  /**
   * Issue a credential from verified claims
   */
  async issueCredential(
    requestParameters: IssueCredentialOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<IssueCredentialResponse> {
    const response = await this.issueCredentialRaw(requestParameters, initOverrides)
    return await response.value()
  }
}
