/* tslint:disable */
/* eslint-disable */
/**
 * OwlID Issuer Service
 * Identity verification and credential issuance
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime.js'

export interface PollSessionRequest {
  sessionId: string
}

/**
 * PollingApi - interface
 *
 * @export
 * @interface PollingApiInterface
 */
export interface PollingApiInterface {
  /**
   *
   * @summary Poll session status (for QR polling flows like BankID, Didit webhook).
   * @param {string} sessionId Session ID
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof PollingApiInterface
   */
  pollSessionRaw(
    requestParameters: PollSessionRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<any>>

  /**
   * Poll session status (for QR polling flows like BankID, Didit webhook).
   */
  pollSession(
    requestParameters: PollSessionRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<any>
}

/**
 *
 */
export class PollingApi extends runtime.BaseAPI implements PollingApiInterface {
  /**
   * Poll session status (for QR polling flows like BankID, Didit webhook).
   */
  async pollSessionRaw(
    requestParameters: PollSessionRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<any>> {
    if (requestParameters['sessionId'] == null) {
      throw new runtime.RequiredError(
        'sessionId',
        'Required parameter "sessionId" was null or undefined when calling pollSession().',
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    const response = await this.request(
      {
        path: `/polling/{session_id}`.replace(
          `{${'session_id'}}`,
          encodeURIComponent(String(requestParameters['sessionId'])),
        ),
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    if (this.isJsonMime(response.headers.get('content-type'))) {
      return new runtime.JSONApiResponse<any>(response)
    } else {
      return new runtime.TextApiResponse(response) as any
    }
  }

  /**
   * Poll session status (for QR polling flows like BankID, Didit webhook).
   */
  async pollSession(
    requestParameters: PollSessionRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<any> {
    const response = await this.pollSessionRaw(requestParameters, initOverrides)
    return await response.value()
  }
}
