/* tslint:disable */
/* eslint-disable */
/**
 * OwlID Issuer Service
 * Identity verification and credential issuance
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime.js'
import type { ProviderInfo } from '../models/index.js'
import { ProviderInfoFromJSON, ProviderInfoToJSON } from '../models/index.js'

/**
 * ProvidersApi - interface
 *
 * @export
 * @interface ProvidersApiInterface
 */
export interface ProvidersApiInterface {
  /**
   *
   * @summary List available identity providers (with flow type info)
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof ProvidersApiInterface
   */
  listProvidersRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<ProviderInfo>>>

  /**
   * List available identity providers (with flow type info)
   */
  listProviders(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<ProviderInfo>>
}

/**
 *
 */
export class ProvidersApi extends runtime.BaseAPI implements ProvidersApiInterface {
  /**
   * List available identity providers (with flow type info)
   */
  async listProvidersRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<ProviderInfo>>> {
    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    const response = await this.request(
      {
        path: `/providers`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ProviderInfoFromJSON))
  }

  /**
   * List available identity providers (with flow type info)
   */
  async listProviders(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<ProviderInfo>> {
    const response = await this.listProvidersRaw(initOverrides)
    return await response.value()
  }
}
