/* tslint:disable */
/* eslint-disable */
/**
 * OwlID Issuer Service
 * Identity verification and credential issuance
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime.js'
import type {
  CompleteVerificationResponse,
  CreateSessionRequest,
  CreateSessionResponse,
  SessionResponse,
} from '../models/index.js'
import {
  CompleteVerificationResponseFromJSON,
  CompleteVerificationResponseToJSON,
  CreateSessionRequestFromJSON,
  CreateSessionRequestToJSON,
  CreateSessionResponseFromJSON,
  CreateSessionResponseToJSON,
  SessionResponseFromJSON,
  SessionResponseToJSON,
} from '../models/index.js'

export interface AutoVerifyRequest {
  id: string
}

export interface CompleteVerificationRequest {
  id: string
}

export interface CreateSessionOperationRequest {
  createSessionRequest: CreateSessionRequest
}

export interface GetClaimsRequest {
  id: string
}

export interface GetSessionRequest {
  id: string
}

export interface SubmitIdentityRequest {
  id: string
  body: any | null
}

/**
 * SessionsApi - interface
 *
 * @export
 * @interface SessionsApiInterface
 */
export interface SessionsApiInterface {
  /**
   *
   * @summary Auto-verify with sample data - completes verification without user input Useful for testing the flow with mock providers. In production, real providers would complete via SAML callbacks, webhooks, or form submission.
   * @param {string} id Session ID
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof SessionsApiInterface
   */
  autoVerifyRaw(
    requestParameters: AutoVerifyRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<any>>

  /**
   * Auto-verify with sample data - completes verification without user input Useful for testing the flow with mock providers. In production, real providers would complete via SAML callbacks, webhooks, or form submission.
   */
  autoVerify(
    requestParameters: AutoVerifyRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<any>

  /**
   *
   * @summary Complete verification for webhook_async providers Polls the external provider\'s decision endpoint and returns claims when ready
   * @param {string} id Session ID
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof SessionsApiInterface
   */
  completeVerificationRaw(
    requestParameters: CompleteVerificationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<CompleteVerificationResponse>>

  /**
   * Complete verification for webhook_async providers Polls the external provider\'s decision endpoint and returns claims when ready
   */
  completeVerification(
    requestParameters: CompleteVerificationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<CompleteVerificationResponse>

  /**
   *
   * @summary Create a new verification session
   * @param {CreateSessionRequest} createSessionRequest
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof SessionsApiInterface
   */
  createSessionRaw(
    requestParameters: CreateSessionOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<CreateSessionResponse>>

  /**
   * Create a new verification session
   */
  createSession(
    requestParameters: CreateSessionOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<CreateSessionResponse>

  /**
   *
   * @summary Get verified claims for a session
   * @param {string} id Session ID
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof SessionsApiInterface
   */
  getClaimsRaw(
    requestParameters: GetClaimsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<any>>

  /**
   * Get verified claims for a session
   */
  getClaims(
    requestParameters: GetClaimsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<any>

  /**
   *
   * @summary Get session status
   * @param {string} id Session ID
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof SessionsApiInterface
   */
  getSessionRaw(
    requestParameters: GetSessionRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<SessionResponse>>

  /**
   * Get session status
   */
  getSession(
    requestParameters: GetSessionRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<SessionResponse>

  /**
   *
   * @summary Submit identity data for verification (form-based providers)
   * @param {string} id Session ID
   * @param {any} body
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof SessionsApiInterface
   */
  submitIdentityRaw(
    requestParameters: SubmitIdentityRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<any>>

  /**
   * Submit identity data for verification (form-based providers)
   */
  submitIdentity(
    requestParameters: SubmitIdentityRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<any>
}

/**
 *
 */
export class SessionsApi extends runtime.BaseAPI implements SessionsApiInterface {
  /**
   * Auto-verify with sample data - completes verification without user input Useful for testing the flow with mock providers. In production, real providers would complete via SAML callbacks, webhooks, or form submission.
   */
  async autoVerifyRaw(
    requestParameters: AutoVerifyRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<any>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling autoVerify().',
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    const response = await this.request(
      {
        path: `/sessions/{id}/auto-verify`.replace(
          `{${'id'}}`,
          encodeURIComponent(String(requestParameters['id'])),
        ),
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    if (this.isJsonMime(response.headers.get('content-type'))) {
      return new runtime.JSONApiResponse<any>(response)
    } else {
      return new runtime.TextApiResponse(response) as any
    }
  }

  /**
   * Auto-verify with sample data - completes verification without user input Useful for testing the flow with mock providers. In production, real providers would complete via SAML callbacks, webhooks, or form submission.
   */
  async autoVerify(
    requestParameters: AutoVerifyRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<any> {
    const response = await this.autoVerifyRaw(requestParameters, initOverrides)
    return await response.value()
  }

  /**
   * Complete verification for webhook_async providers Polls the external provider\'s decision endpoint and returns claims when ready
   */
  async completeVerificationRaw(
    requestParameters: CompleteVerificationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<CompleteVerificationResponse>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling completeVerification().',
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    const response = await this.request(
      {
        path: `/sessions/{id}/complete`.replace(
          `{${'id'}}`,
          encodeURIComponent(String(requestParameters['id'])),
        ),
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      CompleteVerificationResponseFromJSON(jsonValue),
    )
  }

  /**
   * Complete verification for webhook_async providers Polls the external provider\'s decision endpoint and returns claims when ready
   */
  async completeVerification(
    requestParameters: CompleteVerificationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<CompleteVerificationResponse> {
    const response = await this.completeVerificationRaw(requestParameters, initOverrides)
    return await response.value()
  }

  /**
   * Create a new verification session
   */
  async createSessionRaw(
    requestParameters: CreateSessionOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<CreateSessionResponse>> {
    if (requestParameters['createSessionRequest'] == null) {
      throw new runtime.RequiredError(
        'createSessionRequest',
        'Required parameter "createSessionRequest" was null or undefined when calling createSession().',
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters['Content-Type'] = 'application/json'

    const response = await this.request(
      {
        path: `/sessions`,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: CreateSessionRequestToJSON(requestParameters['createSessionRequest']),
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      CreateSessionResponseFromJSON(jsonValue),
    )
  }

  /**
   * Create a new verification session
   */
  async createSession(
    requestParameters: CreateSessionOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<CreateSessionResponse> {
    const response = await this.createSessionRaw(requestParameters, initOverrides)
    return await response.value()
  }

  /**
   * Get verified claims for a session
   */
  async getClaimsRaw(
    requestParameters: GetClaimsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<any>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling getClaims().',
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    const response = await this.request(
      {
        path: `/sessions/{id}/claims`.replace(
          `{${'id'}}`,
          encodeURIComponent(String(requestParameters['id'])),
        ),
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    if (this.isJsonMime(response.headers.get('content-type'))) {
      return new runtime.JSONApiResponse<any>(response)
    } else {
      return new runtime.TextApiResponse(response) as any
    }
  }

  /**
   * Get verified claims for a session
   */
  async getClaims(
    requestParameters: GetClaimsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<any> {
    const response = await this.getClaimsRaw(requestParameters, initOverrides)
    return await response.value()
  }

  /**
   * Get session status
   */
  async getSessionRaw(
    requestParameters: GetSessionRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<SessionResponse>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling getSession().',
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    const response = await this.request(
      {
        path: `/sessions/{id}`.replace(
          `{${'id'}}`,
          encodeURIComponent(String(requestParameters['id'])),
        ),
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) => SessionResponseFromJSON(jsonValue))
  }

  /**
   * Get session status
   */
  async getSession(
    requestParameters: GetSessionRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<SessionResponse> {
    const response = await this.getSessionRaw(requestParameters, initOverrides)
    return await response.value()
  }

  /**
   * Submit identity data for verification (form-based providers)
   */
  async submitIdentityRaw(
    requestParameters: SubmitIdentityRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<any>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling submitIdentity().',
      )
    }

    if (requestParameters['body'] == null) {
      throw new runtime.RequiredError(
        'body',
        'Required parameter "body" was null or undefined when calling submitIdentity().',
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters['Content-Type'] = 'application/json'

    const response = await this.request(
      {
        path: `/sessions/{id}/submit`.replace(
          `{${'id'}}`,
          encodeURIComponent(String(requestParameters['id'])),
        ),
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: requestParameters['body'] as any,
      },
      initOverrides,
    )

    if (this.isJsonMime(response.headers.get('content-type'))) {
      return new runtime.JSONApiResponse<any>(response)
    } else {
      return new runtime.TextApiResponse(response) as any
    }
  }

  /**
   * Submit identity data for verification (form-based providers)
   */
  async submitIdentity(
    requestParameters: SubmitIdentityRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<any> {
    const response = await this.submitIdentityRaw(requestParameters, initOverrides)
    return await response.value()
  }
}
