/* tslint:disable */
/* eslint-disable */
/**
 * OwlID Verification Service
 * Token verification, trusted issuer management, and credential revocation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime.js'
import type {
  ApiKeyInfo,
  CreateApiKeyRequest,
  CreateApiKeyResponse,
  MidnightStatus,
  ToggleResponse,
} from '../models/index.js'
import {
  ApiKeyInfoFromJSON,
  ApiKeyInfoToJSON,
  CreateApiKeyRequestFromJSON,
  CreateApiKeyRequestToJSON,
  CreateApiKeyResponseFromJSON,
  CreateApiKeyResponseToJSON,
  MidnightStatusFromJSON,
  MidnightStatusToJSON,
  ToggleResponseFromJSON,
  ToggleResponseToJSON,
} from '../models/index.js'

export interface CreateApiKeyOperationRequest {
  createApiKeyRequest: CreateApiKeyRequest
}

export interface DeactivateApiKeyRequest {
  id: string
}

/**
 * AdminApi - interface
 *
 * @export
 * @interface AdminApiInterface
 */
export interface AdminApiInterface {
  /**
   *
   * @summary Create a new API key
   * @param {CreateApiKeyRequest} createApiKeyRequest
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof AdminApiInterface
   */
  createApiKeyRaw(
    requestParameters: CreateApiKeyOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<CreateApiKeyResponse>>

  /**
   * Create a new API key
   */
  createApiKey(
    requestParameters: CreateApiKeyOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<CreateApiKeyResponse>

  /**
   *
   * @summary Deactivate an API key
   * @param {string} id API key UUID
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof AdminApiInterface
   */
  deactivateApiKeyRaw(
    requestParameters: DeactivateApiKeyRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>>

  /**
   * Deactivate an API key
   */
  deactivateApiKey(
    requestParameters: DeactivateApiKeyRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void>

  /**
   *
   * @summary Disable the Midnight integration.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof AdminApiInterface
   */
  disableMidnightRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<ToggleResponse>>

  /**
   * Disable the Midnight integration.
   */
  disableMidnight(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<ToggleResponse>

  /**
   *
   * @summary Enable the Midnight integration.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof AdminApiInterface
   */
  enableMidnightRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<ToggleResponse>>

  /**
   * Enable the Midnight integration.
   */
  enableMidnight(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<ToggleResponse>

  /**
   *
   * @summary Get current status of the Midnight integration.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof AdminApiInterface
   */
  getMidnightStatusRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<MidnightStatus>>

  /**
   * Get current status of the Midnight integration.
   */
  getMidnightStatus(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<MidnightStatus>

  /**
   *
   * @summary List all API keys
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof AdminApiInterface
   */
  listApiKeysRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<ApiKeyInfo>>>

  /**
   * List all API keys
   */
  listApiKeys(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<ApiKeyInfo>>
}

/**
 *
 */
export class AdminApi extends runtime.BaseAPI implements AdminApiInterface {
  /**
   * Create a new API key
   */
  async createApiKeyRaw(
    requestParameters: CreateApiKeyOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<CreateApiKeyResponse>> {
    if (requestParameters['createApiKeyRequest'] == null) {
      throw new runtime.RequiredError(
        'createApiKeyRequest',
        'Required parameter "createApiKeyRequest" was null or undefined when calling createApiKey().',
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters['Content-Type'] = 'application/json'

    const response = await this.request(
      {
        path: `/admin/api-keys`,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: CreateApiKeyRequestToJSON(requestParameters['createApiKeyRequest']),
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      CreateApiKeyResponseFromJSON(jsonValue),
    )
  }

  /**
   * Create a new API key
   */
  async createApiKey(
    requestParameters: CreateApiKeyOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<CreateApiKeyResponse> {
    const response = await this.createApiKeyRaw(requestParameters, initOverrides)
    return await response.value()
  }

  /**
   * Deactivate an API key
   */
  async deactivateApiKeyRaw(
    requestParameters: DeactivateApiKeyRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling deactivateApiKey().',
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    const response = await this.request(
      {
        path: `/admin/api-keys/{id}`.replace(
          `{${'id'}}`,
          encodeURIComponent(String(requestParameters['id'])),
        ),
        method: 'DELETE',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.VoidApiResponse(response)
  }

  /**
   * Deactivate an API key
   */
  async deactivateApiKey(
    requestParameters: DeactivateApiKeyRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.deactivateApiKeyRaw(requestParameters, initOverrides)
  }

  /**
   * Disable the Midnight integration.
   */
  async disableMidnightRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<ToggleResponse>> {
    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    const response = await this.request(
      {
        path: `/admin/midnight/disable`,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) => ToggleResponseFromJSON(jsonValue))
  }

  /**
   * Disable the Midnight integration.
   */
  async disableMidnight(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<ToggleResponse> {
    const response = await this.disableMidnightRaw(initOverrides)
    return await response.value()
  }

  /**
   * Enable the Midnight integration.
   */
  async enableMidnightRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<ToggleResponse>> {
    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    const response = await this.request(
      {
        path: `/admin/midnight/enable`,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) => ToggleResponseFromJSON(jsonValue))
  }

  /**
   * Enable the Midnight integration.
   */
  async enableMidnight(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<ToggleResponse> {
    const response = await this.enableMidnightRaw(initOverrides)
    return await response.value()
  }

  /**
   * Get current status of the Midnight integration.
   */
  async getMidnightStatusRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<MidnightStatus>> {
    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    const response = await this.request(
      {
        path: `/admin/midnight/status`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) => MidnightStatusFromJSON(jsonValue))
  }

  /**
   * Get current status of the Midnight integration.
   */
  async getMidnightStatus(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<MidnightStatus> {
    const response = await this.getMidnightStatusRaw(initOverrides)
    return await response.value()
  }

  /**
   * List all API keys
   */
  async listApiKeysRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<ApiKeyInfo>>> {
    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    const response = await this.request(
      {
        path: `/admin/api-keys`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ApiKeyInfoFromJSON))
  }

  /**
   * List all API keys
   */
  async listApiKeys(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<ApiKeyInfo>> {
    const response = await this.listApiKeysRaw(initOverrides)
    return await response.value()
  }
}
