/* tslint:disable */
/* eslint-disable */
/**
 * OwlID Verification Service
 * Token verification, trusted issuer management, and credential revocation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime.js'
import type { AddTrustedIssuerRequest, AddTrustedIssuerResponse } from '../models/index.js'
import {
  AddTrustedIssuerRequestFromJSON,
  AddTrustedIssuerRequestToJSON,
  AddTrustedIssuerResponseFromJSON,
  AddTrustedIssuerResponseToJSON,
} from '../models/index.js'

export interface AddTrustedIssuerOperationRequest {
  addTrustedIssuerRequest: AddTrustedIssuerRequest
}

/**
 * AdminIssuersApi - interface
 *
 * @export
 * @interface AdminIssuersApiInterface
 */
export interface AdminIssuersApiInterface {
  /**
   *
   * @summary Add a trusted issuer
   * @param {AddTrustedIssuerRequest} addTrustedIssuerRequest
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof AdminIssuersApiInterface
   */
  addTrustedIssuerRaw(
    requestParameters: AddTrustedIssuerOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<AddTrustedIssuerResponse>>

  /**
   * Add a trusted issuer
   */
  addTrustedIssuer(
    requestParameters: AddTrustedIssuerOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<AddTrustedIssuerResponse>
}

/**
 *
 */
export class AdminIssuersApi extends runtime.BaseAPI implements AdminIssuersApiInterface {
  /**
   * Add a trusted issuer
   */
  async addTrustedIssuerRaw(
    requestParameters: AddTrustedIssuerOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<AddTrustedIssuerResponse>> {
    if (requestParameters['addTrustedIssuerRequest'] == null) {
      throw new runtime.RequiredError(
        'addTrustedIssuerRequest',
        'Required parameter "addTrustedIssuerRequest" was null or undefined when calling addTrustedIssuer().',
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters['Content-Type'] = 'application/json'

    const response = await this.request(
      {
        path: `/trusted-issuers`,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: AddTrustedIssuerRequestToJSON(requestParameters['addTrustedIssuerRequest']),
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      AddTrustedIssuerResponseFromJSON(jsonValue),
    )
  }

  /**
   * Add a trusted issuer
   */
  async addTrustedIssuer(
    requestParameters: AddTrustedIssuerOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<AddTrustedIssuerResponse> {
    const response = await this.addTrustedIssuerRaw(requestParameters, initOverrides)
    return await response.value()
  }
}
