/* tslint:disable */
/* eslint-disable */
/**
 * OwlID Verification Service
 * SD-JWT VC presentation verification, trusted issuer management, and credential revocation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime.js'
import type { ErasureReceipt } from '../models/index.js'
import { ErasureReceiptFromJSON, ErasureReceiptToJSON } from '../models/index.js'

export interface GdprErasureRequest {
  ownerPublicKey: string
}

/**
 * GdprApi - interface
 *
 * @export
 * @interface GdprApiInterface
 */
export interface GdprApiInterface {
  /**
   * This endpoint: 1. Revokes all active credentials for the owner 2. Anonymizes credential attributes in the database 3. Retains non-personal audit records (hashes, timestamps) 4. Returns an erasure receipt  Requires admin + gdpr permissions.
   * @summary Handle GDPR right-to-erasure request
   * @param {string} ownerPublicKey Owner\&#39;s public key to erase
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof GdprApiInterface
   */
  gdprErasureRaw(
    requestParameters: GdprErasureRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<ErasureReceipt>>

  /**
   * This endpoint: 1. Revokes all active credentials for the owner 2. Anonymizes credential attributes in the database 3. Retains non-personal audit records (hashes, timestamps) 4. Returns an erasure receipt  Requires admin + gdpr permissions.
   * Handle GDPR right-to-erasure request
   */
  gdprErasure(
    requestParameters: GdprErasureRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<ErasureReceipt>
}

/**
 *
 */
export class GdprApi extends runtime.BaseAPI implements GdprApiInterface {
  /**
   * This endpoint: 1. Revokes all active credentials for the owner 2. Anonymizes credential attributes in the database 3. Retains non-personal audit records (hashes, timestamps) 4. Returns an erasure receipt  Requires admin + gdpr permissions.
   * Handle GDPR right-to-erasure request
   */
  async gdprErasureRaw(
    requestParameters: GdprErasureRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<ErasureReceipt>> {
    if (requestParameters['ownerPublicKey'] == null) {
      throw new runtime.RequiredError(
        'ownerPublicKey',
        'Required parameter "ownerPublicKey" was null or undefined when calling gdprErasure().',
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    const response = await this.request(
      {
        path: `/admin/gdpr-erasure/{owner_public_key}`.replace(
          `{${'owner_public_key'}}`,
          encodeURIComponent(String(requestParameters['ownerPublicKey'])),
        ),
        method: 'DELETE',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) => ErasureReceiptFromJSON(jsonValue))
  }

  /**
   * This endpoint: 1. Revokes all active credentials for the owner 2. Anonymizes credential attributes in the database 3. Retains non-personal audit records (hashes, timestamps) 4. Returns an erasure receipt  Requires admin + gdpr permissions.
   * Handle GDPR right-to-erasure request
   */
  async gdprErasure(
    requestParameters: GdprErasureRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<ErasureReceipt> {
    const response = await this.gdprErasureRaw(requestParameters, initOverrides)
    return await response.value()
  }
}
