/* tslint:disable */
/* eslint-disable */
/**
 * OwlID Verification Service
 * SD-JWT VC presentation verification, trusted issuer management, and credential revocation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime.js'
import type { MetricsResponse } from '../models/index.js'
import { MetricsResponseFromJSON, MetricsResponseToJSON } from '../models/index.js'

/**
 * MetricsApi - interface
 *
 * @export
 * @interface MetricsApiInterface
 */
export interface MetricsApiInterface {
  /**
   *
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof MetricsApiInterface
   */
  getMetricsRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<MetricsResponse>>

  /**
   */
  getMetrics(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MetricsResponse>
}

/**
 *
 */
export class MetricsApi extends runtime.BaseAPI implements MetricsApiInterface {
  /**
   */
  async getMetricsRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<MetricsResponse>> {
    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    const response = await this.request(
      {
        path: `/metrics`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) => MetricsResponseFromJSON(jsonValue))
  }

  /**
   */
  async getMetrics(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<MetricsResponse> {
    const response = await this.getMetricsRaw(initOverrides)
    return await response.value()
  }
}
