/* tslint:disable */
/* eslint-disable */
/**
 * OwlID Verification Service
 * Token verification, trusted issuer management, and credential revocation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js'
/**
 * Request to add a trusted issuer
 * @export
 * @interface AddTrustedIssuerRequest
 */
export interface AddTrustedIssuerRequest {
  /**
   *
   * @type {string}
   * @memberof AddTrustedIssuerRequest
   */
  description?: string | null
  /**
   *
   * @type {string}
   * @memberof AddTrustedIssuerRequest
   */
  issuerUrl?: string | null
  /**
   *
   * @type {string}
   * @memberof AddTrustedIssuerRequest
   */
  name: string
  /**
   *
   * @type {string}
   * @memberof AddTrustedIssuerRequest
   */
  publicKey: string
}

/**
 * Check if a given object implements the AddTrustedIssuerRequest interface.
 */
export function instanceOfAddTrustedIssuerRequest(value: object): value is AddTrustedIssuerRequest {
  if (!('name' in value) || value['name'] === undefined) return false
  if (!('publicKey' in value) || value['publicKey'] === undefined) return false
  return true
}

export function AddTrustedIssuerRequestFromJSON(json: any): AddTrustedIssuerRequest {
  return AddTrustedIssuerRequestFromJSONTyped(json, false)
}

export function AddTrustedIssuerRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AddTrustedIssuerRequest {
  if (json == null) {
    return json
  }
  return {
    description: json['description'] == null ? undefined : json['description'],
    issuerUrl: json['issuerUrl'] == null ? undefined : json['issuerUrl'],
    name: json['name'],
    publicKey: json['publicKey'],
  }
}

export function AddTrustedIssuerRequestToJSON(json: any): AddTrustedIssuerRequest {
  return AddTrustedIssuerRequestToJSONTyped(json, false)
}

export function AddTrustedIssuerRequestToJSONTyped(
  value?: AddTrustedIssuerRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    description: value['description'],
    issuerUrl: value['issuerUrl'],
    name: value['name'],
    publicKey: value['publicKey'],
  }
}
