/* tslint:disable */
/* eslint-disable */
/**
 * OwlID Verification Service
 * SD-JWT VC presentation verification, trusted issuer management, and credential revocation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js'
import type { KeyType } from './KeyType.js'
import {
  KeyTypeFromJSON,
  KeyTypeFromJSONTyped,
  KeyTypeToJSON,
  KeyTypeToJSONTyped,
} from './KeyType.js'
import type { Environment } from './Environment.js'
import {
  EnvironmentFromJSON,
  EnvironmentFromJSONTyped,
  EnvironmentToJSON,
  EnvironmentToJSONTyped,
} from './Environment.js'

/**
 *
 * @export
 * @interface ApiKeyInfo
 */
export interface ApiKeyInfo {
  /**
   *
   * @type {string}
   * @memberof ApiKeyInfo
   */
  createdAt: string
  /**
   *
   * @type {string}
   * @memberof ApiKeyInfo
   */
  createdBy?: string | null
  /**
   *
   * @type {string}
   * @memberof ApiKeyInfo
   */
  description?: string | null
  /**
   *
   * @type {Environment}
   * @memberof ApiKeyInfo
   */
  environment: Environment
  /**
   *
   * @type {string}
   * @memberof ApiKeyInfo
   */
  id: string
  /**
   *
   * @type {boolean}
   * @memberof ApiKeyInfo
   */
  isActive: boolean
  /**
   *
   * @type {string}
   * @memberof ApiKeyInfo
   */
  keyPreview?: string | null
  /**
   *
   * @type {KeyType}
   * @memberof ApiKeyInfo
   */
  keyType: KeyType
  /**
   *
   * @type {string}
   * @memberof ApiKeyInfo
   */
  lastUsedAt?: string | null
  /**
   *
   * @type {string}
   * @memberof ApiKeyInfo
   */
  name: string
  /**
   *
   * @type {Array<string>}
   * @memberof ApiKeyInfo
   */
  permissions: Array<string>
}

/**
 * Check if a given object implements the ApiKeyInfo interface.
 */
export function instanceOfApiKeyInfo(value: object): value is ApiKeyInfo {
  if (!('createdAt' in value) || value['createdAt'] === undefined) return false
  if (!('environment' in value) || value['environment'] === undefined) return false
  if (!('id' in value) || value['id'] === undefined) return false
  if (!('isActive' in value) || value['isActive'] === undefined) return false
  if (!('keyType' in value) || value['keyType'] === undefined) return false
  if (!('name' in value) || value['name'] === undefined) return false
  if (!('permissions' in value) || value['permissions'] === undefined) return false
  return true
}

export function ApiKeyInfoFromJSON(json: any): ApiKeyInfo {
  return ApiKeyInfoFromJSONTyped(json, false)
}

export function ApiKeyInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiKeyInfo {
  if (json == null) {
    return json
  }
  return {
    createdAt: json['createdAt'],
    createdBy: json['createdBy'] == null ? undefined : json['createdBy'],
    description: json['description'] == null ? undefined : json['description'],
    environment: EnvironmentFromJSON(json['environment']),
    id: json['id'],
    isActive: json['isActive'],
    keyPreview: json['keyPreview'] == null ? undefined : json['keyPreview'],
    keyType: KeyTypeFromJSON(json['keyType']),
    lastUsedAt: json['lastUsedAt'] == null ? undefined : json['lastUsedAt'],
    name: json['name'],
    permissions: json['permissions'],
  }
}

export function ApiKeyInfoToJSON(json: any): ApiKeyInfo {
  return ApiKeyInfoToJSONTyped(json, false)
}

export function ApiKeyInfoToJSONTyped(
  value?: ApiKeyInfo | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    createdAt: value['createdAt'],
    createdBy: value['createdBy'],
    description: value['description'],
    environment: EnvironmentToJSON(value['environment']),
    id: value['id'],
    isActive: value['isActive'],
    keyPreview: value['keyPreview'],
    keyType: KeyTypeToJSON(value['keyType']),
    lastUsedAt: value['lastUsedAt'],
    name: value['name'],
    permissions: value['permissions'],
  }
}
