/* tslint:disable */
/* eslint-disable */
/**
 * OwlID Verification Service
 * Token verification, trusted issuer management, and credential revocation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js'
/**
 * Response containing a server-generated challenge
 * @export
 * @interface ChallengeResponse
 */
export interface ChallengeResponse {
  /**
   * Server-generated challenge (hex, 16 chars). Valid for 5 minutes.
   * @type {string}
   * @memberof ChallengeResponse
   */
  challenge: string
  /**
   * Seconds until the challenge expires
   * @type {number}
   * @memberof ChallengeResponse
   */
  expiresIn: number
}

/**
 * Check if a given object implements the ChallengeResponse interface.
 */
export function instanceOfChallengeResponse(value: object): value is ChallengeResponse {
  if (!('challenge' in value) || value['challenge'] === undefined) return false
  if (!('expiresIn' in value) || value['expiresIn'] === undefined) return false
  return true
}

export function ChallengeResponseFromJSON(json: any): ChallengeResponse {
  return ChallengeResponseFromJSONTyped(json, false)
}

export function ChallengeResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ChallengeResponse {
  if (json == null) {
    return json
  }
  return {
    challenge: json['challenge'],
    expiresIn: json['expiresIn'],
  }
}

export function ChallengeResponseToJSON(json: any): ChallengeResponse {
  return ChallengeResponseToJSONTyped(json, false)
}

export function ChallengeResponseToJSONTyped(
  value?: ChallengeResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    challenge: value['challenge'],
    expiresIn: value['expiresIn'],
  }
}
