/* tslint:disable */
/* eslint-disable */
/**
 * OwlID Verification Service
 * SD-JWT VC presentation verification, trusted issuer management, and credential revocation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js'
/**
 *
 * @export
 * @interface CheckPredicateRequest
 */
export interface CheckPredicateRequest {
  /**
   * Required for `unique_personhood` (hex, 32 bytes).
   * @type {string}
   * @memberof CheckPredicateRequest
   */
  appId?: string | null
  /**
   * Required for `nationality` and `residency` — the verifier-supplied
   * ISO 3166-1 alpha-2 country set (≤64 codes) the attestation was
   * minted against. The on-chain key binds to a hash of this exact
   * set, so a "Dutch resident" attestation does not satisfy an
   * "EU resident" check (and vice versa).
   * @type {Array<string>}
   * @memberof CheckPredicateRequest
   */
  countries?: Array<string> | null
  /**
   * SD-JWT VC credential_id (hex, 32 bytes) — issuer-signed.
   * @type {string}
   * @memberof CheckPredicateRequest
   */
  credentialId: string
  /**
   * Required for `unique_personhood` (hex, 32 bytes).
   * @type {string}
   * @memberof CheckPredicateRequest
   */
  epoch?: string | null
  /**
   * Required for `age_range`.
   * @type {number}
   * @memberof CheckPredicateRequest
   */
  maxAge?: number | null
  /**
   * Required for `age_range` (`age in [min_age, max_age]`).
   * @type {number}
   * @memberof CheckPredicateRequest
   */
  minAge?: number | null
  /**
   * One of: `age` | `kyc` | `nationality` | `residency` | `age_range`
   * | `email_verified` | `unique_personhood`.
   * @type {string}
   * @memberof CheckPredicateRequest
   */
  predicate: string
  /**
   * Required for `age`, `kyc` (`value >= threshold`).
   * @type {number}
   * @memberof CheckPredicateRequest
   */
  threshold?: number | null
  /**
   * Required for `nationality` and `residency` — the OID4VP verifier
   * `client_id` (typically the response_uri). Folded into the setHash
   * so two verifiers asking the same allowed-set produce distinct
   * on-chain attestation keys (anti-cross-verifier correlation).
   * @type {string}
   * @memberof CheckPredicateRequest
   */
  verifierId?: string | null
}

/**
 * Check if a given object implements the CheckPredicateRequest interface.
 */
export function instanceOfCheckPredicateRequest(value: object): value is CheckPredicateRequest {
  if (!('credentialId' in value) || value['credentialId'] === undefined) return false
  if (!('predicate' in value) || value['predicate'] === undefined) return false
  return true
}

export function CheckPredicateRequestFromJSON(json: any): CheckPredicateRequest {
  return CheckPredicateRequestFromJSONTyped(json, false)
}

export function CheckPredicateRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CheckPredicateRequest {
  if (json == null) {
    return json
  }
  return {
    appId: json['appId'] == null ? undefined : json['appId'],
    countries: json['countries'] == null ? undefined : json['countries'],
    credentialId: json['credentialId'],
    epoch: json['epoch'] == null ? undefined : json['epoch'],
    maxAge: json['maxAge'] == null ? undefined : json['maxAge'],
    minAge: json['minAge'] == null ? undefined : json['minAge'],
    predicate: json['predicate'],
    threshold: json['threshold'] == null ? undefined : json['threshold'],
    verifierId: json['verifierId'] == null ? undefined : json['verifierId'],
  }
}

export function CheckPredicateRequestToJSON(json: any): CheckPredicateRequest {
  return CheckPredicateRequestToJSONTyped(json, false)
}

export function CheckPredicateRequestToJSONTyped(
  value?: CheckPredicateRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    appId: value['appId'],
    countries: value['countries'],
    credentialId: value['credentialId'],
    epoch: value['epoch'],
    maxAge: value['maxAge'],
    minAge: value['minAge'],
    predicate: value['predicate'],
    threshold: value['threshold'],
    verifierId: value['verifierId'],
  }
}
