/* tslint:disable */
/* eslint-disable */
/**
 * OwlID Verification Service
 * SD-JWT VC presentation verification, trusted issuer management, and credential revocation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js'
import type { KeyType } from './KeyType.js'
import {
  KeyTypeFromJSON,
  KeyTypeFromJSONTyped,
  KeyTypeToJSON,
  KeyTypeToJSONTyped,
} from './KeyType.js'
import type { Environment } from './Environment.js'
import {
  EnvironmentFromJSON,
  EnvironmentFromJSONTyped,
  EnvironmentToJSON,
  EnvironmentToJSONTyped,
} from './Environment.js'

/**
 *
 * @export
 * @interface CreateApiKeyResponse
 */
export interface CreateApiKeyResponse {
  /**
   *
   * @type {Environment}
   * @memberof CreateApiKeyResponse
   */
  environment: Environment
  /**
   * Raw API key — returned ONCE, never readable again.
   * @type {string}
   * @memberof CreateApiKeyResponse
   */
  key: string
  /**
   * Human-safe key fingerprint (`owlid_sk_live_…AbCd`) for later display.
   * @type {string}
   * @memberof CreateApiKeyResponse
   */
  keyPreview: string
  /**
   *
   * @type {KeyType}
   * @memberof CreateApiKeyResponse
   */
  keyType: KeyType
  /**
   *
   * @type {string}
   * @memberof CreateApiKeyResponse
   */
  name: string
  /**
   *
   * @type {Array<string>}
   * @memberof CreateApiKeyResponse
   */
  permissions: Array<string>
}

/**
 * Check if a given object implements the CreateApiKeyResponse interface.
 */
export function instanceOfCreateApiKeyResponse(value: object): value is CreateApiKeyResponse {
  if (!('environment' in value) || value['environment'] === undefined) return false
  if (!('key' in value) || value['key'] === undefined) return false
  if (!('keyPreview' in value) || value['keyPreview'] === undefined) return false
  if (!('keyType' in value) || value['keyType'] === undefined) return false
  if (!('name' in value) || value['name'] === undefined) return false
  if (!('permissions' in value) || value['permissions'] === undefined) return false
  return true
}

export function CreateApiKeyResponseFromJSON(json: any): CreateApiKeyResponse {
  return CreateApiKeyResponseFromJSONTyped(json, false)
}

export function CreateApiKeyResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreateApiKeyResponse {
  if (json == null) {
    return json
  }
  return {
    environment: EnvironmentFromJSON(json['environment']),
    key: json['key'],
    keyPreview: json['keyPreview'],
    keyType: KeyTypeFromJSON(json['keyType']),
    name: json['name'],
    permissions: json['permissions'],
  }
}

export function CreateApiKeyResponseToJSON(json: any): CreateApiKeyResponse {
  return CreateApiKeyResponseToJSONTyped(json, false)
}

export function CreateApiKeyResponseToJSONTyped(
  value?: CreateApiKeyResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    environment: EnvironmentToJSON(value['environment']),
    key: value['key'],
    keyPreview: value['keyPreview'],
    keyType: KeyTypeToJSON(value['keyType']),
    name: value['name'],
    permissions: value['permissions'],
  }
}
