/* tslint:disable */
/* eslint-disable */
/**
 * OwlID Verification Service
 * SD-JWT VC presentation verification, trusted issuer management, and credential revocation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js'
import type { DcqlRequest } from './DcqlRequest.js'
import {
  DcqlRequestFromJSON,
  DcqlRequestFromJSONTyped,
  DcqlRequestToJSON,
  DcqlRequestToJSONTyped,
} from './DcqlRequest.js'

/**
 *
 * @export
 * @interface CreatePresentationRequest
 */
export interface CreatePresentationRequest {
  /**
   * Expected KB-JWT `aud` — defaults to the response_uri when absent.
   * @type {string}
   * @memberof CreatePresentationRequest
   */
  audience?: string | null
  /**
   * Optional OpenID4VP §6 DCQL query the holder should solve.
   * Surfaced to external wallets via `GET /openid4vp/request/{id}`.
   * OwlID's own holder app receives the same query over the
   * presentation WebSocket; both paths converge on `/openid4vp/response`.
   * @type {DcqlRequest}
   * @memberof CreatePresentationRequest
   */
  dcql?: DcqlRequest | null
  /**
   * Display name shown on the holder's consent screen.
   * @type {string}
   * @memberof CreatePresentationRequest
   */
  verifierName?: string | null
}

/**
 * Check if a given object implements the CreatePresentationRequest interface.
 */
export function instanceOfCreatePresentationRequest(
  value: object,
): value is CreatePresentationRequest {
  return true
}

export function CreatePresentationRequestFromJSON(json: any): CreatePresentationRequest {
  return CreatePresentationRequestFromJSONTyped(json, false)
}

export function CreatePresentationRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreatePresentationRequest {
  if (json == null) {
    return json
  }
  return {
    audience: json['audience'] == null ? undefined : json['audience'],
    dcql: json['dcql'] == null ? undefined : DcqlRequestFromJSON(json['dcql']),
    verifierName: json['verifierName'] == null ? undefined : json['verifierName'],
  }
}

export function CreatePresentationRequestToJSON(json: any): CreatePresentationRequest {
  return CreatePresentationRequestToJSONTyped(json, false)
}

export function CreatePresentationRequestToJSONTyped(
  value?: CreatePresentationRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    audience: value['audience'],
    dcql: DcqlRequestToJSON(value['dcql']),
    verifierName: value['verifierName'],
  }
}
