/* tslint:disable */
/* eslint-disable */
/**
 * OwlID Verification Service
 * SD-JWT VC presentation verification, trusted issuer management, and credential revocation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js'
import type { DcqlCredentialQuery } from './DcqlCredentialQuery.js'
import {
  DcqlCredentialQueryFromJSON,
  DcqlCredentialQueryFromJSONTyped,
  DcqlCredentialQueryToJSON,
  DcqlCredentialQueryToJSONTyped,
} from './DcqlCredentialQuery.js'
import type { DcqlCredentialSet } from './DcqlCredentialSet.js'
import {
  DcqlCredentialSetFromJSON,
  DcqlCredentialSetFromJSONTyped,
  DcqlCredentialSetToJSON,
  DcqlCredentialSetToJSONTyped,
} from './DcqlCredentialSet.js'

/**
 *
 * @export
 * @interface DcqlRequest
 */
export interface DcqlRequest {
  /**
   *
   * @type {Array<DcqlCredentialSet>}
   * @memberof DcqlRequest
   */
  credentialSets?: Array<DcqlCredentialSet> | null
  /**
   *
   * @type {Array<DcqlCredentialQuery>}
   * @memberof DcqlRequest
   */
  credentials: Array<DcqlCredentialQuery>
}

/**
 * Check if a given object implements the DcqlRequest interface.
 */
export function instanceOfDcqlRequest(value: object): value is DcqlRequest {
  if (!('credentials' in value) || value['credentials'] === undefined) return false
  return true
}

export function DcqlRequestFromJSON(json: any): DcqlRequest {
  return DcqlRequestFromJSONTyped(json, false)
}

export function DcqlRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DcqlRequest {
  if (json == null) {
    return json
  }
  return {
    credentialSets:
      json['credential_sets'] == null
        ? undefined
        : (json['credential_sets'] as Array<any>).map(DcqlCredentialSetFromJSON),
    credentials: (json['credentials'] as Array<any>).map(DcqlCredentialQueryFromJSON),
  }
}

export function DcqlRequestToJSON(json: any): DcqlRequest {
  return DcqlRequestToJSONTyped(json, false)
}

export function DcqlRequestToJSONTyped(
  value?: DcqlRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    credential_sets:
      value['credentialSets'] == null
        ? undefined
        : (value['credentialSets'] as Array<any>).map(DcqlCredentialSetToJSON),
    credentials: (value['credentials'] as Array<any>).map(DcqlCredentialQueryToJSON),
  }
}
