/* tslint:disable */
/* eslint-disable */
/**
 * OwlID Verification Service
 * SD-JWT VC presentation verification, trusted issuer management, and credential revocation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js'
/**
 *
 * @export
 * @interface DcqlMeta
 */
export interface DcqlMeta {
  /**
   * For `dc+sd-jwt`, allowed `vct` values.
   * @type {Array<string>}
   * @memberof DcqlMeta
   */
  vctValues?: Array<string>
}

/**
 * Check if a given object implements the DcqlMeta interface.
 */
export function instanceOfDcqlMeta(value: object): value is DcqlMeta {
  return true
}

export function DcqlMetaFromJSON(json: any): DcqlMeta {
  return DcqlMetaFromJSONTyped(json, false)
}

export function DcqlMetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): DcqlMeta {
  if (json == null) {
    return json
  }
  return {
    vctValues: json['vct_values'] == null ? undefined : json['vct_values'],
  }
}

export function DcqlMetaToJSON(json: any): DcqlMeta {
  return DcqlMetaToJSONTyped(json, false)
}

export function DcqlMetaToJSONTyped(
  value?: DcqlMeta | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    vct_values: value['vctValues'],
  }
}
