/* tslint:disable */
/* eslint-disable */
/**
 * OwlID Verification Service
 * SD-JWT VC presentation verification, trusted issuer management, and credential revocation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js'
/**
 *
 * @export
 * @interface DcqlCredentialSet
 */
export interface DcqlCredentialSet {
  /**
   * One row of `options` is sufficient to satisfy the set.  Each
   * entry inside a row is a credential `id` that must be present.
   * @type {Array<Array<string>>}
   * @memberof DcqlCredentialSet
   */
  options: Array<Array<string>>
  /**
   *
   * @type {boolean}
   * @memberof DcqlCredentialSet
   */
  required?: boolean | null
}

/**
 * Check if a given object implements the DcqlCredentialSet interface.
 */
export function instanceOfDcqlCredentialSet(value: object): value is DcqlCredentialSet {
  if (!('options' in value) || value['options'] === undefined) return false
  return true
}

export function DcqlCredentialSetFromJSON(json: any): DcqlCredentialSet {
  return DcqlCredentialSetFromJSONTyped(json, false)
}

export function DcqlCredentialSetFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): DcqlCredentialSet {
  if (json == null) {
    return json
  }
  return {
    options: json['options'],
    required: json['required'] == null ? undefined : json['required'],
  }
}

export function DcqlCredentialSetToJSON(json: any): DcqlCredentialSet {
  return DcqlCredentialSetToJSONTyped(json, false)
}

export function DcqlCredentialSetToJSONTyped(
  value?: DcqlCredentialSet | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    options: value['options'],
    required: value['required'],
  }
}
