/* tslint:disable */
/* eslint-disable */
/**
 * OwlID Verification Service
 * Token verification, trusted issuer management, and credential revocation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @enum {string}
 */
export enum Environment {
  live = 'live',
  test = 'test',
}

export function instanceOfEnvironment(value: any): boolean {
  for (const key in Environment) {
    if (Object.prototype.hasOwnProperty.call(Environment, key)) {
      if (Environment[key as keyof typeof Environment] === value) {
        return true
      }
    }
  }
  return false
}

export function EnvironmentFromJSON(json: any): Environment {
  return EnvironmentFromJSONTyped(json, false)
}

export function EnvironmentFromJSONTyped(json: any, ignoreDiscriminator: boolean): Environment {
  return json as Environment
}

export function EnvironmentToJSON(value?: Environment | null): any {
  return value as any
}

export function EnvironmentToJSONTyped(value: any, ignoreDiscriminator: boolean): Environment {
  return value as Environment
}
