/* tslint:disable */
/* eslint-disable */
/**
 * OwlID Verification Service
 * Token verification, trusted issuer management, and credential revocation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js'
/**
 * GDPR erasure receipt
 * @export
 * @interface ErasureReceipt
 */
export interface ErasureReceipt {
  /**
   * Number of credentials revoked
   * @type {number}
   * @memberof ErasureReceipt
   */
  credentialsRevoked: number
  /**
   * Timestamp of erasure
   * @type {string}
   * @memberof ErasureReceipt
   */
  erasedAt: string
  /**
   * Owner public key that was erased
   * @type {string}
   * @memberof ErasureReceipt
   */
  ownerPublicKey: string
  /**
   * Receipt ID for audit purposes
   * @type {string}
   * @memberof ErasureReceipt
   */
  receiptId: string
  /**
   * Number of records anonymized
   * @type {number}
   * @memberof ErasureReceipt
   */
  recordsAnonymized: number
}

/**
 * Check if a given object implements the ErasureReceipt interface.
 */
export function instanceOfErasureReceipt(value: object): value is ErasureReceipt {
  if (!('credentialsRevoked' in value) || value['credentialsRevoked'] === undefined) return false
  if (!('erasedAt' in value) || value['erasedAt'] === undefined) return false
  if (!('ownerPublicKey' in value) || value['ownerPublicKey'] === undefined) return false
  if (!('receiptId' in value) || value['receiptId'] === undefined) return false
  if (!('recordsAnonymized' in value) || value['recordsAnonymized'] === undefined) return false
  return true
}

export function ErasureReceiptFromJSON(json: any): ErasureReceipt {
  return ErasureReceiptFromJSONTyped(json, false)
}

export function ErasureReceiptFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ErasureReceipt {
  if (json == null) {
    return json
  }
  return {
    credentialsRevoked: json['credentials_revoked'],
    erasedAt: json['erased_at'],
    ownerPublicKey: json['owner_public_key'],
    receiptId: json['receipt_id'],
    recordsAnonymized: json['records_anonymized'],
  }
}

export function ErasureReceiptToJSON(json: any): ErasureReceipt {
  return ErasureReceiptToJSONTyped(json, false)
}

export function ErasureReceiptToJSONTyped(
  value?: ErasureReceipt | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    credentials_revoked: value['credentialsRevoked'],
    erased_at: value['erasedAt'],
    owner_public_key: value['ownerPublicKey'],
    receipt_id: value['receiptId'],
    records_anonymized: value['recordsAnonymized'],
  }
}
