/* tslint:disable */
/* eslint-disable */
/**
 * OwlID Verification Service
 * SD-JWT VC presentation verification, trusted issuer management, and credential revocation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @enum {string}
 */
export enum KeyType {
  pk = 'pk',
  sk = 'sk',
}

export function instanceOfKeyType(value: any): boolean {
  for (const key in KeyType) {
    if (Object.prototype.hasOwnProperty.call(KeyType, key)) {
      if (KeyType[key as keyof typeof KeyType] === value) {
        return true
      }
    }
  }
  return false
}

export function KeyTypeFromJSON(json: any): KeyType {
  return KeyTypeFromJSONTyped(json, false)
}

export function KeyTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): KeyType {
  return json as KeyType
}

export function KeyTypeToJSON(value?: KeyType | null): any {
  return value as any
}

export function KeyTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): KeyType {
  return value as KeyType
}
