/* tslint:disable */
/* eslint-disable */
/**
 * OwlID Verification Service
 * SD-JWT VC presentation verification, trusted issuer management, and credential revocation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js'
/**
 *
 * @export
 * @interface LoginResponse
 */
export interface LoginResponse {
  /**
   *
   * @type {number}
   * @memberof LoginResponse
   */
  expiresIn: number
  /**
   * `true` when the operator just authenticated with the built-in
   * default password (`admin`/`admin`). The admin SPA must intercept
   * this and force the user through `POST /admin/password` before
   * surfacing the dashboard. Backend already issued a session cookie
   * so the change-password call can carry it; the SPA still gates
   * every other route until rotation completes.
   * @type {boolean}
   * @memberof LoginResponse
   */
  mustChangeDefaultPassword: boolean
  /**
   *
   * @type {string}
   * @memberof LoginResponse
   */
  token: string
  /**
   *
   * @type {string}
   * @memberof LoginResponse
   */
  username: string
}

/**
 * Check if a given object implements the LoginResponse interface.
 */
export function instanceOfLoginResponse(value: object): value is LoginResponse {
  if (!('expiresIn' in value) || value['expiresIn'] === undefined) return false
  if (!('mustChangeDefaultPassword' in value) || value['mustChangeDefaultPassword'] === undefined)
    return false
  if (!('token' in value) || value['token'] === undefined) return false
  if (!('username' in value) || value['username'] === undefined) return false
  return true
}

export function LoginResponseFromJSON(json: any): LoginResponse {
  return LoginResponseFromJSONTyped(json, false)
}

export function LoginResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginResponse {
  if (json == null) {
    return json
  }
  return {
    expiresIn: json['expiresIn'],
    mustChangeDefaultPassword: json['mustChangeDefaultPassword'],
    token: json['token'],
    username: json['username'],
  }
}

export function LoginResponseToJSON(json: any): LoginResponse {
  return LoginResponseToJSONTyped(json, false)
}

export function LoginResponseToJSONTyped(
  value?: LoginResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    expiresIn: value['expiresIn'],
    mustChangeDefaultPassword: value['mustChangeDefaultPassword'],
    token: value['token'],
    username: value['username'],
  }
}
