/* tslint:disable */
/* eslint-disable */
/**
 * OwlID Verification Service
 * Token verification, trusted issuer management, and credential revocation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js'
import type { SidecarHealth } from './SidecarHealth.js'
import {
  SidecarHealthFromJSON,
  SidecarHealthFromJSONTyped,
  SidecarHealthToJSON,
  SidecarHealthToJSONTyped,
} from './SidecarHealth.js'

/**
 *
 * @export
 * @interface MidnightStatus
 */
export interface MidnightStatus {
  /**
   * Whether the service has a sidecar client at all (configured at boot).
   * `false` means the service was started without a sidecar URL — the
   * admin toggle is inert until the operator restarts with one.
   * @type {boolean}
   * @memberof MidnightStatus
   */
  configured: boolean
  /**
   * Runtime flag: true if the sidecar gate is open.
   * @type {boolean}
   * @memberof MidnightStatus
   */
  enabled: boolean
  /**
   * Sidecar health probe outcome.
   * @type {SidecarHealth}
   * @memberof MidnightStatus
   */
  sidecar: SidecarHealth
  /**
   * Sidecar base URL the service is pointed at.
   * @type {string}
   * @memberof MidnightStatus
   */
  sidecarUrl?: string | null
}

/**
 * Check if a given object implements the MidnightStatus interface.
 */
export function instanceOfMidnightStatus(value: object): value is MidnightStatus {
  if (!('configured' in value) || value['configured'] === undefined) return false
  if (!('enabled' in value) || value['enabled'] === undefined) return false
  if (!('sidecar' in value) || value['sidecar'] === undefined) return false
  return true
}

export function MidnightStatusFromJSON(json: any): MidnightStatus {
  return MidnightStatusFromJSONTyped(json, false)
}

export function MidnightStatusFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): MidnightStatus {
  if (json == null) {
    return json
  }
  return {
    configured: json['configured'],
    enabled: json['enabled'],
    sidecar: SidecarHealthFromJSON(json['sidecar']),
    sidecarUrl: json['sidecarUrl'] == null ? undefined : json['sidecarUrl'],
  }
}

export function MidnightStatusToJSON(json: any): MidnightStatus {
  return MidnightStatusToJSONTyped(json, false)
}

export function MidnightStatusToJSONTyped(
  value?: MidnightStatus | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    configured: value['configured'],
    enabled: value['enabled'],
    sidecar: SidecarHealthToJSON(value['sidecar']),
    sidecarUrl: value['sidecarUrl'],
  }
}
