/* tslint:disable */
/* eslint-disable */
/**
 * OwlID Verification Service
 * SD-JWT VC presentation verification, trusted issuer management, and credential revocation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js'
/**
 *
 * @export
 * @interface MidnightInfoResponse
 */
export interface MidnightInfoResponse {
  /**
   * Network id the sidecar is bound to (`undeployed` for local
   * devnet, `preprod`/`mainnet` elsewhere). The SDK passes this
   * verbatim to `@midnight-ntwrk/midnight-js-network-id`
   * `setNetworkId()` before any contract operation.
   * @type {string}
   * @memberof MidnightInfoResponse
   */
  networkId: string
}

/**
 * Check if a given object implements the MidnightInfoResponse interface.
 */
export function instanceOfMidnightInfoResponse(value: object): value is MidnightInfoResponse {
  if (!('networkId' in value) || value['networkId'] === undefined) return false
  return true
}

export function MidnightInfoResponseFromJSON(json: any): MidnightInfoResponse {
  return MidnightInfoResponseFromJSONTyped(json, false)
}

export function MidnightInfoResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): MidnightInfoResponse {
  if (json == null) {
    return json
  }
  return {
    networkId: json['networkId'],
  }
}

export function MidnightInfoResponseToJSON(json: any): MidnightInfoResponse {
  return MidnightInfoResponseToJSONTyped(json, false)
}

export function MidnightInfoResponseToJSONTyped(
  value?: MidnightInfoResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    networkId: value['networkId'],
  }
}
