/* tslint:disable */
/* eslint-disable */
/**
 * OwlID Verification Service
 * SD-JWT VC presentation verification, trusted issuer management, and credential revocation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js'
/**
 * Holder's nationality is in the verifier's alpha-2 set.
 * @export
 * @interface OwlPredicateOneOf3
 */
export interface OwlPredicateOneOf3 {
  /**
   *
   * @type {Array<string>}
   * @memberof OwlPredicateOneOf3
   */
  countries: Array<string>
  /**
   *
   * @type {string}
   * @memberof OwlPredicateOneOf3
   */
  kind: OwlPredicateOneOf3KindEnum
}

/**
 * @export
 * @enum {string}
 */
export enum OwlPredicateOneOf3KindEnum {
  nationality_in = 'nationality_in',
}

/**
 * Check if a given object implements the OwlPredicateOneOf3 interface.
 */
export function instanceOfOwlPredicateOneOf3(value: object): value is OwlPredicateOneOf3 {
  if (!('countries' in value) || value['countries'] === undefined) return false
  if (!('kind' in value) || value['kind'] === undefined) return false
  return true
}

export function OwlPredicateOneOf3FromJSON(json: any): OwlPredicateOneOf3 {
  return OwlPredicateOneOf3FromJSONTyped(json, false)
}

export function OwlPredicateOneOf3FromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): OwlPredicateOneOf3 {
  if (json == null) {
    return json
  }
  return {
    countries: json['countries'],
    kind: json['kind'],
  }
}

export function OwlPredicateOneOf3ToJSON(json: any): OwlPredicateOneOf3 {
  return OwlPredicateOneOf3ToJSONTyped(json, false)
}

export function OwlPredicateOneOf3ToJSONTyped(
  value?: OwlPredicateOneOf3 | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    countries: value['countries'],
    kind: value['kind'],
  }
}
