/* tslint:disable */
/* eslint-disable */
/**
 * OwlID Verification Service
 * SD-JWT VC presentation verification, trusted issuer management, and credential revocation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js'
/**
 * Issuer's verification level is ≥ `threshold` (1/2/3).
 * @export
 * @interface OwlPredicateOneOf2
 */
export interface OwlPredicateOneOf2 {
  /**
   *
   * @type {string}
   * @memberof OwlPredicateOneOf2
   */
  kind: OwlPredicateOneOf2KindEnum
  /**
   *
   * @type {number}
   * @memberof OwlPredicateOneOf2
   */
  threshold: number
}

/**
 * @export
 * @enum {string}
 */
export enum OwlPredicateOneOf2KindEnum {
  kyc_gte = 'kyc_gte',
}

/**
 * Check if a given object implements the OwlPredicateOneOf2 interface.
 */
export function instanceOfOwlPredicateOneOf2(value: object): value is OwlPredicateOneOf2 {
  if (!('kind' in value) || value['kind'] === undefined) return false
  if (!('threshold' in value) || value['threshold'] === undefined) return false
  return true
}

export function OwlPredicateOneOf2FromJSON(json: any): OwlPredicateOneOf2 {
  return OwlPredicateOneOf2FromJSONTyped(json, false)
}

export function OwlPredicateOneOf2FromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): OwlPredicateOneOf2 {
  if (json == null) {
    return json
  }
  return {
    kind: json['kind'],
    threshold: json['threshold'],
  }
}

export function OwlPredicateOneOf2ToJSON(json: any): OwlPredicateOneOf2 {
  return OwlPredicateOneOf2ToJSONTyped(json, false)
}

export function OwlPredicateOneOf2ToJSONTyped(
  value?: OwlPredicateOneOf2 | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    kind: value['kind'],
    threshold: value['threshold'],
  }
}
