/* tslint:disable */
/* eslint-disable */
/**
 * OwlID Verification Service
 * SD-JWT VC presentation verification, trusted issuer management, and credential revocation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js'
/**
 * Holder's age is ≥ `threshold` years.
 * @export
 * @interface OwlPredicateOneOf
 */
export interface OwlPredicateOneOf {
  /**
   *
   * @type {string}
   * @memberof OwlPredicateOneOf
   */
  kind: OwlPredicateOneOfKindEnum
  /**
   *
   * @type {number}
   * @memberof OwlPredicateOneOf
   */
  threshold: number
}

/**
 * @export
 * @enum {string}
 */
export enum OwlPredicateOneOfKindEnum {
  age_gte = 'age_gte',
}

/**
 * Check if a given object implements the OwlPredicateOneOf interface.
 */
export function instanceOfOwlPredicateOneOf(value: object): value is OwlPredicateOneOf {
  if (!('kind' in value) || value['kind'] === undefined) return false
  if (!('threshold' in value) || value['threshold'] === undefined) return false
  return true
}

export function OwlPredicateOneOfFromJSON(json: any): OwlPredicateOneOf {
  return OwlPredicateOneOfFromJSONTyped(json, false)
}

export function OwlPredicateOneOfFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): OwlPredicateOneOf {
  if (json == null) {
    return json
  }
  return {
    kind: json['kind'],
    threshold: json['threshold'],
  }
}

export function OwlPredicateOneOfToJSON(json: any): OwlPredicateOneOf {
  return OwlPredicateOneOfToJSONTyped(json, false)
}

export function OwlPredicateOneOfToJSONTyped(
  value?: OwlPredicateOneOf | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    kind: value['kind'],
    threshold: value['threshold'],
  }
}
