/* tslint:disable */
/* eslint-disable */
/**
 * OwlID Verification Service
 * SD-JWT VC presentation verification, trusted issuer management, and credential revocation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js'
/**
 * Reactivate a credential
 * @export
 * @interface ReactivateCredentialRequest
 */
export interface ReactivateCredentialRequest {
  /**
   *
   * @type {string}
   * @memberof ReactivateCredentialRequest
   */
  credentialId: string
}

/**
 * Check if a given object implements the ReactivateCredentialRequest interface.
 */
export function instanceOfReactivateCredentialRequest(
  value: object,
): value is ReactivateCredentialRequest {
  if (!('credentialId' in value) || value['credentialId'] === undefined) return false
  return true
}

export function ReactivateCredentialRequestFromJSON(json: any): ReactivateCredentialRequest {
  return ReactivateCredentialRequestFromJSONTyped(json, false)
}

export function ReactivateCredentialRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ReactivateCredentialRequest {
  if (json == null) {
    return json
  }
  return {
    credentialId: json['credentialId'],
  }
}

export function ReactivateCredentialRequestToJSON(json: any): ReactivateCredentialRequest {
  return ReactivateCredentialRequestToJSONTyped(json, false)
}

export function ReactivateCredentialRequestToJSONTyped(
  value?: ReactivateCredentialRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    credentialId: value['credentialId'],
  }
}
