/* tslint:disable */
/* eslint-disable */
/**
 * OwlID Verification Service
 * SD-JWT VC presentation verification, trusted issuer management, and credential revocation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js'
/**
 *
 * @export
 * @interface RelayProofRequest
 */
export interface RelayProofRequest {
  /**
   * Holder-proven `UnboundTransaction`, serialized, hex. The witness
   * is already gone (preimage → ZK proof) before it reaches here.
   * @type {string}
   * @memberof RelayProofRequest
   */
  provenTx: string
}

/**
 * Check if a given object implements the RelayProofRequest interface.
 */
export function instanceOfRelayProofRequest(value: object): value is RelayProofRequest {
  if (!('provenTx' in value) || value['provenTx'] === undefined) return false
  return true
}

export function RelayProofRequestFromJSON(json: any): RelayProofRequest {
  return RelayProofRequestFromJSONTyped(json, false)
}

export function RelayProofRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): RelayProofRequest {
  if (json == null) {
    return json
  }
  return {
    provenTx: json['provenTx'],
  }
}

export function RelayProofRequestToJSON(json: any): RelayProofRequest {
  return RelayProofRequestToJSONTyped(json, false)
}

export function RelayProofRequestToJSONTyped(
  value?: RelayProofRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    provenTx: value['provenTx'],
  }
}
