/* tslint:disable */
/* eslint-disable */
/**
 * OwlID Verification Service
 * SD-JWT VC presentation verification, trusted issuer management, and credential revocation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js'
/**
 *
 * @export
 * @interface RelayProofResponse
 */
export interface RelayProofResponse {
  /**
   * Sidecar-local job id. The chain tx-id is not known at relay
   * time (the SDK assigns it after `submitTx` returns). Holder
   * opens `GET /predicates/job/{jobId}/events` to follow the
   * relay-job lifecycle (queued → balancing → submitting →
   * submitted), at which point the SSE stream switches to chain
   * finalization via the indexer.
   * @type {string}
   * @memberof RelayProofResponse
   */
  jobId: string
  /**
   * Submission status at relay time — `queued` for the standard
   * fire-and-forget path. Terminal statuses arrive over the
   * `/predicates/job/{jobId}/events` SSE stream, not on this
   * response.
   * @type {string}
   * @memberof RelayProofResponse
   */
  status: string
}

/**
 * Check if a given object implements the RelayProofResponse interface.
 */
export function instanceOfRelayProofResponse(value: object): value is RelayProofResponse {
  if (!('jobId' in value) || value['jobId'] === undefined) return false
  if (!('status' in value) || value['status'] === undefined) return false
  return true
}

export function RelayProofResponseFromJSON(json: any): RelayProofResponse {
  return RelayProofResponseFromJSONTyped(json, false)
}

export function RelayProofResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): RelayProofResponse {
  if (json == null) {
    return json
  }
  return {
    jobId: json['jobId'],
    status: json['status'],
  }
}

export function RelayProofResponseToJSON(json: any): RelayProofResponse {
  return RelayProofResponseToJSONTyped(json, false)
}

export function RelayProofResponseToJSONTyped(
  value?: RelayProofResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    jobId: value['jobId'],
    status: value['status'],
  }
}
