/* tslint:disable */
/* eslint-disable */
/**
 * OwlID Verification Service
 * Token verification, trusted issuer management, and credential revocation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js'
/**
 * Request to revoke a credential
 * @export
 * @interface RevokeCredentialRequest
 */
export interface RevokeCredentialRequest {
  /**
   *
   * @type {string}
   * @memberof RevokeCredentialRequest
   */
  credentialId: string
  /**
   *
   * @type {string}
   * @memberof RevokeCredentialRequest
   */
  issuerPublicKey: string
  /**
   *
   * @type {string}
   * @memberof RevokeCredentialRequest
   */
  reason?: string | null
}

/**
 * Check if a given object implements the RevokeCredentialRequest interface.
 */
export function instanceOfRevokeCredentialRequest(value: object): value is RevokeCredentialRequest {
  if (!('credentialId' in value) || value['credentialId'] === undefined) return false
  if (!('issuerPublicKey' in value) || value['issuerPublicKey'] === undefined) return false
  return true
}

export function RevokeCredentialRequestFromJSON(json: any): RevokeCredentialRequest {
  return RevokeCredentialRequestFromJSONTyped(json, false)
}

export function RevokeCredentialRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): RevokeCredentialRequest {
  if (json == null) {
    return json
  }
  return {
    credentialId: json['credentialId'],
    issuerPublicKey: json['issuerPublicKey'],
    reason: json['reason'] == null ? undefined : json['reason'],
  }
}

export function RevokeCredentialRequestToJSON(json: any): RevokeCredentialRequest {
  return RevokeCredentialRequestToJSONTyped(json, false)
}

export function RevokeCredentialRequestToJSONTyped(
  value?: RevokeCredentialRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    credentialId: value['credentialId'],
    issuerPublicKey: value['issuerPublicKey'],
    reason: value['reason'],
  }
}
