/* tslint:disable */
/* eslint-disable */
/**
 * OwlID Verification Service
 * SD-JWT VC presentation verification, trusted issuer management, and credential revocation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js'
/**
 *
 * @export
 * @interface RevokeOwnCredentialResponse
 */
export interface RevokeOwnCredentialResponse {
  /**
   * True when the credential was already revoked (idempotent no-op).
   * @type {boolean}
   * @memberof RevokeOwnCredentialResponse
   */
  alreadyRevoked: boolean
  /**
   *
   * @type {string}
   * @memberof RevokeOwnCredentialResponse
   */
  credentialId: string
  /**
   *
   * @type {boolean}
   * @memberof RevokeOwnCredentialResponse
   */
  revoked: boolean
}

/**
 * Check if a given object implements the RevokeOwnCredentialResponse interface.
 */
export function instanceOfRevokeOwnCredentialResponse(
  value: object,
): value is RevokeOwnCredentialResponse {
  if (!('alreadyRevoked' in value) || value['alreadyRevoked'] === undefined) return false
  if (!('credentialId' in value) || value['credentialId'] === undefined) return false
  if (!('revoked' in value) || value['revoked'] === undefined) return false
  return true
}

export function RevokeOwnCredentialResponseFromJSON(json: any): RevokeOwnCredentialResponse {
  return RevokeOwnCredentialResponseFromJSONTyped(json, false)
}

export function RevokeOwnCredentialResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): RevokeOwnCredentialResponse {
  if (json == null) {
    return json
  }
  return {
    alreadyRevoked: json['alreadyRevoked'],
    credentialId: json['credentialId'],
    revoked: json['revoked'],
  }
}

export function RevokeOwnCredentialResponseToJSON(json: any): RevokeOwnCredentialResponse {
  return RevokeOwnCredentialResponseToJSONTyped(json, false)
}

export function RevokeOwnCredentialResponseToJSONTyped(
  value?: RevokeOwnCredentialResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    alreadyRevoked: value['alreadyRevoked'],
    credentialId: value['credentialId'],
    revoked: value['revoked'],
  }
}
