/* tslint:disable */
/* eslint-disable */
/**
 * OwlID Verification Service
 * SD-JWT VC presentation verification, trusted issuer management, and credential revocation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js'
/**
 * One row of the revocation registry as exposed to admin clients.
 * @export
 * @interface RevocationEntry
 */
export interface RevocationEntry {
  /**
   *
   * @type {string}
   * @memberof RevocationEntry
   */
  credentialId: string
  /**
   *
   * @type {string}
   * @memberof RevocationEntry
   */
  reason?: string | null
  /**
   * RFC 3339 timestamp; `None` for credentials that were suspended but
   * never permanently revoked (kept for symmetry with the row shape).
   * @type {Date}
   * @memberof RevocationEntry
   */
  revokedAt?: Date | null
  /**
   *
   * @type {string}
   * @memberof RevocationEntry
   */
  status: string
}

/**
 * Check if a given object implements the RevocationEntry interface.
 */
export function instanceOfRevocationEntry(value: object): value is RevocationEntry {
  if (!('credentialId' in value) || value['credentialId'] === undefined) return false
  if (!('status' in value) || value['status'] === undefined) return false
  return true
}

export function RevocationEntryFromJSON(json: any): RevocationEntry {
  return RevocationEntryFromJSONTyped(json, false)
}

export function RevocationEntryFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): RevocationEntry {
  if (json == null) {
    return json
  }
  return {
    credentialId: json['credentialId'],
    reason: json['reason'] == null ? undefined : json['reason'],
    revokedAt: json['revokedAt'] == null ? undefined : new Date(json['revokedAt']),
    status: json['status'],
  }
}

export function RevocationEntryToJSON(json: any): RevocationEntry {
  return RevocationEntryToJSONTyped(json, false)
}

export function RevocationEntryToJSONTyped(
  value?: RevocationEntry | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    credentialId: value['credentialId'],
    reason: value['reason'],
    revokedAt: value['revokedAt'] == null ? undefined : (value['revokedAt'] as any).toISOString(),
    status: value['status'],
  }
}
