/* tslint:disable */
/* eslint-disable */
/**
 * OwlID Verification Service
 * SD-JWT VC presentation verification, trusted issuer management, and credential revocation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js'
import type { VerifyResponse } from './VerifyResponse.js'
import {
  VerifyResponseFromJSON,
  VerifyResponseFromJSONTyped,
  VerifyResponseToJSON,
  VerifyResponseToJSONTyped,
} from './VerifyResponse.js'

/**
 * DCQL verification response.
 * @export
 * @interface VerifyDcqlResponse
 */
export interface VerifyDcqlResponse {
  /**
   *
   * @type {string}
   * @memberof VerifyDcqlResponse
   */
  error?: string | null
  /**
   * Per-credential verdict, keyed by DCQL credential id.
   * @type {{ [key: string]: VerifyResponse; }}
   * @memberof VerifyDcqlResponse
   */
  perCredential: { [key: string]: VerifyResponse }
  /**
   *
   * @type {any}
   * @memberof VerifyDcqlResponse
   */
  subjects: any | null
  /**
   * `true` iff every claimed `vp_token` entry verified AND the DCQL
   * query's `credential_sets` are satisfied.
   * @type {boolean}
   * @memberof VerifyDcqlResponse
   */
  valid: boolean
}

/**
 * Check if a given object implements the VerifyDcqlResponse interface.
 */
export function instanceOfVerifyDcqlResponse(value: object): value is VerifyDcqlResponse {
  if (!('perCredential' in value) || value['perCredential'] === undefined) return false
  if (!('subjects' in value) || value['subjects'] === undefined) return false
  if (!('valid' in value) || value['valid'] === undefined) return false
  return true
}

export function VerifyDcqlResponseFromJSON(json: any): VerifyDcqlResponse {
  return VerifyDcqlResponseFromJSONTyped(json, false)
}

export function VerifyDcqlResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): VerifyDcqlResponse {
  if (json == null) {
    return json
  }
  return {
    error: json['error'] == null ? undefined : json['error'],
    perCredential: mapValues(json['perCredential'], VerifyResponseFromJSON),
    subjects: json['subjects'],
    valid: json['valid'],
  }
}

export function VerifyDcqlResponseToJSON(json: any): VerifyDcqlResponse {
  return VerifyDcqlResponseToJSONTyped(json, false)
}

export function VerifyDcqlResponseToJSONTyped(
  value?: VerifyDcqlResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    error: value['error'],
    perCredential: mapValues(value['perCredential'], VerifyResponseToJSON),
    subjects: value['subjects'],
    valid: value['valid'],
  }
}
