/* tslint:disable */
/* eslint-disable */
/**
 * OwlID Verification Service
 * Token verification, trusted issuer management, and credential revocation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime.js'
import type { TrustedIssuerInfo } from '../models/index.js'
import { TrustedIssuerInfoFromJSON, TrustedIssuerInfoToJSON } from '../models/index.js'

/**
 * IssuersApi - interface
 *
 * @export
 * @interface IssuersApiInterface
 */
export interface IssuersApiInterface {
  /**
   *
   * @summary List trusted issuers
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof IssuersApiInterface
   */
  listTrustedIssuersRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<TrustedIssuerInfo>>>

  /**
   * List trusted issuers
   */
  listTrustedIssuers(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<TrustedIssuerInfo>>
}

/**
 *
 */
export class IssuersApi extends runtime.BaseAPI implements IssuersApiInterface {
  /**
   * List trusted issuers
   */
  async listTrustedIssuersRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<TrustedIssuerInfo>>> {
    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    const response = await this.request(
      {
        path: `/trusted-issuers`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(TrustedIssuerInfoFromJSON),
    )
  }

  /**
   * List trusted issuers
   */
  async listTrustedIssuers(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<TrustedIssuerInfo>> {
    const response = await this.listTrustedIssuersRaw(initOverrides)
    return await response.value()
  }
}
