/* tslint:disable */
/* eslint-disable */
/**
 * OwlID Verification Service
 * Token verification, trusted issuer management, and credential revocation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime.js'

/**
 * MonitoringApi - interface
 *
 * @export
 * @interface MonitoringApiInterface
 */
export interface MonitoringApiInterface {
  /**
   *
   * @summary Health check endpoint
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof MonitoringApiInterface
   */
  healthRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<string>>

  /**
   * Health check endpoint
   */
  health(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string>
}

/**
 *
 */
export class MonitoringApi extends runtime.BaseAPI implements MonitoringApiInterface {
  /**
   * Health check endpoint
   */
  async healthRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<string>> {
    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    const response = await this.request(
      {
        path: `/health`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    if (this.isJsonMime(response.headers.get('content-type'))) {
      return new runtime.JSONApiResponse<string>(response)
    } else {
      return new runtime.TextApiResponse(response) as any
    }
  }

  /**
   * Health check endpoint
   */
  async health(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
    const response = await this.healthRaw(initOverrides)
    return await response.value()
  }
}
