/* tslint:disable */
/* eslint-disable */
/**
 * OwlID Verification Service
 * SD-JWT VC presentation verification, trusted issuer management, and credential revocation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime.js'
import type {
  CheckPredicateRequest,
  CheckPredicateResponse,
  PredicateSnapshotResponse,
  RelayProofRequest,
  RelayProofResponse,
} from '../models/index.js'
import {
  CheckPredicateRequestFromJSON,
  CheckPredicateRequestToJSON,
  CheckPredicateResponseFromJSON,
  CheckPredicateResponseToJSON,
  PredicateSnapshotResponseFromJSON,
  PredicateSnapshotResponseToJSON,
  RelayProofRequestFromJSON,
  RelayProofRequestToJSON,
  RelayProofResponseFromJSON,
  RelayProofResponseToJSON,
} from '../models/index.js'

export interface CheckPredicateAttestedRequest {
  checkPredicateRequest: CheckPredicateRequest
}

export interface GetPredicateSnapshotRequest {
  kind: string
}

export interface RelayPredicateProofRequest {
  kind: string
  relayProofRequest: RelayProofRequest
}

export interface StreamPredicateTxEventsRequest {
  txId: string
}

/**
 * PredicatesApi - interface
 *
 * @export
 * @interface PredicatesApiInterface
 */
export interface PredicatesApiInterface {
  /**
   *
   * @summary Recompute the Midnight attestation key from the credential\'s issuer-signed credential_id + requested predicate (binding it to *this* credential), then check membership in the SSE-mirrored set. No ZK proof verified inline — the Midnight node already verified it in consensus when the attest tx was processed.
   * @param {CheckPredicateRequest} checkPredicateRequest
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof PredicatesApiInterface
   */
  checkPredicateAttestedRaw(
    requestParameters: CheckPredicateAttestedRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<CheckPredicateResponse>>

  /**
   * Recompute the Midnight attestation key from the credential\'s issuer-signed credential_id + requested predicate (binding it to *this* credential), then check membership in the SSE-mirrored set. No ZK proof verified inline — the Midnight node already verified it in consensus when the attest tx was processed.
   */
  checkPredicateAttested(
    requestParameters: CheckPredicateAttestedRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<CheckPredicateResponse>

  /**
   *
   * @summary Read-only chain-state snapshot the holder device feeds to a snapshot-backed provider for offline predicate circuit-exec. The holder never queries the chain — this is the only state it gets. One Compact contract per predicate kind; the `kind` path segment selects which (`age|kyc|residency|email|nationality|age_range| personhood`).
   * @param {string} kind Predicate kind segment (age|kyc|residency|email|nationality|age_range|personhood)
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof PredicatesApiInterface
   */
  getPredicateSnapshotRaw(
    requestParameters: GetPredicateSnapshotRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<PredicateSnapshotResponse>>

  /**
   * Read-only chain-state snapshot the holder device feeds to a snapshot-backed provider for offline predicate circuit-exec. The holder never queries the chain — this is the only state it gets. One Compact contract per predicate kind; the `kind` path segment selects which (`age|kyc|residency|email|nationality|age_range| personhood`).
   */
  getPredicateSnapshot(
    requestParameters: GetPredicateSnapshotRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<PredicateSnapshotResponse>

  /**
   *
   * @summary Balance + submit a holder-proven predicate attestation against the per-kind Compact contract. The Midnight node verifies the proof in consensus and records the attestation; the existing SSE mirror surfaces it to verifiers. The holder never touches the chain — this endpoint is the only submit path.
   * @param {string} kind Predicate kind segment (age|kyc|residency|email|nationality|age_range|personhood)
   * @param {RelayProofRequest} relayProofRequest
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof PredicatesApiInterface
   */
  relayPredicateProofRaw(
    requestParameters: RelayPredicateProofRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<RelayProofResponse>>

  /**
   * Balance + submit a holder-proven predicate attestation against the per-kind Compact contract. The Midnight node verifies the proof in consensus and records the attestation; the existing SSE mirror surfaces it to verifiers. The holder never touches the chain — this endpoint is the only submit path.
   */
  relayPredicateProof(
    requestParameters: RelayPredicateProofRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<RelayProofResponse>

  /**
   *
   * @summary SSE stream of phase transitions for a relay job (or raw chain tx). Forwards the sidecar\'s upstream `GET /api/predicates/tx/{id}/events` byte-for-byte to the holder so the in-process eventBus pushes reach the browser as `text/event-stream` events. The whole system uses exactly two notification transports end-to-end: WS for two-way channels (presentation sockets) and SSE for server→client pushes. No polling, no long-polling, no rapid-fire HTTP.
   * @param {string} txId Midnight tx id or relay job id (returned by /predicates/{kind}/relay)
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof PredicatesApiInterface
   */
  streamPredicateTxEventsRaw(
    requestParameters: StreamPredicateTxEventsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>>

  /**
   * SSE stream of phase transitions for a relay job (or raw chain tx). Forwards the sidecar\'s upstream `GET /api/predicates/tx/{id}/events` byte-for-byte to the holder so the in-process eventBus pushes reach the browser as `text/event-stream` events. The whole system uses exactly two notification transports end-to-end: WS for two-way channels (presentation sockets) and SSE for server→client pushes. No polling, no long-polling, no rapid-fire HTTP.
   */
  streamPredicateTxEvents(
    requestParameters: StreamPredicateTxEventsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void>
}

/**
 *
 */
export class PredicatesApi extends runtime.BaseAPI implements PredicatesApiInterface {
  /**
   * Recompute the Midnight attestation key from the credential\'s issuer-signed credential_id + requested predicate (binding it to *this* credential), then check membership in the SSE-mirrored set. No ZK proof verified inline — the Midnight node already verified it in consensus when the attest tx was processed.
   */
  async checkPredicateAttestedRaw(
    requestParameters: CheckPredicateAttestedRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<CheckPredicateResponse>> {
    if (requestParameters['checkPredicateRequest'] == null) {
      throw new runtime.RequiredError(
        'checkPredicateRequest',
        'Required parameter "checkPredicateRequest" was null or undefined when calling checkPredicateAttested().',
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters['Content-Type'] = 'application/json'

    const response = await this.request(
      {
        path: `/predicates/attested`,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: CheckPredicateRequestToJSON(requestParameters['checkPredicateRequest']),
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      CheckPredicateResponseFromJSON(jsonValue),
    )
  }

  /**
   * Recompute the Midnight attestation key from the credential\'s issuer-signed credential_id + requested predicate (binding it to *this* credential), then check membership in the SSE-mirrored set. No ZK proof verified inline — the Midnight node already verified it in consensus when the attest tx was processed.
   */
  async checkPredicateAttested(
    requestParameters: CheckPredicateAttestedRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<CheckPredicateResponse> {
    const response = await this.checkPredicateAttestedRaw(requestParameters, initOverrides)
    return await response.value()
  }

  /**
   * Read-only chain-state snapshot the holder device feeds to a snapshot-backed provider for offline predicate circuit-exec. The holder never queries the chain — this is the only state it gets. One Compact contract per predicate kind; the `kind` path segment selects which (`age|kyc|residency|email|nationality|age_range| personhood`).
   */
  async getPredicateSnapshotRaw(
    requestParameters: GetPredicateSnapshotRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<PredicateSnapshotResponse>> {
    if (requestParameters['kind'] == null) {
      throw new runtime.RequiredError(
        'kind',
        'Required parameter "kind" was null or undefined when calling getPredicateSnapshot().',
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    const response = await this.request(
      {
        path: `/predicates/{kind}/snapshot`.replace(
          `{${'kind'}}`,
          encodeURIComponent(String(requestParameters['kind'])),
        ),
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      PredicateSnapshotResponseFromJSON(jsonValue),
    )
  }

  /**
   * Read-only chain-state snapshot the holder device feeds to a snapshot-backed provider for offline predicate circuit-exec. The holder never queries the chain — this is the only state it gets. One Compact contract per predicate kind; the `kind` path segment selects which (`age|kyc|residency|email|nationality|age_range| personhood`).
   */
  async getPredicateSnapshot(
    requestParameters: GetPredicateSnapshotRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<PredicateSnapshotResponse> {
    const response = await this.getPredicateSnapshotRaw(requestParameters, initOverrides)
    return await response.value()
  }

  /**
   * Balance + submit a holder-proven predicate attestation against the per-kind Compact contract. The Midnight node verifies the proof in consensus and records the attestation; the existing SSE mirror surfaces it to verifiers. The holder never touches the chain — this endpoint is the only submit path.
   */
  async relayPredicateProofRaw(
    requestParameters: RelayPredicateProofRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<RelayProofResponse>> {
    if (requestParameters['kind'] == null) {
      throw new runtime.RequiredError(
        'kind',
        'Required parameter "kind" was null or undefined when calling relayPredicateProof().',
      )
    }

    if (requestParameters['relayProofRequest'] == null) {
      throw new runtime.RequiredError(
        'relayProofRequest',
        'Required parameter "relayProofRequest" was null or undefined when calling relayPredicateProof().',
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters['Content-Type'] = 'application/json'

    const response = await this.request(
      {
        path: `/predicates/{kind}/relay`.replace(
          `{${'kind'}}`,
          encodeURIComponent(String(requestParameters['kind'])),
        ),
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: RelayProofRequestToJSON(requestParameters['relayProofRequest']),
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      RelayProofResponseFromJSON(jsonValue),
    )
  }

  /**
   * Balance + submit a holder-proven predicate attestation against the per-kind Compact contract. The Midnight node verifies the proof in consensus and records the attestation; the existing SSE mirror surfaces it to verifiers. The holder never touches the chain — this endpoint is the only submit path.
   */
  async relayPredicateProof(
    requestParameters: RelayPredicateProofRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<RelayProofResponse> {
    const response = await this.relayPredicateProofRaw(requestParameters, initOverrides)
    return await response.value()
  }

  /**
   * SSE stream of phase transitions for a relay job (or raw chain tx). Forwards the sidecar\'s upstream `GET /api/predicates/tx/{id}/events` byte-for-byte to the holder so the in-process eventBus pushes reach the browser as `text/event-stream` events. The whole system uses exactly two notification transports end-to-end: WS for two-way channels (presentation sockets) and SSE for server→client pushes. No polling, no long-polling, no rapid-fire HTTP.
   */
  async streamPredicateTxEventsRaw(
    requestParameters: StreamPredicateTxEventsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters['txId'] == null) {
      throw new runtime.RequiredError(
        'txId',
        'Required parameter "txId" was null or undefined when calling streamPredicateTxEvents().',
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    const response = await this.request(
      {
        path: `/predicates/tx/{tx_id}/events`.replace(
          `{${'tx_id'}}`,
          encodeURIComponent(String(requestParameters['txId'])),
        ),
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.VoidApiResponse(response)
  }

  /**
   * SSE stream of phase transitions for a relay job (or raw chain tx). Forwards the sidecar\'s upstream `GET /api/predicates/tx/{id}/events` byte-for-byte to the holder so the in-process eventBus pushes reach the browser as `text/event-stream` events. The whole system uses exactly two notification transports end-to-end: WS for two-way channels (presentation sockets) and SSE for server→client pushes. No polling, no long-polling, no rapid-fire HTTP.
   */
  async streamPredicateTxEvents(
    requestParameters: StreamPredicateTxEventsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.streamPredicateTxEventsRaw(requestParameters, initOverrides)
  }
}
