/* tslint:disable */
/* eslint-disable */
/**
 * OwlID Verification Service
 * SD-JWT VC presentation verification, trusted issuer management, and credential revocation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime.js'
import type { CreatePresentationRequest, CreatePresentationResponse } from '../models/index.js'
import {
  CreatePresentationRequestFromJSON,
  CreatePresentationRequestToJSON,
  CreatePresentationResponseFromJSON,
  CreatePresentationResponseToJSON,
} from '../models/index.js'

export interface CreateSessionRequest {
  createPresentationRequest: CreatePresentationRequest
}

/**
 * PresentationApi - interface
 *
 * @export
 * @interface PresentationApiInterface
 */
export interface PresentationApiInterface {
  /**
   *
   * @param {CreatePresentationRequest} createPresentationRequest
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof PresentationApiInterface
   */
  createSessionRaw(
    requestParameters: CreateSessionRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<CreatePresentationResponse>>

  /**
   */
  createSession(
    requestParameters: CreateSessionRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<CreatePresentationResponse>
}

/**
 *
 */
export class PresentationApi extends runtime.BaseAPI implements PresentationApiInterface {
  /**
   */
  async createSessionRaw(
    requestParameters: CreateSessionRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<CreatePresentationResponse>> {
    if (requestParameters['createPresentationRequest'] == null) {
      throw new runtime.RequiredError(
        'createPresentationRequest',
        'Required parameter "createPresentationRequest" was null or undefined when calling createSession().',
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters['Content-Type'] = 'application/json'

    const response = await this.request(
      {
        path: `/presentation/sessions`,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: CreatePresentationRequestToJSON(requestParameters['createPresentationRequest']),
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      CreatePresentationResponseFromJSON(jsonValue),
    )
  }

  /**
   */
  async createSession(
    requestParameters: CreateSessionRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<CreatePresentationResponse> {
    const response = await this.createSessionRaw(requestParameters, initOverrides)
    return await response.value()
  }
}
