/* tslint:disable */
/* eslint-disable */
/**
 * OwlID Verification Service
 * SD-JWT VC presentation verification, trusted issuer management, and credential revocation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime.js'
import type { CircuitDataset, CircuitDatasetInfo, PredicateInfo } from '../models/index.js'
import {
  CircuitDatasetFromJSON,
  CircuitDatasetToJSON,
  CircuitDatasetInfoFromJSON,
  CircuitDatasetInfoToJSON,
  PredicateInfoFromJSON,
  PredicateInfoToJSON,
} from '../models/index.js'

export interface GetCircuitDatasetRequest {
  name: string
}

export interface GetPredicateAssetRequest {
  filename: string
}

export interface GetProvingKeyRequest {
  filename: string
}

/**
 * RegistryApi - interface
 *
 * @export
 * @interface RegistryApiInterface
 */
export interface RegistryApiInterface {
  /**
   *
   * @summary Return a single dataset\'s full leaf list. Public.
   * @param {string} name Dataset name
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof RegistryApiInterface
   */
  getCircuitDatasetRaw(
    requestParameters: GetCircuitDatasetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<CircuitDataset>>

  /**
   * Return a single dataset\'s full leaf list. Public.
   */
  getCircuitDataset(
    requestParameters: GetCircuitDatasetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<CircuitDataset>

  /**
   *
   * @summary Serve a raw per-kind predicate Compact artifact (zkir / prover / verifier). Public — Compact ZK material is public; integrity, not secrecy, is what matters. Immutable-cached: a contract change ships a new artifact set behind a new build. Mirrors [`get_proving_key`].
   * @param {string} filename &lt;circuit&gt;.{bzkir|prover|verifier}
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof RegistryApiInterface
   */
  getPredicateAssetRaw(
    requestParameters: GetPredicateAssetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>>

  /**
   * Serve a raw per-kind predicate Compact artifact (zkir / prover / verifier). Public — Compact ZK material is public; integrity, not secrecy, is what matters. Immutable-cached: a contract change ships a new artifact set behind a new build. Mirrors [`get_proving_key`].
   */
  getPredicateAsset(
    requestParameters: GetPredicateAssetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void>

  /**
   * Path is `/zk-keys/{circuit}.pk.bin`. Cached aggressively (immutable): when the circuit changes, the key changes and a new artifact is shipped behind a new build hash; clients pick that up on next deploy.
   * @summary Serve the raw Groth16 proving key for a given circuit. Public — the keys are public cryptographic material; integrity is what matters, not secrecy.
   * @param {string} filename &lt;circuit&gt;.pk.bin
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof RegistryApiInterface
   */
  getProvingKeyRaw(
    requestParameters: GetProvingKeyRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>>

  /**
   * Path is `/zk-keys/{circuit}.pk.bin`. Cached aggressively (immutable): when the circuit changes, the key changes and a new artifact is shipped behind a new build hash; clients pick that up on next deploy.
   * Serve the raw Groth16 proving key for a given circuit. Public — the keys are public cryptographic material; integrity is what matters, not secrecy.
   */
  getProvingKey(
    requestParameters: GetProvingKeyRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void>

  /**
   *
   * @summary Summarise every registered set-membership dataset (name + version only).
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof RegistryApiInterface
   */
  listCircuitDataRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<CircuitDatasetInfo>>>

  /**
   * Summarise every registered set-membership dataset (name + version only).
   */
  listCircuitData(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<CircuitDatasetInfo>>

  /**
   *
   * @summary Filenames of every per-kind predicate Compact artifact served by `/predicate-zk/{filename}`. Same role as `/zk-keys` for Groth16: the holder\'s WASM build leaves the multi-MB keys out and prefetches this list. `<circuit>.<kind>`, `kind ∈ {bzkir, prover, verifier}`. One Compact contract per predicate kind (devnet block-weight cap) — the circuit names cover every deployed kind in one bucket.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof RegistryApiInterface
   */
  listPredicateAssetsRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<string>>>

  /**
   * Filenames of every per-kind predicate Compact artifact served by `/predicate-zk/{filename}`. Same role as `/zk-keys` for Groth16: the holder\'s WASM build leaves the multi-MB keys out and prefetches this list. `<circuit>.<kind>`, `kind ∈ {bzkir, prover, verifier}`. One Compact contract per predicate kind (devnet block-weight cap) — the circuit names cover every deployed kind in one bucket.
   */
  listPredicateAssets(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<string>>

  /**
   *
   * @summary List every predicate the system can prove. Public, no auth required.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof RegistryApiInterface
   */
  listPredicatesRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<PredicateInfo>>>

  /**
   * List every predicate the system can prove. Public, no auth required.
   */
  listPredicates(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<PredicateInfo>>

  /**
   *
   * @summary Names of every Groth16 circuit served by `/zk-keys/{circuit}.pk.bin`. Wallets call this once to drive their prefetch list and avoid hard-coding circuit identifiers that change with the artifact set.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof RegistryApiInterface
   */
  listProvingKeysRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<string>>>

  /**
   * Names of every Groth16 circuit served by `/zk-keys/{circuit}.pk.bin`. Wallets call this once to drive their prefetch list and avoid hard-coding circuit identifiers that change with the artifact set.
   */
  listProvingKeys(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<string>>
}

/**
 *
 */
export class RegistryApi extends runtime.BaseAPI implements RegistryApiInterface {
  /**
   * Return a single dataset\'s full leaf list. Public.
   */
  async getCircuitDatasetRaw(
    requestParameters: GetCircuitDatasetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<CircuitDataset>> {
    if (requestParameters['name'] == null) {
      throw new runtime.RequiredError(
        'name',
        'Required parameter "name" was null or undefined when calling getCircuitDataset().',
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    const response = await this.request(
      {
        path: `/circuit-data/{name}`.replace(
          `{${'name'}}`,
          encodeURIComponent(String(requestParameters['name'])),
        ),
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) => CircuitDatasetFromJSON(jsonValue))
  }

  /**
   * Return a single dataset\'s full leaf list. Public.
   */
  async getCircuitDataset(
    requestParameters: GetCircuitDatasetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<CircuitDataset> {
    const response = await this.getCircuitDatasetRaw(requestParameters, initOverrides)
    return await response.value()
  }

  /**
   * Serve a raw per-kind predicate Compact artifact (zkir / prover / verifier). Public — Compact ZK material is public; integrity, not secrecy, is what matters. Immutable-cached: a contract change ships a new artifact set behind a new build. Mirrors [`get_proving_key`].
   */
  async getPredicateAssetRaw(
    requestParameters: GetPredicateAssetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters['filename'] == null) {
      throw new runtime.RequiredError(
        'filename',
        'Required parameter "filename" was null or undefined when calling getPredicateAsset().',
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    const response = await this.request(
      {
        path: `/predicate-zk/{filename}`.replace(
          `{${'filename'}}`,
          encodeURIComponent(String(requestParameters['filename'])),
        ),
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.VoidApiResponse(response)
  }

  /**
   * Serve a raw per-kind predicate Compact artifact (zkir / prover / verifier). Public — Compact ZK material is public; integrity, not secrecy, is what matters. Immutable-cached: a contract change ships a new artifact set behind a new build. Mirrors [`get_proving_key`].
   */
  async getPredicateAsset(
    requestParameters: GetPredicateAssetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.getPredicateAssetRaw(requestParameters, initOverrides)
  }

  /**
   * Path is `/zk-keys/{circuit}.pk.bin`. Cached aggressively (immutable): when the circuit changes, the key changes and a new artifact is shipped behind a new build hash; clients pick that up on next deploy.
   * Serve the raw Groth16 proving key for a given circuit. Public — the keys are public cryptographic material; integrity is what matters, not secrecy.
   */
  async getProvingKeyRaw(
    requestParameters: GetProvingKeyRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters['filename'] == null) {
      throw new runtime.RequiredError(
        'filename',
        'Required parameter "filename" was null or undefined when calling getProvingKey().',
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    const response = await this.request(
      {
        path: `/zk-keys/{filename}`.replace(
          `{${'filename'}}`,
          encodeURIComponent(String(requestParameters['filename'])),
        ),
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.VoidApiResponse(response)
  }

  /**
   * Path is `/zk-keys/{circuit}.pk.bin`. Cached aggressively (immutable): when the circuit changes, the key changes and a new artifact is shipped behind a new build hash; clients pick that up on next deploy.
   * Serve the raw Groth16 proving key for a given circuit. Public — the keys are public cryptographic material; integrity is what matters, not secrecy.
   */
  async getProvingKey(
    requestParameters: GetProvingKeyRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.getProvingKeyRaw(requestParameters, initOverrides)
  }

  /**
   * Summarise every registered set-membership dataset (name + version only).
   */
  async listCircuitDataRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<CircuitDatasetInfo>>> {
    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    const response = await this.request(
      {
        path: `/circuit-data`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(CircuitDatasetInfoFromJSON),
    )
  }

  /**
   * Summarise every registered set-membership dataset (name + version only).
   */
  async listCircuitData(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<CircuitDatasetInfo>> {
    const response = await this.listCircuitDataRaw(initOverrides)
    return await response.value()
  }

  /**
   * Filenames of every per-kind predicate Compact artifact served by `/predicate-zk/{filename}`. Same role as `/zk-keys` for Groth16: the holder\'s WASM build leaves the multi-MB keys out and prefetches this list. `<circuit>.<kind>`, `kind ∈ {bzkir, prover, verifier}`. One Compact contract per predicate kind (devnet block-weight cap) — the circuit names cover every deployed kind in one bucket.
   */
  async listPredicateAssetsRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<string>>> {
    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    const response = await this.request(
      {
        path: `/predicate-zk`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse<any>(response)
  }

  /**
   * Filenames of every per-kind predicate Compact artifact served by `/predicate-zk/{filename}`. Same role as `/zk-keys` for Groth16: the holder\'s WASM build leaves the multi-MB keys out and prefetches this list. `<circuit>.<kind>`, `kind ∈ {bzkir, prover, verifier}`. One Compact contract per predicate kind (devnet block-weight cap) — the circuit names cover every deployed kind in one bucket.
   */
  async listPredicateAssets(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<string>> {
    const response = await this.listPredicateAssetsRaw(initOverrides)
    return await response.value()
  }

  /**
   * List every predicate the system can prove. Public, no auth required.
   */
  async listPredicatesRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<PredicateInfo>>> {
    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    const response = await this.request(
      {
        path: `/predicates`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(PredicateInfoFromJSON),
    )
  }

  /**
   * List every predicate the system can prove. Public, no auth required.
   */
  async listPredicates(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<PredicateInfo>> {
    const response = await this.listPredicatesRaw(initOverrides)
    return await response.value()
  }

  /**
   * Names of every Groth16 circuit served by `/zk-keys/{circuit}.pk.bin`. Wallets call this once to drive their prefetch list and avoid hard-coding circuit identifiers that change with the artifact set.
   */
  async listProvingKeysRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<string>>> {
    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    const response = await this.request(
      {
        path: `/zk-keys`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse<any>(response)
  }

  /**
   * Names of every Groth16 circuit served by `/zk-keys/{circuit}.pk.bin`. Wallets call this once to drive their prefetch list and avoid hard-coding circuit identifiers that change with the artifact set.
   */
  async listProvingKeys(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<string>> {
    const response = await this.listProvingKeysRaw(initOverrides)
    return await response.value()
  }
}
