/* tslint:disable */
/* eslint-disable */
/**
 * OwlID Verification Service
 * SD-JWT VC presentation verification, trusted issuer management, and credential revocation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime.js'
import type {
  CheckRevocationRequest,
  CheckRevocationResponse,
  RevocationEntry,
  RevokeOwnCredentialRequest,
  RevokeOwnCredentialResponse,
} from '../models/index.js'
import {
  CheckRevocationRequestFromJSON,
  CheckRevocationRequestToJSON,
  CheckRevocationResponseFromJSON,
  CheckRevocationResponseToJSON,
  RevocationEntryFromJSON,
  RevocationEntryToJSON,
  RevokeOwnCredentialRequestFromJSON,
  RevokeOwnCredentialRequestToJSON,
  RevokeOwnCredentialResponseFromJSON,
  RevokeOwnCredentialResponseToJSON,
} from '../models/index.js'

export interface CheckRevocationOperationRequest {
  checkRevocationRequest: CheckRevocationRequest
}

export interface RevokeOwnCredentialOperationRequest {
  revokeOwnCredentialRequest: RevokeOwnCredentialRequest
}

/**
 * RevocationsApi - interface
 *
 * @export
 * @interface RevocationsApiInterface
 */
export interface RevocationsApiInterface {
  /**
   *
   * @param {CheckRevocationRequest} checkRevocationRequest
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof RevocationsApiInterface
   */
  checkRevocationRaw(
    requestParameters: CheckRevocationOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<CheckRevocationResponse>>

  /**
   */
  checkRevocation(
    requestParameters: CheckRevocationOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<CheckRevocationResponse>

  /**
   *
   * @summary List revoked credentials
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof RevocationsApiInterface
   */
  listRevokedRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<RevocationEntry>>>

  /**
   * List revoked credentials
   */
  listRevoked(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<RevocationEntry>>

  /**
   * Unlike `/revocations/revoke` (admin), this needs no admin key. The holder presents the credential with a KB-JWT signed by the `cnf` holder key, bound to a fresh server challenge + the self-revoke audience. We verify the issuer signature (which binds `cnf` ↔ `credential_id`) and the KB-JWT (proof of possession), then revoke that single credential on-chain with the ISSUER key. A holder can therefore only ever revoke a credential they can prove they hold — never someone else\'s.
   * @summary Revoke your OWN credential by proving possession of its holder key.
   * @param {RevokeOwnCredentialRequest} revokeOwnCredentialRequest
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof RevocationsApiInterface
   */
  revokeOwnCredentialRaw(
    requestParameters: RevokeOwnCredentialOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<RevokeOwnCredentialResponse>>

  /**
   * Unlike `/revocations/revoke` (admin), this needs no admin key. The holder presents the credential with a KB-JWT signed by the `cnf` holder key, bound to a fresh server challenge + the self-revoke audience. We verify the issuer signature (which binds `cnf` ↔ `credential_id`) and the KB-JWT (proof of possession), then revoke that single credential on-chain with the ISSUER key. A holder can therefore only ever revoke a credential they can prove they hold — never someone else\'s.
   * Revoke your OWN credential by proving possession of its holder key.
   */
  revokeOwnCredential(
    requestParameters: RevokeOwnCredentialOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<RevokeOwnCredentialResponse>
}

/**
 *
 */
export class RevocationsApi extends runtime.BaseAPI implements RevocationsApiInterface {
  /**
   */
  async checkRevocationRaw(
    requestParameters: CheckRevocationOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<CheckRevocationResponse>> {
    if (requestParameters['checkRevocationRequest'] == null) {
      throw new runtime.RequiredError(
        'checkRevocationRequest',
        'Required parameter "checkRevocationRequest" was null or undefined when calling checkRevocation().',
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters['Content-Type'] = 'application/json'

    const response = await this.request(
      {
        path: `/revocations/check`,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: CheckRevocationRequestToJSON(requestParameters['checkRevocationRequest']),
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      CheckRevocationResponseFromJSON(jsonValue),
    )
  }

  /**
   */
  async checkRevocation(
    requestParameters: CheckRevocationOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<CheckRevocationResponse> {
    const response = await this.checkRevocationRaw(requestParameters, initOverrides)
    return await response.value()
  }

  /**
   * List revoked credentials
   */
  async listRevokedRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<RevocationEntry>>> {
    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    const response = await this.request(
      {
        path: `/revocations/list`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(RevocationEntryFromJSON),
    )
  }

  /**
   * List revoked credentials
   */
  async listRevoked(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<RevocationEntry>> {
    const response = await this.listRevokedRaw(initOverrides)
    return await response.value()
  }

  /**
   * Unlike `/revocations/revoke` (admin), this needs no admin key. The holder presents the credential with a KB-JWT signed by the `cnf` holder key, bound to a fresh server challenge + the self-revoke audience. We verify the issuer signature (which binds `cnf` ↔ `credential_id`) and the KB-JWT (proof of possession), then revoke that single credential on-chain with the ISSUER key. A holder can therefore only ever revoke a credential they can prove they hold — never someone else\'s.
   * Revoke your OWN credential by proving possession of its holder key.
   */
  async revokeOwnCredentialRaw(
    requestParameters: RevokeOwnCredentialOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<RevokeOwnCredentialResponse>> {
    if (requestParameters['revokeOwnCredentialRequest'] == null) {
      throw new runtime.RequiredError(
        'revokeOwnCredentialRequest',
        'Required parameter "revokeOwnCredentialRequest" was null or undefined when calling revokeOwnCredential().',
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters['Content-Type'] = 'application/json'

    const response = await this.request(
      {
        path: `/revocations/revoke-mine`,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: RevokeOwnCredentialRequestToJSON(requestParameters['revokeOwnCredentialRequest']),
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      RevokeOwnCredentialResponseFromJSON(jsonValue),
    )
  }

  /**
   * Unlike `/revocations/revoke` (admin), this needs no admin key. The holder presents the credential with a KB-JWT signed by the `cnf` holder key, bound to a fresh server challenge + the self-revoke audience. We verify the issuer signature (which binds `cnf` ↔ `credential_id`) and the KB-JWT (proof of possession), then revoke that single credential on-chain with the ISSUER key. A holder can therefore only ever revoke a credential they can prove they hold — never someone else\'s.
   * Revoke your OWN credential by proving possession of its holder key.
   */
  async revokeOwnCredential(
    requestParameters: RevokeOwnCredentialOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<RevokeOwnCredentialResponse> {
    const response = await this.revokeOwnCredentialRaw(requestParameters, initOverrides)
    return await response.value()
  }
}
