/* tslint:disable */
/* eslint-disable */
/**
 * OwlID Verification Service
 * Token verification, trusted issuer management, and credential revocation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime.js'
import type {
  CheckRevocationRequest,
  CheckRevocationResponse,
  RevocationEntry,
} from '../models/index.js'
import {
  CheckRevocationRequestFromJSON,
  CheckRevocationRequestToJSON,
  CheckRevocationResponseFromJSON,
  CheckRevocationResponseToJSON,
  RevocationEntryFromJSON,
  RevocationEntryToJSON,
} from '../models/index.js'

export interface CheckRevocationOperationRequest {
  checkRevocationRequest: CheckRevocationRequest
}

/**
 * RevocationsApi - interface
 *
 * @export
 * @interface RevocationsApiInterface
 */
export interface RevocationsApiInterface {
  /**
   *
   * @param {CheckRevocationRequest} checkRevocationRequest
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof RevocationsApiInterface
   */
  checkRevocationRaw(
    requestParameters: CheckRevocationOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<CheckRevocationResponse>>

  /**
   */
  checkRevocation(
    requestParameters: CheckRevocationOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<CheckRevocationResponse>

  /**
   *
   * @summary List revoked credentials
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof RevocationsApiInterface
   */
  listRevokedRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<RevocationEntry>>>

  /**
   * List revoked credentials
   */
  listRevoked(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<RevocationEntry>>
}

/**
 *
 */
export class RevocationsApi extends runtime.BaseAPI implements RevocationsApiInterface {
  /**
   */
  async checkRevocationRaw(
    requestParameters: CheckRevocationOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<CheckRevocationResponse>> {
    if (requestParameters['checkRevocationRequest'] == null) {
      throw new runtime.RequiredError(
        'checkRevocationRequest',
        'Required parameter "checkRevocationRequest" was null or undefined when calling checkRevocation().',
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters['Content-Type'] = 'application/json'

    const response = await this.request(
      {
        path: `/revocations/check`,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: CheckRevocationRequestToJSON(requestParameters['checkRevocationRequest']),
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      CheckRevocationResponseFromJSON(jsonValue),
    )
  }

  /**
   */
  async checkRevocation(
    requestParameters: CheckRevocationOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<CheckRevocationResponse> {
    const response = await this.checkRevocationRaw(requestParameters, initOverrides)
    return await response.value()
  }

  /**
   * List revoked credentials
   */
  async listRevokedRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<RevocationEntry>>> {
    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    const response = await this.request(
      {
        path: `/revocations/list`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(RevocationEntryFromJSON),
    )
  }

  /**
   * List revoked credentials
   */
  async listRevoked(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<RevocationEntry>> {
    const response = await this.listRevokedRaw(initOverrides)
    return await response.value()
  }
}
