/* tslint:disable */
/* eslint-disable */
/**
 * OwlID Verification Service
 * SD-JWT VC presentation verification, trusted issuer management, and credential revocation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime.js'
import type { ChallengeResponse, VerifyDcqlRequest, VerifyDcqlResponse } from '../models/index.js'
import {
  ChallengeResponseFromJSON,
  ChallengeResponseToJSON,
  VerifyDcqlRequestFromJSON,
  VerifyDcqlRequestToJSON,
  VerifyDcqlResponseFromJSON,
  VerifyDcqlResponseToJSON,
} from '../models/index.js'

export interface VerifyDcqlOperationRequest {
  verifyDcqlRequest: VerifyDcqlRequest
}

/**
 * VerificationApi - interface
 *
 * @export
 * @interface VerificationApiInterface
 */
export interface VerificationApiInterface {
  /**
   * The verifier calls this first, displays/sends the challenge to the holder, the holder creates a token bound to this challenge, then the verifier sends the token + challenge to POST /verify.  This is the FIDO2/WebAuthn pattern: the server generates the challenge so it can guarantee freshness.
   * @summary Generate a server-side challenge for secure verification.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof VerificationApiInterface
   */
  generateChallengeRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<ChallengeResponse>>

  /**
   * The verifier calls this first, displays/sends the challenge to the holder, the holder creates a token bound to this challenge, then the verifier sends the token + challenge to POST /verify.  This is the FIDO2/WebAuthn pattern: the server generates the challenge so it can guarantee freshness.
   * Generate a server-side challenge for secure verification.
   */
  generateChallenge(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<ChallengeResponse>

  /**
   * Consumes the one-shot nonce ONCE, then verifies every `vp_token` entry independently with the same `challenge` and `audience`. Per-credential DCQL constraints (`format`, `meta.vct_values`, `claims[].path`/`values`) are enforced after the crypto chain passes; `credential_sets` are solved over the set of valid ids.
   * @summary DCQL multi-credential verification (OpenID4VP 1.0 §6 + §8.1).
   * @param {VerifyDcqlRequest} verifyDcqlRequest
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof VerificationApiInterface
   */
  verifyDcqlRaw(
    requestParameters: VerifyDcqlOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<VerifyDcqlResponse>>

  /**
   * Consumes the one-shot nonce ONCE, then verifies every `vp_token` entry independently with the same `challenge` and `audience`. Per-credential DCQL constraints (`format`, `meta.vct_values`, `claims[].path`/`values`) are enforced after the crypto chain passes; `credential_sets` are solved over the set of valid ids.
   * DCQL multi-credential verification (OpenID4VP 1.0 §6 + §8.1).
   */
  verifyDcql(
    requestParameters: VerifyDcqlOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<VerifyDcqlResponse>
}

/**
 *
 */
export class VerificationApi extends runtime.BaseAPI implements VerificationApiInterface {
  /**
   * The verifier calls this first, displays/sends the challenge to the holder, the holder creates a token bound to this challenge, then the verifier sends the token + challenge to POST /verify.  This is the FIDO2/WebAuthn pattern: the server generates the challenge so it can guarantee freshness.
   * Generate a server-side challenge for secure verification.
   */
  async generateChallengeRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<ChallengeResponse>> {
    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    const response = await this.request(
      {
        path: `/verify/challenge`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ChallengeResponseFromJSON(jsonValue),
    )
  }

  /**
   * The verifier calls this first, displays/sends the challenge to the holder, the holder creates a token bound to this challenge, then the verifier sends the token + challenge to POST /verify.  This is the FIDO2/WebAuthn pattern: the server generates the challenge so it can guarantee freshness.
   * Generate a server-side challenge for secure verification.
   */
  async generateChallenge(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<ChallengeResponse> {
    const response = await this.generateChallengeRaw(initOverrides)
    return await response.value()
  }

  /**
   * Consumes the one-shot nonce ONCE, then verifies every `vp_token` entry independently with the same `challenge` and `audience`. Per-credential DCQL constraints (`format`, `meta.vct_values`, `claims[].path`/`values`) are enforced after the crypto chain passes; `credential_sets` are solved over the set of valid ids.
   * DCQL multi-credential verification (OpenID4VP 1.0 §6 + §8.1).
   */
  async verifyDcqlRaw(
    requestParameters: VerifyDcqlOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<VerifyDcqlResponse>> {
    if (requestParameters['verifyDcqlRequest'] == null) {
      throw new runtime.RequiredError(
        'verifyDcqlRequest',
        'Required parameter "verifyDcqlRequest" was null or undefined when calling verifyDcql().',
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters['Content-Type'] = 'application/json'

    const response = await this.request(
      {
        path: `/verify/dcql`,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: VerifyDcqlRequestToJSON(requestParameters['verifyDcqlRequest']),
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      VerifyDcqlResponseFromJSON(jsonValue),
    )
  }

  /**
   * Consumes the one-shot nonce ONCE, then verifies every `vp_token` entry independently with the same `challenge` and `audience`. Per-credential DCQL constraints (`format`, `meta.vct_values`, `claims[].path`/`values`) are enforced after the crypto chain passes; `credential_sets` are solved over the set of valid ids.
   * DCQL multi-credential verification (OpenID4VP 1.0 §6 + §8.1).
   */
  async verifyDcql(
    requestParameters: VerifyDcqlOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<VerifyDcqlResponse> {
    const response = await this.verifyDcqlRaw(requestParameters, initOverrides)
    return await response.value()
  }
}
