/* tslint:disable */
/* eslint-disable */
/**
 * OwlID Verification Service
 * Token verification, trusted issuer management, and credential revocation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime.js'
import type { ChallengeResponse, VerifyRequest, VerifyResponse } from '../models/index.js'
import {
  ChallengeResponseFromJSON,
  ChallengeResponseToJSON,
  VerifyRequestFromJSON,
  VerifyRequestToJSON,
  VerifyResponseFromJSON,
  VerifyResponseToJSON,
} from '../models/index.js'

export interface VerifyTokenRequest {
  verifyRequest: VerifyRequest
}

/**
 * VerificationApi - interface
 *
 * @export
 * @interface VerificationApiInterface
 */
export interface VerificationApiInterface {
  /**
   * The verifier calls this first, displays/sends the challenge to the holder, the holder creates a token bound to this challenge, then the verifier sends the token + challenge to POST /verify.  This is the FIDO2/WebAuthn pattern: the server generates the challenge so it can guarantee freshness.
   * @summary Generate a server-side challenge for secure verification.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof VerificationApiInterface
   */
  generateChallengeRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<ChallengeResponse>>

  /**
   * The verifier calls this first, displays/sends the challenge to the holder, the holder creates a token bound to this challenge, then the verifier sends the token + challenge to POST /verify.  This is the FIDO2/WebAuthn pattern: the server generates the challenge so it can guarantee freshness.
   * Generate a server-side challenge for secure verification.
   */
  generateChallenge(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<ChallengeResponse>

  /**
   *
   * @summary Verify a token
   * @param {VerifyRequest} verifyRequest
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof VerificationApiInterface
   */
  verifyTokenRaw(
    requestParameters: VerifyTokenRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<VerifyResponse>>

  /**
   * Verify a token
   */
  verifyToken(
    requestParameters: VerifyTokenRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<VerifyResponse>
}

/**
 *
 */
export class VerificationApi extends runtime.BaseAPI implements VerificationApiInterface {
  /**
   * The verifier calls this first, displays/sends the challenge to the holder, the holder creates a token bound to this challenge, then the verifier sends the token + challenge to POST /verify.  This is the FIDO2/WebAuthn pattern: the server generates the challenge so it can guarantee freshness.
   * Generate a server-side challenge for secure verification.
   */
  async generateChallengeRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<ChallengeResponse>> {
    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    const response = await this.request(
      {
        path: `/verify/challenge`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ChallengeResponseFromJSON(jsonValue),
    )
  }

  /**
   * The verifier calls this first, displays/sends the challenge to the holder, the holder creates a token bound to this challenge, then the verifier sends the token + challenge to POST /verify.  This is the FIDO2/WebAuthn pattern: the server generates the challenge so it can guarantee freshness.
   * Generate a server-side challenge for secure verification.
   */
  async generateChallenge(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<ChallengeResponse> {
    const response = await this.generateChallengeRaw(initOverrides)
    return await response.value()
  }

  /**
   * Verify a token
   */
  async verifyTokenRaw(
    requestParameters: VerifyTokenRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<VerifyResponse>> {
    if (requestParameters['verifyRequest'] == null) {
      throw new runtime.RequiredError(
        'verifyRequest',
        'Required parameter "verifyRequest" was null or undefined when calling verifyToken().',
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters['Content-Type'] = 'application/json'

    const response = await this.request(
      {
        path: `/verify`,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: VerifyRequestToJSON(requestParameters['verifyRequest']),
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) => VerifyResponseFromJSON(jsonValue))
  }

  /**
   * Verify a token
   */
  async verifyToken(
    requestParameters: VerifyTokenRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<VerifyResponse> {
    const response = await this.verifyTokenRaw(requestParameters, initOverrides)
    return await response.value()
  }
}
