substitutions:
  _IMAGE_TAG: latest
  _REGION: europe-west1
  _REPO: owlid
steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - Dockerfile.verification
      - -t
      - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/verification:${_IMAGE_TAG}
      - .
images:
  - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/verification:${_IMAGE_TAG}
options:
  machineType: E2_HIGHCPU_8
  logging: CLOUD_LOGGING_ONLY
timeout: 1800s
