/* tslint:disable */
/* eslint-disable */
/**
 * OwlID Issuer Service
 * Identity verification and credential issuance
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime.js'
import type { ProviderToggleResponse } from '../models/index.js'
import { ProviderToggleResponseFromJSON, ProviderToggleResponseToJSON } from '../models/index.js'

export interface DisableProviderRequest {
  id: string
}

export interface EnableProviderRequest {
  id: string
}

/**
 * AdminApi - interface
 *
 * @export
 * @interface AdminApiInterface
 */
export interface AdminApiInterface {
  /**
   *
   * @summary Disable a provider. Subsequent session-creation requests against it fail closed.
   * @param {string} id Provider ID
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof AdminApiInterface
   */
  disableProviderRaw(
    requestParameters: DisableProviderRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<ProviderToggleResponse>>

  /**
   * Disable a provider. Subsequent session-creation requests against it fail closed.
   */
  disableProvider(
    requestParameters: DisableProviderRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<ProviderToggleResponse>

  /**
   *
   * @summary Enable a previously disabled provider.
   * @param {string} id Provider ID
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof AdminApiInterface
   */
  enableProviderRaw(
    requestParameters: EnableProviderRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<ProviderToggleResponse>>

  /**
   * Enable a previously disabled provider.
   */
  enableProvider(
    requestParameters: EnableProviderRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<ProviderToggleResponse>
}

/**
 *
 */
export class AdminApi extends runtime.BaseAPI implements AdminApiInterface {
  /**
   * Disable a provider. Subsequent session-creation requests against it fail closed.
   */
  async disableProviderRaw(
    requestParameters: DisableProviderRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<ProviderToggleResponse>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling disableProvider().',
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    const response = await this.request(
      {
        path: `/admin/providers/{id}/disable`.replace(
          `{${'id'}}`,
          encodeURIComponent(String(requestParameters['id'])),
        ),
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ProviderToggleResponseFromJSON(jsonValue),
    )
  }

  /**
   * Disable a provider. Subsequent session-creation requests against it fail closed.
   */
  async disableProvider(
    requestParameters: DisableProviderRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<ProviderToggleResponse> {
    const response = await this.disableProviderRaw(requestParameters, initOverrides)
    return await response.value()
  }

  /**
   * Enable a previously disabled provider.
   */
  async enableProviderRaw(
    requestParameters: EnableProviderRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<ProviderToggleResponse>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling enableProvider().',
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    const response = await this.request(
      {
        path: `/admin/providers/{id}/enable`.replace(
          `{${'id'}}`,
          encodeURIComponent(String(requestParameters['id'])),
        ),
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ProviderToggleResponseFromJSON(jsonValue),
    )
  }

  /**
   * Enable a previously disabled provider.
   */
  async enableProvider(
    requestParameters: EnableProviderRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<ProviderToggleResponse> {
    const response = await this.enableProviderRaw(requestParameters, initOverrides)
    return await response.value()
  }
}
