/* tslint:disable */
/* eslint-disable */
/**
 * OwlID Issuer Service
 * Identity verification and credential issuance
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime.js'

export interface HandleSamlCallbackRequest {
  body: any | null
}

export interface HandleWebhookRequest {
  provider: string
  body: any | null
}

/**
 * CallbacksApi - interface
 *
 * @export
 * @interface CallbacksApiInterface
 */
export interface CallbacksApiInterface {
  /**
   *
   * @summary Handle SAML assertion callback from identity provider
   * @param {any} body
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof CallbacksApiInterface
   */
  handleSamlCallbackRaw(
    requestParameters: HandleSamlCallbackRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<any>>

  /**
   * Handle SAML assertion callback from identity provider
   */
  handleSamlCallback(
    requestParameters: HandleSamlCallbackRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<any>

  /**
   *
   * @summary Handle webhook from external provider (Onfido, Jumio, etc.)
   * @param {string} provider Provider ID
   * @param {any} body
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof CallbacksApiInterface
   */
  handleWebhookRaw(
    requestParameters: HandleWebhookRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<any>>

  /**
   * Handle webhook from external provider (Onfido, Jumio, etc.)
   */
  handleWebhook(
    requestParameters: HandleWebhookRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<any>
}

/**
 *
 */
export class CallbacksApi extends runtime.BaseAPI implements CallbacksApiInterface {
  /**
   * Handle SAML assertion callback from identity provider
   */
  async handleSamlCallbackRaw(
    requestParameters: HandleSamlCallbackRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<any>> {
    if (requestParameters['body'] == null) {
      throw new runtime.RequiredError(
        'body',
        'Required parameter "body" was null or undefined when calling handleSamlCallback().',
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters['Content-Type'] = 'application/json'

    const response = await this.request(
      {
        path: `/callbacks/saml`,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: requestParameters['body'] as any,
      },
      initOverrides,
    )

    if (this.isJsonMime(response.headers.get('content-type'))) {
      return new runtime.JSONApiResponse<any>(response)
    } else {
      return new runtime.TextApiResponse(response) as any
    }
  }

  /**
   * Handle SAML assertion callback from identity provider
   */
  async handleSamlCallback(
    requestParameters: HandleSamlCallbackRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<any> {
    const response = await this.handleSamlCallbackRaw(requestParameters, initOverrides)
    return await response.value()
  }

  /**
   * Handle webhook from external provider (Onfido, Jumio, etc.)
   */
  async handleWebhookRaw(
    requestParameters: HandleWebhookRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<any>> {
    if (requestParameters['provider'] == null) {
      throw new runtime.RequiredError(
        'provider',
        'Required parameter "provider" was null or undefined when calling handleWebhook().',
      )
    }

    if (requestParameters['body'] == null) {
      throw new runtime.RequiredError(
        'body',
        'Required parameter "body" was null or undefined when calling handleWebhook().',
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters['Content-Type'] = 'application/json'

    const response = await this.request(
      {
        path: `/callbacks/webhook/{provider}`.replace(
          `{${'provider'}}`,
          encodeURIComponent(String(requestParameters['provider'])),
        ),
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: requestParameters['body'] as any,
      },
      initOverrides,
    )

    if (this.isJsonMime(response.headers.get('content-type'))) {
      return new runtime.JSONApiResponse<any>(response)
    } else {
      return new runtime.TextApiResponse(response) as any
    }
  }

  /**
   * Handle webhook from external provider (Onfido, Jumio, etc.)
   */
  async handleWebhook(
    requestParameters: HandleWebhookRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<any> {
    const response = await this.handleWebhookRaw(requestParameters, initOverrides)
    return await response.value()
  }
}
