/* tslint:disable */
/* eslint-disable */
/**
 * OwlID Issuer Service
 * Identity verification and credential issuance
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { FlowStateOneOf } from './FlowStateOneOf.js'
import {
  instanceOfFlowStateOneOf,
  FlowStateOneOfFromJSON,
  FlowStateOneOfFromJSONTyped,
  FlowStateOneOfToJSON,
} from './FlowStateOneOf.js'
import type { FlowStateOneOf1 } from './FlowStateOneOf1.js'
import {
  instanceOfFlowStateOneOf1,
  FlowStateOneOf1FromJSON,
  FlowStateOneOf1FromJSONTyped,
  FlowStateOneOf1ToJSON,
} from './FlowStateOneOf1.js'
import type { FlowStateOneOf2 } from './FlowStateOneOf2.js'
import {
  instanceOfFlowStateOneOf2,
  FlowStateOneOf2FromJSON,
  FlowStateOneOf2FromJSONTyped,
  FlowStateOneOf2ToJSON,
} from './FlowStateOneOf2.js'
import type { FlowStateOneOf3 } from './FlowStateOneOf3.js'
import {
  instanceOfFlowStateOneOf3,
  FlowStateOneOf3FromJSON,
  FlowStateOneOf3FromJSONTyped,
  FlowStateOneOf3ToJSON,
} from './FlowStateOneOf3.js'
import type { FlowStateOneOf4 } from './FlowStateOneOf4.js'
import {
  instanceOfFlowStateOneOf4,
  FlowStateOneOf4FromJSON,
  FlowStateOneOf4FromJSONTyped,
  FlowStateOneOf4ToJSON,
} from './FlowStateOneOf4.js'
import type { FlowStateOneOf5 } from './FlowStateOneOf5.js'
import {
  instanceOfFlowStateOneOf5,
  FlowStateOneOf5FromJSON,
  FlowStateOneOf5FromJSONTyped,
  FlowStateOneOf5ToJSON,
} from './FlowStateOneOf5.js'
import type { FlowStateOneOf6 } from './FlowStateOneOf6.js'
import {
  instanceOfFlowStateOneOf6,
  FlowStateOneOf6FromJSON,
  FlowStateOneOf6FromJSONTyped,
  FlowStateOneOf6ToJSON,
} from './FlowStateOneOf6.js'
import type { FlowStateOneOf7 } from './FlowStateOneOf7.js'
import {
  instanceOfFlowStateOneOf7,
  FlowStateOneOf7FromJSON,
  FlowStateOneOf7FromJSONTyped,
  FlowStateOneOf7ToJSON,
} from './FlowStateOneOf7.js'
import type { FlowStateOneOf8 } from './FlowStateOneOf8.js'
import {
  instanceOfFlowStateOneOf8,
  FlowStateOneOf8FromJSON,
  FlowStateOneOf8FromJSONTyped,
  FlowStateOneOf8ToJSON,
} from './FlowStateOneOf8.js'
import type { FlowStateOneOf9 } from './FlowStateOneOf9.js'
import {
  instanceOfFlowStateOneOf9,
  FlowStateOneOf9FromJSON,
  FlowStateOneOf9FromJSONTyped,
  FlowStateOneOf9ToJSON,
} from './FlowStateOneOf9.js'

/**
 * @type FlowState
 * Flow-specific state for verification sessions
 * @export
 */
export type FlowState =
  | FlowStateOneOf
  | FlowStateOneOf1
  | FlowStateOneOf2
  | FlowStateOneOf3
  | FlowStateOneOf4
  | FlowStateOneOf5
  | FlowStateOneOf6
  | FlowStateOneOf7
  | FlowStateOneOf8
  | FlowStateOneOf9

export function FlowStateFromJSON(json: any): FlowState {
  return FlowStateFromJSONTyped(json, false)
}

export function FlowStateFromJSONTyped(json: any, ignoreDiscriminator: boolean): FlowState {
  if (json == null) {
    return json
  }
  if (instanceOfFlowStateOneOf(json)) {
    return FlowStateOneOfFromJSONTyped(json, true)
  }
  if (instanceOfFlowStateOneOf1(json)) {
    return FlowStateOneOf1FromJSONTyped(json, true)
  }
  if (instanceOfFlowStateOneOf2(json)) {
    return FlowStateOneOf2FromJSONTyped(json, true)
  }
  if (instanceOfFlowStateOneOf3(json)) {
    return FlowStateOneOf3FromJSONTyped(json, true)
  }
  if (instanceOfFlowStateOneOf4(json)) {
    return FlowStateOneOf4FromJSONTyped(json, true)
  }
  if (instanceOfFlowStateOneOf5(json)) {
    return FlowStateOneOf5FromJSONTyped(json, true)
  }
  if (instanceOfFlowStateOneOf6(json)) {
    return FlowStateOneOf6FromJSONTyped(json, true)
  }
  if (instanceOfFlowStateOneOf7(json)) {
    return FlowStateOneOf7FromJSONTyped(json, true)
  }
  if (instanceOfFlowStateOneOf8(json)) {
    return FlowStateOneOf8FromJSONTyped(json, true)
  }
  if (instanceOfFlowStateOneOf9(json)) {
    return FlowStateOneOf9FromJSONTyped(json, true)
  }

  return {} as any
}

export function FlowStateToJSON(json: any): any {
  return FlowStateToJSONTyped(json, false)
}

export function FlowStateToJSONTyped(
  value?: FlowState | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  if (instanceOfFlowStateOneOf(value)) {
    return FlowStateOneOfToJSON(value as FlowStateOneOf)
  }
  if (instanceOfFlowStateOneOf1(value)) {
    return FlowStateOneOf1ToJSON(value as FlowStateOneOf1)
  }
  if (instanceOfFlowStateOneOf2(value)) {
    return FlowStateOneOf2ToJSON(value as FlowStateOneOf2)
  }
  if (instanceOfFlowStateOneOf3(value)) {
    return FlowStateOneOf3ToJSON(value as FlowStateOneOf3)
  }
  if (instanceOfFlowStateOneOf4(value)) {
    return FlowStateOneOf4ToJSON(value as FlowStateOneOf4)
  }
  if (instanceOfFlowStateOneOf5(value)) {
    return FlowStateOneOf5ToJSON(value as FlowStateOneOf5)
  }
  if (instanceOfFlowStateOneOf6(value)) {
    return FlowStateOneOf6ToJSON(value as FlowStateOneOf6)
  }
  if (instanceOfFlowStateOneOf7(value)) {
    return FlowStateOneOf7ToJSON(value as FlowStateOneOf7)
  }
  if (instanceOfFlowStateOneOf8(value)) {
    return FlowStateOneOf8ToJSON(value as FlowStateOneOf8)
  }
  if (instanceOfFlowStateOneOf9(value)) {
    return FlowStateOneOf9ToJSON(value as FlowStateOneOf9)
  }

  return {}
}
