/* tslint:disable */
/* eslint-disable */
/**
 * OwlID Issuer Service
 * Identity verification and credential issuance
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js'
/**
 * Polling: order created, waiting for user to complete
 * @export
 * @interface FlowStateOneOf3
 */
export interface FlowStateOneOf3 {
  /**
   * Last poll timestamp
   * @type {Date}
   * @memberof FlowStateOneOf3
   */
  lastPoll: Date
  /**
   * Reference for polling the status
   * @type {string}
   * @memberof FlowStateOneOf3
   */
  orderRef: string
  /**
   * Number of times we've polled
   * @type {number}
   * @memberof FlowStateOneOf3
   */
  pollCount: number
  /**
   *
   * @type {string}
   * @memberof FlowStateOneOf3
   */
  type: FlowStateOneOf3TypeEnum
}

/**
 * @export
 * @enum {string}
 */
export enum FlowStateOneOf3TypeEnum {
  polling = 'polling',
}

/**
 * Check if a given object implements the FlowStateOneOf3 interface.
 */
export function instanceOfFlowStateOneOf3(value: object): value is FlowStateOneOf3 {
  if (!('lastPoll' in value) || value['lastPoll'] === undefined) return false
  if (!('orderRef' in value) || value['orderRef'] === undefined) return false
  if (!('pollCount' in value) || value['pollCount'] === undefined) return false
  if (!('type' in value) || value['type'] === undefined) return false
  return true
}

export function FlowStateOneOf3FromJSON(json: any): FlowStateOneOf3 {
  return FlowStateOneOf3FromJSONTyped(json, false)
}

export function FlowStateOneOf3FromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): FlowStateOneOf3 {
  if (json == null) {
    return json
  }
  return {
    lastPoll: new Date(json['lastPoll']),
    orderRef: json['orderRef'],
    pollCount: json['pollCount'],
    type: json['type'],
  }
}

export function FlowStateOneOf3ToJSON(json: any): FlowStateOneOf3 {
  return FlowStateOneOf3ToJSONTyped(json, false)
}

export function FlowStateOneOf3ToJSONTyped(
  value?: FlowStateOneOf3 | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    lastPoll: value['lastPoll'].toISOString(),
    orderRef: value['orderRef'],
    pollCount: value['pollCount'],
    type: value['type'],
  }
}
