/* tslint:disable */
/* eslint-disable */
/**
 * OwlID Issuer Service
 * Identity verification and credential issuance
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js'
/**
 * Verification failed
 * @export
 * @interface FlowStateOneOf11
 */
export interface FlowStateOneOf11 {
  /**
   *
   * @type {string}
   * @memberof FlowStateOneOf11
   */
  reason: string
  /**
   *
   * @type {string}
   * @memberof FlowStateOneOf11
   */
  type: FlowStateOneOf11TypeEnum
}

/**
 * @export
 * @enum {string}
 */
export enum FlowStateOneOf11TypeEnum {
  failed = 'failed',
}

/**
 * Check if a given object implements the FlowStateOneOf11 interface.
 */
export function instanceOfFlowStateOneOf11(value: object): value is FlowStateOneOf11 {
  if (!('reason' in value) || value['reason'] === undefined) return false
  if (!('type' in value) || value['type'] === undefined) return false
  return true
}

export function FlowStateOneOf11FromJSON(json: any): FlowStateOneOf11 {
  return FlowStateOneOf11FromJSONTyped(json, false)
}

export function FlowStateOneOf11FromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): FlowStateOneOf11 {
  if (json == null) {
    return json
  }
  return {
    reason: json['reason'],
    type: json['type'],
  }
}

export function FlowStateOneOf11ToJSON(json: any): FlowStateOneOf11 {
  return FlowStateOneOf11ToJSONTyped(json, false)
}

export function FlowStateOneOf11ToJSONTyped(
  value?: FlowStateOneOf11 | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    reason: value['reason'],
    type: value['type'],
  }
}
