/* tslint:disable */
/* eslint-disable */
/**
 * OwlID Issuer Service
 * Identity verification and credential issuance
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js'
/**
 * Form: waiting for user to submit form
 * @export
 * @interface FlowStateOneOf8
 */
export interface FlowStateOneOf8 {
  /**
   *
   * @type {string}
   * @memberof FlowStateOneOf8
   */
  type: FlowStateOneOf8TypeEnum
}

/**
 * @export
 * @enum {string}
 */
export enum FlowStateOneOf8TypeEnum {
  form_pending = 'form_pending',
}

/**
 * Check if a given object implements the FlowStateOneOf8 interface.
 */
export function instanceOfFlowStateOneOf8(value: object): value is FlowStateOneOf8 {
  if (!('type' in value) || value['type'] === undefined) return false
  return true
}

export function FlowStateOneOf8FromJSON(json: any): FlowStateOneOf8 {
  return FlowStateOneOf8FromJSONTyped(json, false)
}

export function FlowStateOneOf8FromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): FlowStateOneOf8 {
  if (json == null) {
    return json
  }
  return {
    type: json['type'],
  }
}

export function FlowStateOneOf8ToJSON(json: any): FlowStateOneOf8 {
  return FlowStateOneOf8ToJSONTyped(json, false)
}

export function FlowStateOneOf8ToJSONTyped(
  value?: FlowStateOneOf8 | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    type: value['type'],
  }
}
