/* tslint:disable */
/* eslint-disable */
/**
 * OwlID Issuer Service
 * Identity verification and credential issuance
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js'
/**
 * Polling: initial state, waiting for order to be created
 * @export
 * @interface FlowStateOneOf2
 */
export interface FlowStateOneOf2 {
  /**
   *
   * @type {string}
   * @memberof FlowStateOneOf2
   */
  type: FlowStateOneOf2TypeEnum
}

/**
 * @export
 * @enum {string}
 */
export enum FlowStateOneOf2TypeEnum {
  polling_pending = 'polling_pending',
}

/**
 * Check if a given object implements the FlowStateOneOf2 interface.
 */
export function instanceOfFlowStateOneOf2(value: object): value is FlowStateOneOf2 {
  if (!('type' in value) || value['type'] === undefined) return false
  return true
}

export function FlowStateOneOf2FromJSON(json: any): FlowStateOneOf2 {
  return FlowStateOneOf2FromJSONTyped(json, false)
}

export function FlowStateOneOf2FromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): FlowStateOneOf2 {
  if (json == null) {
    return json
  }
  return {
    type: json['type'],
  }
}

export function FlowStateOneOf2ToJSON(json: any): FlowStateOneOf2 {
  return FlowStateOneOf2ToJSONTyped(json, false)
}

export function FlowStateOneOf2ToJSONTyped(
  value?: FlowStateOneOf2 | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    type: value['type'],
  }
}
