/* tslint:disable */
/* eslint-disable */
/**
 * OwlID Issuer Service
 * Identity verification and credential issuance
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js'
/**
 * Webhook: waiting for external session to be created
 * @export
 * @interface FlowStateOneOf4
 */
export interface FlowStateOneOf4 {
  /**
   * External session/applicant ID (set after redirect)
   * @type {string}
   * @memberof FlowStateOneOf4
   */
  externalSessionId?: string | null
  /**
   *
   * @type {string}
   * @memberof FlowStateOneOf4
   */
  type: FlowStateOneOf4TypeEnum
}

/**
 * @export
 * @enum {string}
 */
export enum FlowStateOneOf4TypeEnum {
  webhook_pending = 'webhook_pending',
}

/**
 * Check if a given object implements the FlowStateOneOf4 interface.
 */
export function instanceOfFlowStateOneOf4(value: object): value is FlowStateOneOf4 {
  if (!('type' in value) || value['type'] === undefined) return false
  return true
}

export function FlowStateOneOf4FromJSON(json: any): FlowStateOneOf4 {
  return FlowStateOneOf4FromJSONTyped(json, false)
}

export function FlowStateOneOf4FromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): FlowStateOneOf4 {
  if (json == null) {
    return json
  }
  return {
    externalSessionId: json['externalSessionId'] == null ? undefined : json['externalSessionId'],
    type: json['type'],
  }
}

export function FlowStateOneOf4ToJSON(json: any): FlowStateOneOf4 {
  return FlowStateOneOf4ToJSONTyped(json, false)
}

export function FlowStateOneOf4ToJSONTyped(
  value?: FlowStateOneOf4 | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    externalSessionId: value['externalSessionId'],
    type: value['type'],
  }
}
