/* tslint:disable */
/* eslint-disable */
/**
 * OwlID Issuer Service
 * Identity verification and credential issuance
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js'
/**
 * Form submitted by user during identity verification
 * @export
 * @interface IdentitySubmissionForm
 */
export interface IdentitySubmissionForm {
  /**
   *
   * @type {string}
   * @memberof IdentitySubmissionForm
   */
  city: string
  /**
   *
   * @type {string}
   * @memberof IdentitySubmissionForm
   */
  country: string
  /**
   *
   * @type {Date}
   * @memberof IdentitySubmissionForm
   */
  dateOfBirth: Date
  /**
   *
   * @type {string}
   * @memberof IdentitySubmissionForm
   */
  driversLicense?: string | null
  /**
   *
   * @type {string}
   * @memberof IdentitySubmissionForm
   */
  firstName: string
  /**
   *
   * @type {string}
   * @memberof IdentitySubmissionForm
   */
  gender?: string | null
  /**
   *
   * @type {string}
   * @memberof IdentitySubmissionForm
   */
  lastName: string
  /**
   *
   * @type {string}
   * @memberof IdentitySubmissionForm
   */
  nationalId: string
  /**
   *
   * @type {string}
   * @memberof IdentitySubmissionForm
   */
  nationality: string
  /**
   *
   * @type {string}
   * @memberof IdentitySubmissionForm
   */
  passportNumber?: string | null
  /**
   *
   * @type {string}
   * @memberof IdentitySubmissionForm
   */
  placeOfBirth: string
  /**
   *
   * @type {string}
   * @memberof IdentitySubmissionForm
   */
  postalCode: string
  /**
   *
   * @type {string}
   * @memberof IdentitySubmissionForm
   */
  streetAddress: string
  /**
   *
   * @type {string}
   * @memberof IdentitySubmissionForm
   */
  taxId?: string | null
}

/**
 * Check if a given object implements the IdentitySubmissionForm interface.
 */
export function instanceOfIdentitySubmissionForm(value: object): value is IdentitySubmissionForm {
  if (!('city' in value) || value['city'] === undefined) return false
  if (!('country' in value) || value['country'] === undefined) return false
  if (!('dateOfBirth' in value) || value['dateOfBirth'] === undefined) return false
  if (!('firstName' in value) || value['firstName'] === undefined) return false
  if (!('lastName' in value) || value['lastName'] === undefined) return false
  if (!('nationalId' in value) || value['nationalId'] === undefined) return false
  if (!('nationality' in value) || value['nationality'] === undefined) return false
  if (!('placeOfBirth' in value) || value['placeOfBirth'] === undefined) return false
  if (!('postalCode' in value) || value['postalCode'] === undefined) return false
  if (!('streetAddress' in value) || value['streetAddress'] === undefined) return false
  return true
}

export function IdentitySubmissionFormFromJSON(json: any): IdentitySubmissionForm {
  return IdentitySubmissionFormFromJSONTyped(json, false)
}

export function IdentitySubmissionFormFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): IdentitySubmissionForm {
  if (json == null) {
    return json
  }
  return {
    city: json['city'],
    country: json['country'],
    dateOfBirth: new Date(json['dateOfBirth']),
    driversLicense: json['driversLicense'] == null ? undefined : json['driversLicense'],
    firstName: json['firstName'],
    gender: json['gender'] == null ? undefined : json['gender'],
    lastName: json['lastName'],
    nationalId: json['nationalId'],
    nationality: json['nationality'],
    passportNumber: json['passportNumber'] == null ? undefined : json['passportNumber'],
    placeOfBirth: json['placeOfBirth'],
    postalCode: json['postalCode'],
    streetAddress: json['streetAddress'],
    taxId: json['taxId'] == null ? undefined : json['taxId'],
  }
}

export function IdentitySubmissionFormToJSON(json: any): IdentitySubmissionForm {
  return IdentitySubmissionFormToJSONTyped(json, false)
}

export function IdentitySubmissionFormToJSONTyped(
  value?: IdentitySubmissionForm | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    city: value['city'],
    country: value['country'],
    dateOfBirth: value['dateOfBirth'].toISOString().substring(0, 10),
    driversLicense: value['driversLicense'],
    firstName: value['firstName'],
    gender: value['gender'],
    lastName: value['lastName'],
    nationalId: value['nationalId'],
    nationality: value['nationality'],
    passportNumber: value['passportNumber'],
    placeOfBirth: value['placeOfBirth'],
    postalCode: value['postalCode'],
    streetAddress: value['streetAddress'],
    taxId: value['taxId'],
  }
}
