/* tslint:disable */
/* eslint-disable */
/**
 * OwlID Issuer Service
 * Identity verification and credential issuance
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js'
/**
 * Issuer info response
 * @export
 * @interface IssuerInfoResponse
 */
export interface IssuerInfoResponse {
  /**
   *
   * @type {string}
   * @memberof IssuerInfoResponse
   */
  name: string
  /**
   *
   * @type {string}
   * @memberof IssuerInfoResponse
   */
  publicKey: string
}

/**
 * Check if a given object implements the IssuerInfoResponse interface.
 */
export function instanceOfIssuerInfoResponse(value: object): value is IssuerInfoResponse {
  if (!('name' in value) || value['name'] === undefined) return false
  if (!('publicKey' in value) || value['publicKey'] === undefined) return false
  return true
}

export function IssuerInfoResponseFromJSON(json: any): IssuerInfoResponse {
  return IssuerInfoResponseFromJSONTyped(json, false)
}

export function IssuerInfoResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): IssuerInfoResponse {
  if (json == null) {
    return json
  }
  return {
    name: json['name'],
    publicKey: json['publicKey'],
  }
}

export function IssuerInfoResponseToJSON(json: any): IssuerInfoResponse {
  return IssuerInfoResponseToJSONTyped(json, false)
}

export function IssuerInfoResponseToJSONTyped(
  value?: IssuerInfoResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    name: value['name'],
    publicKey: value['publicKey'],
  }
}
