/* tslint:disable */
/* eslint-disable */
/**
 * OwlID Issuer Service
 * Identity verification and credential issuance
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js'
/**
 *
 * @export
 * @interface OidcCallbackResponse
 */
export interface OidcCallbackResponse {
  /**
   *
   * @type {{ [key: string]: any; }}
   * @memberof OidcCallbackResponse
   */
  claims: { [key: string]: any }
  /**
   *
   * @type {boolean}
   * @memberof OidcCallbackResponse
   */
  hasIdToken: boolean
  /**
   *
   * @type {string}
   * @memberof OidcCallbackResponse
   */
  message: string
  /**
   *
   * @type {string}
   * @memberof OidcCallbackResponse
   */
  providerId: string
}

/**
 * Check if a given object implements the OidcCallbackResponse interface.
 */
export function instanceOfOidcCallbackResponse(value: object): value is OidcCallbackResponse {
  if (!('claims' in value) || value['claims'] === undefined) return false
  if (!('hasIdToken' in value) || value['hasIdToken'] === undefined) return false
  if (!('message' in value) || value['message'] === undefined) return false
  if (!('providerId' in value) || value['providerId'] === undefined) return false
  return true
}

export function OidcCallbackResponseFromJSON(json: any): OidcCallbackResponse {
  return OidcCallbackResponseFromJSONTyped(json, false)
}

export function OidcCallbackResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): OidcCallbackResponse {
  if (json == null) {
    return json
  }
  return {
    claims: json['claims'],
    hasIdToken: json['hasIdToken'],
    message: json['message'],
    providerId: json['providerId'],
  }
}

export function OidcCallbackResponseToJSON(json: any): OidcCallbackResponse {
  return OidcCallbackResponseToJSONTyped(json, false)
}

export function OidcCallbackResponseToJSONTyped(
  value?: OidcCallbackResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    claims: value['claims'],
    hasIdToken: value['hasIdToken'],
    message: value['message'],
    providerId: value['providerId'],
  }
}
