/* tslint:disable */
/* eslint-disable */
/**
 * OwlID Issuer Service
 * Identity verification and credential issuance
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js'
/**
 *
 * @export
 * @interface OidcLoginResponse
 */
export interface OidcLoginResponse {
  /**
   *
   * @type {string}
   * @memberof OidcLoginResponse
   */
  authUrl: string
  /**
   *
   * @type {string}
   * @memberof OidcLoginResponse
   */
  discoveryUrl: string
  /**
   *
   * @type {string}
   * @memberof OidcLoginResponse
   */
  state: string
}

/**
 * Check if a given object implements the OidcLoginResponse interface.
 */
export function instanceOfOidcLoginResponse(value: object): value is OidcLoginResponse {
  if (!('authUrl' in value) || value['authUrl'] === undefined) return false
  if (!('discoveryUrl' in value) || value['discoveryUrl'] === undefined) return false
  if (!('state' in value) || value['state'] === undefined) return false
  return true
}

export function OidcLoginResponseFromJSON(json: any): OidcLoginResponse {
  return OidcLoginResponseFromJSONTyped(json, false)
}

export function OidcLoginResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): OidcLoginResponse {
  if (json == null) {
    return json
  }
  return {
    authUrl: json['authUrl'],
    discoveryUrl: json['discoveryUrl'],
    state: json['state'],
  }
}

export function OidcLoginResponseToJSON(json: any): OidcLoginResponse {
  return OidcLoginResponseToJSONTyped(json, false)
}

export function OidcLoginResponseToJSONTyped(
  value?: OidcLoginResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    authUrl: value['authUrl'],
    discoveryUrl: value['discoveryUrl'],
    state: value['state'],
  }
}
