/* tslint:disable */
/* eslint-disable */
/**
 * OwlID Issuer Service
 * Identity verification and credential issuance
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js'
import type { SessionStatus } from './SessionStatus.js'
import {
  SessionStatusFromJSON,
  SessionStatusFromJSONTyped,
  SessionStatusToJSON,
  SessionStatusToJSONTyped,
} from './SessionStatus.js'

/**
 *
 * @export
 * @interface PollResponse
 */
export interface PollResponse {
  /**
   *
   * @type {string}
   * @memberof PollResponse
   */
  hint?: string | null
  /**
   *
   * @type {string}
   * @memberof PollResponse
   */
  message: string
  /**
   *
   * @type {SessionStatus}
   * @memberof PollResponse
   */
  status: SessionStatus
}

/**
 * Check if a given object implements the PollResponse interface.
 */
export function instanceOfPollResponse(value: object): value is PollResponse {
  if (!('message' in value) || value['message'] === undefined) return false
  if (!('status' in value) || value['status'] === undefined) return false
  return true
}

export function PollResponseFromJSON(json: any): PollResponse {
  return PollResponseFromJSONTyped(json, false)
}

export function PollResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PollResponse {
  if (json == null) {
    return json
  }
  return {
    hint: json['hint'] == null ? undefined : json['hint'],
    message: json['message'],
    status: SessionStatusFromJSON(json['status']),
  }
}

export function PollResponseToJSON(json: any): PollResponse {
  return PollResponseToJSONTyped(json, false)
}

export function PollResponseToJSONTyped(
  value?: PollResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    hint: value['hint'],
    message: value['message'],
    status: SessionStatusToJSON(value['status']),
  }
}
