/* tslint:disable */
/* eslint-disable */
/**
 * OwlID Issuer Service
 * Identity verification and credential issuance
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * The type of verification flow used by an identity provider
 * @export
 * @enum {string}
 */
export enum ProviderFlowType {
  saml_redirect = 'saml_redirect',
  qr_polling = 'qr_polling',
  webhook_async = 'webhook_async',
  form_based = 'form_based',
}

export function instanceOfProviderFlowType(value: any): boolean {
  for (const key in ProviderFlowType) {
    if (Object.prototype.hasOwnProperty.call(ProviderFlowType, key)) {
      if (ProviderFlowType[key as keyof typeof ProviderFlowType] === value) {
        return true
      }
    }
  }
  return false
}

export function ProviderFlowTypeFromJSON(json: any): ProviderFlowType {
  return ProviderFlowTypeFromJSONTyped(json, false)
}

export function ProviderFlowTypeFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ProviderFlowType {
  return json as ProviderFlowType
}

export function ProviderFlowTypeToJSON(value?: ProviderFlowType | null): any {
  return value as any
}

export function ProviderFlowTypeToJSONTyped(
  value: any,
  ignoreDiscriminator: boolean,
): ProviderFlowType {
  return value as ProviderFlowType
}
