/* tslint:disable */
/* eslint-disable */
/**
 * OwlID Issuer Service
 * Identity verification and credential issuance
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js'
import type { VerificationLevel } from './VerificationLevel.js'
import {
  VerificationLevelFromJSON,
  VerificationLevelFromJSONTyped,
  VerificationLevelToJSON,
  VerificationLevelToJSONTyped,
} from './VerificationLevel.js'

/**
 * Static, intrinsic facts about an identity provider, returned by the
 * provider's trait impl. Composed with runtime fields (flow type,
 * verification level, enabled flag) at registry-list time into the
 * public `ProviderInfo` type exposed over OpenAPI.
 * @export
 * @interface ProviderDescriptor
 */
export interface ProviderDescriptor {
  /**
   *
   * @type {string}
   * @memberof ProviderDescriptor
   */
  country: string
  /**
   *
   * @type {string}
   * @memberof ProviderDescriptor
   */
  description: string
  /**
   *
   * @type {string}
   * @memberof ProviderDescriptor
   */
  id: string
  /**
   *
   * @type {string}
   * @memberof ProviderDescriptor
   */
  name: string
  /**
   *
   * @type {Array<VerificationLevel>}
   * @memberof ProviderDescriptor
   */
  verificationLevels: Array<VerificationLevel>
}

/**
 * Check if a given object implements the ProviderDescriptor interface.
 */
export function instanceOfProviderDescriptor(value: object): value is ProviderDescriptor {
  if (!('country' in value) || value['country'] === undefined) return false
  if (!('description' in value) || value['description'] === undefined) return false
  if (!('id' in value) || value['id'] === undefined) return false
  if (!('name' in value) || value['name'] === undefined) return false
  if (!('verificationLevels' in value) || value['verificationLevels'] === undefined) return false
  return true
}

export function ProviderDescriptorFromJSON(json: any): ProviderDescriptor {
  return ProviderDescriptorFromJSONTyped(json, false)
}

export function ProviderDescriptorFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ProviderDescriptor {
  if (json == null) {
    return json
  }
  return {
    country: json['country'],
    description: json['description'],
    id: json['id'],
    name: json['name'],
    verificationLevels: (json['verificationLevels'] as Array<any>).map(VerificationLevelFromJSON),
  }
}

export function ProviderDescriptorToJSON(json: any): ProviderDescriptor {
  return ProviderDescriptorToJSONTyped(json, false)
}

export function ProviderDescriptorToJSONTyped(
  value?: ProviderDescriptor | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    country: value['country'],
    description: value['description'],
    id: value['id'],
    name: value['name'],
    verificationLevels: (value['verificationLevels'] as Array<any>).map(VerificationLevelToJSON),
  }
}
