/* tslint:disable */
/* eslint-disable */
/**
 * OwlID Issuer Service
 * Identity verification and credential issuance
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js'
/**
 *
 * @export
 * @interface ProviderToggleResponse
 */
export interface ProviderToggleResponse {
  /**
   *
   * @type {boolean}
   * @memberof ProviderToggleResponse
   */
  enabled: boolean
  /**
   *
   * @type {string}
   * @memberof ProviderToggleResponse
   */
  providerId: string
}

/**
 * Check if a given object implements the ProviderToggleResponse interface.
 */
export function instanceOfProviderToggleResponse(value: object): value is ProviderToggleResponse {
  if (!('enabled' in value) || value['enabled'] === undefined) return false
  if (!('providerId' in value) || value['providerId'] === undefined) return false
  return true
}

export function ProviderToggleResponseFromJSON(json: any): ProviderToggleResponse {
  return ProviderToggleResponseFromJSONTyped(json, false)
}

export function ProviderToggleResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ProviderToggleResponse {
  if (json == null) {
    return json
  }
  return {
    enabled: json['enabled'],
    providerId: json['providerId'],
  }
}

export function ProviderToggleResponseToJSON(json: any): ProviderToggleResponse {
  return ProviderToggleResponseToJSONTyped(json, false)
}

export function ProviderToggleResponseToJSONTyped(
  value?: ProviderToggleResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    enabled: value['enabled'],
    providerId: value['providerId'],
  }
}
