/* tslint:disable */
/* eslint-disable */
/**
 * OwlID Issuer Service
 * Identity verification and credential issuance
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js'
import type { FlowState } from './FlowState.js'
import {
  FlowStateFromJSON,
  FlowStateFromJSONTyped,
  FlowStateToJSON,
  FlowStateToJSONTyped,
} from './FlowState.js'
import type { SessionStatus } from './SessionStatus.js'
import {
  SessionStatusFromJSON,
  SessionStatusFromJSONTyped,
  SessionStatusToJSON,
  SessionStatusToJSONTyped,
} from './SessionStatus.js'
import type { ProviderFlowType } from './ProviderFlowType.js'
import {
  ProviderFlowTypeFromJSON,
  ProviderFlowTypeFromJSONTyped,
  ProviderFlowTypeToJSON,
  ProviderFlowTypeToJSONTyped,
} from './ProviderFlowType.js'

/**
 * Extended session response with flow state
 * @export
 * @interface SessionResponse
 */
export interface SessionResponse {
  /**
   *
   * @type {boolean}
   * @memberof SessionResponse
   */
  credentialIssued: boolean
  /**
   *
   * @type {string}
   * @memberof SessionResponse
   */
  expiresAt: string
  /**
   *
   * @type {FlowState}
   * @memberof SessionResponse
   */
  flowState: FlowState
  /**
   *
   * @type {ProviderFlowType}
   * @memberof SessionResponse
   */
  flowType: ProviderFlowType
  /**
   *
   * @type {string}
   * @memberof SessionResponse
   */
  id: string
  /**
   *
   * @type {boolean}
   * @memberof SessionResponse
   */
  isExpired: boolean
  /**
   *
   * @type {string}
   * @memberof SessionResponse
   */
  providerId: string
  /**
   *
   * @type {SessionStatus}
   * @memberof SessionResponse
   */
  status: SessionStatus
  /**
   *
   * @type {string}
   * @memberof SessionResponse
   */
  verifiedAt?: string | null
}

/**
 * Check if a given object implements the SessionResponse interface.
 */
export function instanceOfSessionResponse(value: object): value is SessionResponse {
  if (!('credentialIssued' in value) || value['credentialIssued'] === undefined) return false
  if (!('expiresAt' in value) || value['expiresAt'] === undefined) return false
  if (!('flowState' in value) || value['flowState'] === undefined) return false
  if (!('flowType' in value) || value['flowType'] === undefined) return false
  if (!('id' in value) || value['id'] === undefined) return false
  if (!('isExpired' in value) || value['isExpired'] === undefined) return false
  if (!('providerId' in value) || value['providerId'] === undefined) return false
  if (!('status' in value) || value['status'] === undefined) return false
  return true
}

export function SessionResponseFromJSON(json: any): SessionResponse {
  return SessionResponseFromJSONTyped(json, false)
}

export function SessionResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): SessionResponse {
  if (json == null) {
    return json
  }
  return {
    credentialIssued: json['credentialIssued'],
    expiresAt: json['expiresAt'],
    flowState: FlowStateFromJSON(json['flowState']),
    flowType: ProviderFlowTypeFromJSON(json['flowType']),
    id: json['id'],
    isExpired: json['isExpired'],
    providerId: json['providerId'],
    status: SessionStatusFromJSON(json['status']),
    verifiedAt: json['verifiedAt'] == null ? undefined : json['verifiedAt'],
  }
}

export function SessionResponseToJSON(json: any): SessionResponse {
  return SessionResponseToJSONTyped(json, false)
}

export function SessionResponseToJSONTyped(
  value?: SessionResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    credentialIssued: value['credentialIssued'],
    expiresAt: value['expiresAt'],
    flowState: FlowStateToJSON(value['flowState']),
    flowType: ProviderFlowTypeToJSON(value['flowType']),
    id: value['id'],
    isExpired: value['isExpired'],
    providerId: value['providerId'],
    status: SessionStatusToJSON(value['status']),
    verifiedAt: value['verifiedAt'],
  }
}
