/* tslint:disable */
/* eslint-disable */
/**
 * OwlID Issuer Service
 * Identity verification and credential issuance
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js'
/**
 * Show QR code, poll this order (BankID-style)
 * @export
 * @interface VerificationStartOneOf1
 */
export interface VerificationStartOneOf1 {
  /**
   * URL for user's mobile app to open directly (optional)
   * @type {string}
   * @memberof VerificationStartOneOf1
   */
  autoStartUrl?: string | null
  /**
   * Reference for polling the order status
   * @type {string}
   * @memberof VerificationStartOneOf1
   */
  orderRef: string
  /**
   * Data to encode in QR code (user scans with mobile app)
   * @type {string}
   * @memberof VerificationStartOneOf1
   */
  qrData: string
  /**
   *
   * @type {string}
   * @memberof VerificationStartOneOf1
   */
  type: VerificationStartOneOf1TypeEnum
}

/**
 * @export
 * @enum {string}
 */
export enum VerificationStartOneOf1TypeEnum {
  qrCode = 'qrCode',
}

/**
 * Check if a given object implements the VerificationStartOneOf1 interface.
 */
export function instanceOfVerificationStartOneOf1(value: object): value is VerificationStartOneOf1 {
  if (!('orderRef' in value) || value['orderRef'] === undefined) return false
  if (!('qrData' in value) || value['qrData'] === undefined) return false
  if (!('type' in value) || value['type'] === undefined) return false
  return true
}

export function VerificationStartOneOf1FromJSON(json: any): VerificationStartOneOf1 {
  return VerificationStartOneOf1FromJSONTyped(json, false)
}

export function VerificationStartOneOf1FromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): VerificationStartOneOf1 {
  if (json == null) {
    return json
  }
  return {
    autoStartUrl: json['autoStartUrl'] == null ? undefined : json['autoStartUrl'],
    orderRef: json['orderRef'],
    qrData: json['qrData'],
    type: json['type'],
  }
}

export function VerificationStartOneOf1ToJSON(json: any): VerificationStartOneOf1 {
  return VerificationStartOneOf1ToJSONTyped(json, false)
}

export function VerificationStartOneOf1ToJSONTyped(
  value?: VerificationStartOneOf1 | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    autoStartUrl: value['autoStartUrl'],
    orderRef: value['orderRef'],
    qrData: value['qrData'],
    type: value['type'],
  }
}
