/* tslint:disable */
/* eslint-disable */
/**
 * OwlID Issuer Service
 * Identity verification and credential issuance
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { VerificationStartOneOf } from './VerificationStartOneOf.js'
import {
  instanceOfVerificationStartOneOf,
  VerificationStartOneOfFromJSON,
  VerificationStartOneOfFromJSONTyped,
  VerificationStartOneOfToJSON,
} from './VerificationStartOneOf.js'
import type { VerificationStartOneOf1 } from './VerificationStartOneOf1.js'
import {
  instanceOfVerificationStartOneOf1,
  VerificationStartOneOf1FromJSON,
  VerificationStartOneOf1FromJSONTyped,
  VerificationStartOneOf1ToJSON,
} from './VerificationStartOneOf1.js'
import type { VerificationStartOneOf2 } from './VerificationStartOneOf2.js'
import {
  instanceOfVerificationStartOneOf2,
  VerificationStartOneOf2FromJSON,
  VerificationStartOneOf2FromJSONTyped,
  VerificationStartOneOf2ToJSON,
} from './VerificationStartOneOf2.js'
import type { VerificationStartOneOf3 } from './VerificationStartOneOf3.js'
import {
  instanceOfVerificationStartOneOf3,
  VerificationStartOneOf3FromJSON,
  VerificationStartOneOf3FromJSONTyped,
  VerificationStartOneOf3ToJSON,
} from './VerificationStartOneOf3.js'

/**
 * @type VerificationStart
 * Result of starting a verification session
 *
 * Different flow types return different data to the frontend
 * @export
 */
export type VerificationStart =
  | VerificationStartOneOf
  | VerificationStartOneOf1
  | VerificationStartOneOf2
  | VerificationStartOneOf3

export function VerificationStartFromJSON(json: any): VerificationStart {
  return VerificationStartFromJSONTyped(json, false)
}

export function VerificationStartFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): VerificationStart {
  if (json == null) {
    return json
  }
  if (instanceOfVerificationStartOneOf(json)) {
    return VerificationStartOneOfFromJSONTyped(json, true)
  }
  if (instanceOfVerificationStartOneOf1(json)) {
    return VerificationStartOneOf1FromJSONTyped(json, true)
  }
  if (instanceOfVerificationStartOneOf2(json)) {
    return VerificationStartOneOf2FromJSONTyped(json, true)
  }
  if (instanceOfVerificationStartOneOf3(json)) {
    return VerificationStartOneOf3FromJSONTyped(json, true)
  }

  return {} as any
}

export function VerificationStartToJSON(json: any): any {
  return VerificationStartToJSONTyped(json, false)
}

export function VerificationStartToJSONTyped(
  value?: VerificationStart | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  if (instanceOfVerificationStartOneOf(value)) {
    return VerificationStartOneOfToJSON(value as VerificationStartOneOf)
  }
  if (instanceOfVerificationStartOneOf1(value)) {
    return VerificationStartOneOf1ToJSON(value as VerificationStartOneOf1)
  }
  if (instanceOfVerificationStartOneOf2(value)) {
    return VerificationStartOneOf2ToJSON(value as VerificationStartOneOf2)
  }
  if (instanceOfVerificationStartOneOf3(value)) {
    return VerificationStartOneOf3ToJSON(value as VerificationStartOneOf3)
  }

  return {}
}
