/* tslint:disable */
/* eslint-disable */
/**
 * OwlID Issuer Service
 * Identity verification and credential issuance
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js'
/**
 *
 * @export
 * @interface VerificationWarningResponse
 */
export interface VerificationWarningResponse {
  /**
   *
   * @type {string}
   * @memberof VerificationWarningResponse
   */
  code: string
  /**
   *
   * @type {string}
   * @memberof VerificationWarningResponse
   */
  longDescription?: string | null
  /**
   *
   * @type {string}
   * @memberof VerificationWarningResponse
   */
  risk?: string | null
  /**
   *
   * @type {string}
   * @memberof VerificationWarningResponse
   */
  shortDescription: string
}

/**
 * Check if a given object implements the VerificationWarningResponse interface.
 */
export function instanceOfVerificationWarningResponse(
  value: object,
): value is VerificationWarningResponse {
  if (!('code' in value) || value['code'] === undefined) return false
  if (!('shortDescription' in value) || value['shortDescription'] === undefined) return false
  return true
}

export function VerificationWarningResponseFromJSON(json: any): VerificationWarningResponse {
  return VerificationWarningResponseFromJSONTyped(json, false)
}

export function VerificationWarningResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): VerificationWarningResponse {
  if (json == null) {
    return json
  }
  return {
    code: json['code'],
    longDescription: json['longDescription'] == null ? undefined : json['longDescription'],
    risk: json['risk'] == null ? undefined : json['risk'],
    shortDescription: json['shortDescription'],
  }
}

export function VerificationWarningResponseToJSON(json: any): VerificationWarningResponse {
  return VerificationWarningResponseToJSONTyped(json, false)
}

export function VerificationWarningResponseToJSONTyped(
  value?: VerificationWarningResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    code: value['code'],
    longDescription: value['longDescription'],
    risk: value['risk'],
    shortDescription: value['shortDescription'],
  }
}
