/* tslint:disable */
/* eslint-disable */
/**
 * OwlID Issuer Service
 * Identity verification and credential issuance
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js'
import type { VerificationLevel } from './VerificationLevel.js'
import {
  VerificationLevelFromJSON,
  VerificationLevelFromJSONTyped,
  VerificationLevelToJSON,
  VerificationLevelToJSONTyped,
} from './VerificationLevel.js'

/**
 * Verified identity claims from the IdP
 *
 * This represents what a real IdP like DigiD or BankID would return
 * after verifying a user's identity against government databases.
 * @export
 * @interface VerifiedIdentityClaims
 */
export interface VerifiedIdentityClaims {
  /**
   *
   * @type {string}
   * @memberof VerifiedIdentityClaims
   */
  city: string
  /**
   *
   * @type {string}
   * @memberof VerifiedIdentityClaims
   */
  country: string
  /**
   *
   * @type {Date}
   * @memberof VerifiedIdentityClaims
   */
  dateOfBirth: Date
  /**
   * Document expiration date
   * @type {Date}
   * @memberof VerifiedIdentityClaims
   */
  documentExpiry?: Date | null
  /**
   * Document issue date
   * @type {Date}
   * @memberof VerifiedIdentityClaims
   */
  documentIssueDate?: Date | null
  /**
   * Document number (generic - may be passport, ID, or driver's license)
   * @type {string}
   * @memberof VerifiedIdentityClaims
   */
  documentNumber?: string | null
  /**
   * Type of document used for verification (Passport, ID Card, Driver's License)
   * @type {string}
   * @memberof VerifiedIdentityClaims
   */
  documentType?: string | null
  /**
   *
   * @type {string}
   * @memberof VerifiedIdentityClaims
   */
  driversLicense?: string | null
  /**
   *
   * @type {string}
   * @memberof VerifiedIdentityClaims
   */
  firstName: string
  /**
   *
   * @type {string}
   * @memberof VerifiedIdentityClaims
   */
  gender?: string | null
  /**
   *
   * @type {boolean}
   * @memberof VerifiedIdentityClaims
   */
  isEuCitizen: boolean
  /**
   * Boolean proofs derived from the raw data - the key privacy feature
   * @type {boolean}
   * @memberof VerifiedIdentityClaims
   */
  isOver18: boolean
  /**
   *
   * @type {boolean}
   * @memberof VerifiedIdentityClaims
   */
  isOver21: boolean
  /**
   *
   * @type {boolean}
   * @memberof VerifiedIdentityClaims
   */
  isOver65: boolean
  /**
   *
   * @type {boolean}
   * @memberof VerifiedIdentityClaims
   */
  isResident: boolean
  /**
   * Country that issued the document (ISO 3166-1 alpha-2)
   * @type {string}
   * @memberof VerifiedIdentityClaims
   */
  issuingCountry?: string | null
  /**
   *
   * @type {string}
   * @memberof VerifiedIdentityClaims
   */
  lastName: string
  /**
   * National ID number (BSN, SSN, etc.)
   * @type {string}
   * @memberof VerifiedIdentityClaims
   */
  nationalId: string
  /**
   *
   * @type {string}
   * @memberof VerifiedIdentityClaims
   */
  nationality: string
  /**
   *
   * @type {string}
   * @memberof VerifiedIdentityClaims
   */
  passportNumber?: string | null
  /**
   *
   * @type {string}
   * @memberof VerifiedIdentityClaims
   */
  placeOfBirth: string
  /**
   * Portrait image from document/selfie (base64)
   * Returned in API response but excluded from Merkle tree for privacy
   * @type {string}
   * @memberof VerifiedIdentityClaims
   */
  portraitImage?: string | null
  /**
   *
   * @type {string}
   * @memberof VerifiedIdentityClaims
   */
  postalCode: string
  /**
   *
   * @type {string}
   * @memberof VerifiedIdentityClaims
   */
  providerId: string
  /**
   *
   * @type {string}
   * @memberof VerifiedIdentityClaims
   */
  streetAddress: string
  /**
   *
   * @type {string}
   * @memberof VerifiedIdentityClaims
   */
  taxId?: string | null
  /**
   *
   * @type {VerificationLevel}
   * @memberof VerifiedIdentityClaims
   */
  verificationLevel: VerificationLevel
  /**
   * Method used for verification (e.g., "document_scan", "bank_login", "in_person")
   * @type {string}
   * @memberof VerifiedIdentityClaims
   */
  verificationMethod: string
  /**
   *
   * @type {Date}
   * @memberof VerifiedIdentityClaims
   */
  verifiedAt: Date
}

/**
 * Check if a given object implements the VerifiedIdentityClaims interface.
 */
export function instanceOfVerifiedIdentityClaims(value: object): value is VerifiedIdentityClaims {
  if (!('city' in value) || value['city'] === undefined) return false
  if (!('country' in value) || value['country'] === undefined) return false
  if (!('dateOfBirth' in value) || value['dateOfBirth'] === undefined) return false
  if (!('firstName' in value) || value['firstName'] === undefined) return false
  if (!('isEuCitizen' in value) || value['isEuCitizen'] === undefined) return false
  if (!('isOver18' in value) || value['isOver18'] === undefined) return false
  if (!('isOver21' in value) || value['isOver21'] === undefined) return false
  if (!('isOver65' in value) || value['isOver65'] === undefined) return false
  if (!('isResident' in value) || value['isResident'] === undefined) return false
  if (!('lastName' in value) || value['lastName'] === undefined) return false
  if (!('nationalId' in value) || value['nationalId'] === undefined) return false
  if (!('nationality' in value) || value['nationality'] === undefined) return false
  if (!('placeOfBirth' in value) || value['placeOfBirth'] === undefined) return false
  if (!('postalCode' in value) || value['postalCode'] === undefined) return false
  if (!('providerId' in value) || value['providerId'] === undefined) return false
  if (!('streetAddress' in value) || value['streetAddress'] === undefined) return false
  if (!('verificationLevel' in value) || value['verificationLevel'] === undefined) return false
  if (!('verificationMethod' in value) || value['verificationMethod'] === undefined) return false
  if (!('verifiedAt' in value) || value['verifiedAt'] === undefined) return false
  return true
}

export function VerifiedIdentityClaimsFromJSON(json: any): VerifiedIdentityClaims {
  return VerifiedIdentityClaimsFromJSONTyped(json, false)
}

export function VerifiedIdentityClaimsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): VerifiedIdentityClaims {
  if (json == null) {
    return json
  }
  return {
    city: json['city'],
    country: json['country'],
    dateOfBirth: new Date(json['dateOfBirth']),
    documentExpiry: json['documentExpiry'] == null ? undefined : new Date(json['documentExpiry']),
    documentIssueDate:
      json['documentIssueDate'] == null ? undefined : new Date(json['documentIssueDate']),
    documentNumber: json['documentNumber'] == null ? undefined : json['documentNumber'],
    documentType: json['documentType'] == null ? undefined : json['documentType'],
    driversLicense: json['driversLicense'] == null ? undefined : json['driversLicense'],
    firstName: json['firstName'],
    gender: json['gender'] == null ? undefined : json['gender'],
    isEuCitizen: json['isEuCitizen'],
    isOver18: json['isOver18'],
    isOver21: json['isOver21'],
    isOver65: json['isOver65'],
    isResident: json['isResident'],
    issuingCountry: json['issuingCountry'] == null ? undefined : json['issuingCountry'],
    lastName: json['lastName'],
    nationalId: json['nationalId'],
    nationality: json['nationality'],
    passportNumber: json['passportNumber'] == null ? undefined : json['passportNumber'],
    placeOfBirth: json['placeOfBirth'],
    portraitImage: json['portraitImage'] == null ? undefined : json['portraitImage'],
    postalCode: json['postalCode'],
    providerId: json['providerId'],
    streetAddress: json['streetAddress'],
    taxId: json['taxId'] == null ? undefined : json['taxId'],
    verificationLevel: VerificationLevelFromJSON(json['verificationLevel']),
    verificationMethod: json['verificationMethod'],
    verifiedAt: new Date(json['verifiedAt']),
  }
}

export function VerifiedIdentityClaimsToJSON(json: any): VerifiedIdentityClaims {
  return VerifiedIdentityClaimsToJSONTyped(json, false)
}

export function VerifiedIdentityClaimsToJSONTyped(
  value?: VerifiedIdentityClaims | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    city: value['city'],
    country: value['country'],
    dateOfBirth: value['dateOfBirth'].toISOString().substring(0, 10),
    documentExpiry:
      value['documentExpiry'] == null
        ? undefined
        : (value['documentExpiry'] as any).toISOString().substring(0, 10),
    documentIssueDate:
      value['documentIssueDate'] == null
        ? undefined
        : (value['documentIssueDate'] as any).toISOString().substring(0, 10),
    documentNumber: value['documentNumber'],
    documentType: value['documentType'],
    driversLicense: value['driversLicense'],
    firstName: value['firstName'],
    gender: value['gender'],
    isEuCitizen: value['isEuCitizen'],
    isOver18: value['isOver18'],
    isOver21: value['isOver21'],
    isOver65: value['isOver65'],
    isResident: value['isResident'],
    issuingCountry: value['issuingCountry'],
    lastName: value['lastName'],
    nationalId: value['nationalId'],
    nationality: value['nationality'],
    passportNumber: value['passportNumber'],
    placeOfBirth: value['placeOfBirth'],
    portraitImage: value['portraitImage'],
    postalCode: value['postalCode'],
    providerId: value['providerId'],
    streetAddress: value['streetAddress'],
    taxId: value['taxId'],
    verificationLevel: VerificationLevelToJSON(value['verificationLevel']),
    verificationMethod: value['verificationMethod'],
    verifiedAt: value['verifiedAt'].toISOString(),
  }
}
