/* tslint:disable */
/* eslint-disable */
/**
 * OwlID Issuer Service
 * Identity verification and credential issuance
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js'
import type { FormConfig } from './FormConfig.js'
import {
  FormConfigFromJSON,
  FormConfigFromJSONTyped,
  FormConfigToJSON,
  FormConfigToJSONTyped,
} from './FormConfig.js'

/**
 * Show form to user (mock/test providers)
 * @export
 * @interface VerificationStartOneOf3
 */
export interface VerificationStartOneOf3 {
  /**
   * Configuration for the form fields
   * @type {FormConfig}
   * @memberof VerificationStartOneOf3
   */
  config: FormConfig
  /**
   *
   * @type {string}
   * @memberof VerificationStartOneOf3
   */
  type: VerificationStartOneOf3TypeEnum
}

/**
 * @export
 * @enum {string}
 */
export enum VerificationStartOneOf3TypeEnum {
  form = 'form',
}

/**
 * Check if a given object implements the VerificationStartOneOf3 interface.
 */
export function instanceOfVerificationStartOneOf3(value: object): value is VerificationStartOneOf3 {
  if (!('config' in value) || value['config'] === undefined) return false
  if (!('type' in value) || value['type'] === undefined) return false
  return true
}

export function VerificationStartOneOf3FromJSON(json: any): VerificationStartOneOf3 {
  return VerificationStartOneOf3FromJSONTyped(json, false)
}

export function VerificationStartOneOf3FromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): VerificationStartOneOf3 {
  if (json == null) {
    return json
  }
  return {
    config: FormConfigFromJSON(json['config']),
    type: json['type'],
  }
}

export function VerificationStartOneOf3ToJSON(json: any): VerificationStartOneOf3 {
  return VerificationStartOneOf3ToJSONTyped(json, false)
}

export function VerificationStartOneOf3ToJSONTyped(
  value?: VerificationStartOneOf3 | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    config: FormConfigToJSON(value['config']),
    type: value['type'],
  }
}
