/* tslint:disable */
/* eslint-disable */
/**
 * OwlID Verification Service
 * Token verification, trusted issuer management, and credential revocation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js'
/**
 * Response for adding a trusted issuer
 * @export
 * @interface AddTrustedIssuerResponse
 */
export interface AddTrustedIssuerResponse {
  /**
   *
   * @type {string}
   * @memberof AddTrustedIssuerResponse
   */
  message: string
  /**
   *
   * @type {boolean}
   * @memberof AddTrustedIssuerResponse
   */
  success: boolean
}

/**
 * Check if a given object implements the AddTrustedIssuerResponse interface.
 */
export function instanceOfAddTrustedIssuerResponse(
  value: object,
): value is AddTrustedIssuerResponse {
  if (!('message' in value) || value['message'] === undefined) return false
  if (!('success' in value) || value['success'] === undefined) return false
  return true
}

export function AddTrustedIssuerResponseFromJSON(json: any): AddTrustedIssuerResponse {
  return AddTrustedIssuerResponseFromJSONTyped(json, false)
}

export function AddTrustedIssuerResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AddTrustedIssuerResponse {
  if (json == null) {
    return json
  }
  return {
    message: json['message'],
    success: json['success'],
  }
}

export function AddTrustedIssuerResponseToJSON(json: any): AddTrustedIssuerResponse {
  return AddTrustedIssuerResponseToJSONTyped(json, false)
}

export function AddTrustedIssuerResponseToJSONTyped(
  value?: AddTrustedIssuerResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    message: value['message'],
    success: value['success'],
  }
}
