/* tslint:disable */
/* eslint-disable */
/**
 * OwlID Verification Service
 * SD-JWT VC presentation verification, trusted issuer management, and credential revocation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js'
/**
 *
 * @export
 * @interface AdminUserInfo
 */
export interface AdminUserInfo {
  /**
   *
   * @type {string}
   * @memberof AdminUserInfo
   */
  createdAt: string
  /**
   *
   * @type {string}
   * @memberof AdminUserInfo
   */
  id: string
  /**
   *
   * @type {boolean}
   * @memberof AdminUserInfo
   */
  isActive: boolean
  /**
   *
   * @type {string}
   * @memberof AdminUserInfo
   */
  lastLoginAt?: string | null
  /**
   *
   * @type {string}
   * @memberof AdminUserInfo
   */
  username: string
}

/**
 * Check if a given object implements the AdminUserInfo interface.
 */
export function instanceOfAdminUserInfo(value: object): value is AdminUserInfo {
  if (!('createdAt' in value) || value['createdAt'] === undefined) return false
  if (!('id' in value) || value['id'] === undefined) return false
  if (!('isActive' in value) || value['isActive'] === undefined) return false
  if (!('username' in value) || value['username'] === undefined) return false
  return true
}

export function AdminUserInfoFromJSON(json: any): AdminUserInfo {
  return AdminUserInfoFromJSONTyped(json, false)
}

export function AdminUserInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminUserInfo {
  if (json == null) {
    return json
  }
  return {
    createdAt: json['createdAt'],
    id: json['id'],
    isActive: json['isActive'],
    lastLoginAt: json['lastLoginAt'] == null ? undefined : json['lastLoginAt'],
    username: json['username'],
  }
}

export function AdminUserInfoToJSON(json: any): AdminUserInfo {
  return AdminUserInfoToJSONTyped(json, false)
}

export function AdminUserInfoToJSONTyped(
  value?: AdminUserInfo | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    createdAt: value['createdAt'],
    id: value['id'],
    isActive: value['isActive'],
    lastLoginAt: value['lastLoginAt'],
    username: value['username'],
  }
}
