/* tslint:disable */
/* eslint-disable */
/**
 * OwlID Verification Service
 * SD-JWT VC presentation verification, trusted issuer management, and credential revocation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js'
/**
 *
 * @export
 * @interface AuditEventInfo
 */
export interface AuditEventInfo {
  /**
   *
   * @type {string}
   * @memberof AuditEventInfo
   */
  actor?: string | null
  /**
   *
   * @type {string}
   * @memberof AuditEventInfo
   */
  entityId: string
  /**
   *
   * @type {string}
   * @memberof AuditEventInfo
   */
  entityType: string
  /**
   *
   * @type {string}
   * @memberof AuditEventInfo
   */
  eventType: string
  /**
   *
   * @type {string}
   * @memberof AuditEventInfo
   */
  id: string
  /**
   *
   * @type {object}
   * @memberof AuditEventInfo
   */
  metadata: object
  /**
   *
   * @type {string}
   * @memberof AuditEventInfo
   */
  occurredAt: string
}

/**
 * Check if a given object implements the AuditEventInfo interface.
 */
export function instanceOfAuditEventInfo(value: object): value is AuditEventInfo {
  if (!('entityId' in value) || value['entityId'] === undefined) return false
  if (!('entityType' in value) || value['entityType'] === undefined) return false
  if (!('eventType' in value) || value['eventType'] === undefined) return false
  if (!('id' in value) || value['id'] === undefined) return false
  if (!('metadata' in value) || value['metadata'] === undefined) return false
  if (!('occurredAt' in value) || value['occurredAt'] === undefined) return false
  return true
}

export function AuditEventInfoFromJSON(json: any): AuditEventInfo {
  return AuditEventInfoFromJSONTyped(json, false)
}

export function AuditEventInfoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AuditEventInfo {
  if (json == null) {
    return json
  }
  return {
    actor: json['actor'] == null ? undefined : json['actor'],
    entityId: json['entityId'],
    entityType: json['entityType'],
    eventType: json['eventType'],
    id: json['id'],
    metadata: json['metadata'],
    occurredAt: json['occurredAt'],
  }
}

export function AuditEventInfoToJSON(json: any): AuditEventInfo {
  return AuditEventInfoToJSONTyped(json, false)
}

export function AuditEventInfoToJSONTyped(
  value?: AuditEventInfo | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    actor: value['actor'],
    entityId: value['entityId'],
    entityType: value['entityType'],
    eventType: value['eventType'],
    id: value['id'],
    metadata: value['metadata'],
    occurredAt: value['occurredAt'],
  }
}
