/* tslint:disable */
/* eslint-disable */
/**
 * OwlID Verification Service
 * Token verification, trusted issuer management, and credential revocation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js'
/**
 *
 * @export
 * @interface ChangePasswordResponse
 */
export interface ChangePasswordResponse {
  /**
   *
   * @type {string}
   * @memberof ChangePasswordResponse
   */
  username: string
}

/**
 * Check if a given object implements the ChangePasswordResponse interface.
 */
export function instanceOfChangePasswordResponse(value: object): value is ChangePasswordResponse {
  if (!('username' in value) || value['username'] === undefined) return false
  return true
}

export function ChangePasswordResponseFromJSON(json: any): ChangePasswordResponse {
  return ChangePasswordResponseFromJSONTyped(json, false)
}

export function ChangePasswordResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ChangePasswordResponse {
  if (json == null) {
    return json
  }
  return {
    username: json['username'],
  }
}

export function ChangePasswordResponseToJSON(json: any): ChangePasswordResponse {
  return ChangePasswordResponseToJSONTyped(json, false)
}

export function ChangePasswordResponseToJSONTyped(
  value?: ChangePasswordResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    username: value['username'],
  }
}
