/* tslint:disable */
/* eslint-disable */
/**
 * OwlID Verification Service
 * SD-JWT VC presentation verification, trusted issuer management, and credential revocation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js'
/**
 *
 * @export
 * @interface CheckPredicateResponse
 */
export interface CheckPredicateResponse {
  /**
   * Recomputed attestation key (hex) — bound to the credential_id.
   * @type {string}
   * @memberof CheckPredicateResponse
   */
  attestKey: string
  /**
   * True iff the key is in the SSE-mirrored on-chain attestation set.
   * @type {boolean}
   * @memberof CheckPredicateResponse
   */
  attested: boolean
  /**
   *
   * @type {string}
   * @memberof CheckPredicateResponse
   */
  predicate: string
}

/**
 * Check if a given object implements the CheckPredicateResponse interface.
 */
export function instanceOfCheckPredicateResponse(value: object): value is CheckPredicateResponse {
  if (!('attestKey' in value) || value['attestKey'] === undefined) return false
  if (!('attested' in value) || value['attested'] === undefined) return false
  if (!('predicate' in value) || value['predicate'] === undefined) return false
  return true
}

export function CheckPredicateResponseFromJSON(json: any): CheckPredicateResponse {
  return CheckPredicateResponseFromJSONTyped(json, false)
}

export function CheckPredicateResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CheckPredicateResponse {
  if (json == null) {
    return json
  }
  return {
    attestKey: json['attestKey'],
    attested: json['attested'],
    predicate: json['predicate'],
  }
}

export function CheckPredicateResponseToJSON(json: any): CheckPredicateResponse {
  return CheckPredicateResponseToJSONTyped(json, false)
}

export function CheckPredicateResponseToJSONTyped(
  value?: CheckPredicateResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    attestKey: value['attestKey'],
    attested: value['attested'],
    predicate: value['predicate'],
  }
}
