/* tslint:disable */
/* eslint-disable */
/**
 * OwlID Verification Service
 * SD-JWT VC presentation verification, trusted issuer management, and credential revocation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js'
/**
 * Check revocation status
 * @export
 * @interface CheckRevocationRequest
 */
export interface CheckRevocationRequest {
  /**
   *
   * @type {string}
   * @memberof CheckRevocationRequest
   */
  credentialId: string
}

/**
 * Check if a given object implements the CheckRevocationRequest interface.
 */
export function instanceOfCheckRevocationRequest(value: object): value is CheckRevocationRequest {
  if (!('credentialId' in value) || value['credentialId'] === undefined) return false
  return true
}

export function CheckRevocationRequestFromJSON(json: any): CheckRevocationRequest {
  return CheckRevocationRequestFromJSONTyped(json, false)
}

export function CheckRevocationRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CheckRevocationRequest {
  if (json == null) {
    return json
  }
  return {
    credentialId: json['credentialId'],
  }
}

export function CheckRevocationRequestToJSON(json: any): CheckRevocationRequest {
  return CheckRevocationRequestToJSONTyped(json, false)
}

export function CheckRevocationRequestToJSONTyped(
  value?: CheckRevocationRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    credentialId: value['credentialId'],
  }
}
