/* tslint:disable */
/* eslint-disable */
/**
 * OwlID Verification Service
 * Token verification, trusted issuer management, and credential revocation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js'
/**
 *
 * @export
 * @interface CheckRevocationResponse
 */
export interface CheckRevocationResponse {
  /**
   *
   * @type {string}
   * @memberof CheckRevocationResponse
   */
  credentialId: string
  /**
   *
   * @type {string}
   * @memberof CheckRevocationResponse
   */
  status: string
}

/**
 * Check if a given object implements the CheckRevocationResponse interface.
 */
export function instanceOfCheckRevocationResponse(value: object): value is CheckRevocationResponse {
  if (!('credentialId' in value) || value['credentialId'] === undefined) return false
  if (!('status' in value) || value['status'] === undefined) return false
  return true
}

export function CheckRevocationResponseFromJSON(json: any): CheckRevocationResponse {
  return CheckRevocationResponseFromJSONTyped(json, false)
}

export function CheckRevocationResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CheckRevocationResponse {
  if (json == null) {
    return json
  }
  return {
    credentialId: json['credentialId'],
    status: json['status'],
  }
}

export function CheckRevocationResponseToJSON(json: any): CheckRevocationResponse {
  return CheckRevocationResponseToJSONTyped(json, false)
}

export function CheckRevocationResponseToJSONTyped(
  value?: CheckRevocationResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    credentialId: value['credentialId'],
    status: value['status'],
  }
}
