/* tslint:disable */
/* eslint-disable */
/**
 * OwlID Verification Service
 * SD-JWT VC presentation verification, trusted issuer management, and credential revocation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js'
/**
 *
 * @export
 * @interface CircuitDataset
 */
export interface CircuitDataset {
  /**
   *
   * @type {Array<string>}
   * @memberof CircuitDataset
   */
  items: Array<string>
  /**
   *
   * @type {string}
   * @memberof CircuitDataset
   */
  name: string
  /**
   *
   * @type {number}
   * @memberof CircuitDataset
   */
  version: number
}

/**
 * Check if a given object implements the CircuitDataset interface.
 */
export function instanceOfCircuitDataset(value: object): value is CircuitDataset {
  if (!('items' in value) || value['items'] === undefined) return false
  if (!('name' in value) || value['name'] === undefined) return false
  if (!('version' in value) || value['version'] === undefined) return false
  return true
}

export function CircuitDatasetFromJSON(json: any): CircuitDataset {
  return CircuitDatasetFromJSONTyped(json, false)
}

export function CircuitDatasetFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CircuitDataset {
  if (json == null) {
    return json
  }
  return {
    items: json['items'],
    name: json['name'],
    version: json['version'],
  }
}

export function CircuitDatasetToJSON(json: any): CircuitDataset {
  return CircuitDatasetToJSONTyped(json, false)
}

export function CircuitDatasetToJSONTyped(
  value?: CircuitDataset | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    items: value['items'],
    name: value['name'],
    version: value['version'],
  }
}
