/* tslint:disable */
/* eslint-disable */
/**
 * OwlID Verification Service
 * Token verification, trusted issuer management, and credential revocation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js'
/**
 *
 * @export
 * @interface CircuitDatasetInfo
 */
export interface CircuitDatasetInfo {
  /**
   *
   * @type {string}
   * @memberof CircuitDatasetInfo
   */
  name: string
  /**
   *
   * @type {number}
   * @memberof CircuitDatasetInfo
   */
  version: number
}

/**
 * Check if a given object implements the CircuitDatasetInfo interface.
 */
export function instanceOfCircuitDatasetInfo(value: object): value is CircuitDatasetInfo {
  if (!('name' in value) || value['name'] === undefined) return false
  if (!('version' in value) || value['version'] === undefined) return false
  return true
}

export function CircuitDatasetInfoFromJSON(json: any): CircuitDatasetInfo {
  return CircuitDatasetInfoFromJSONTyped(json, false)
}

export function CircuitDatasetInfoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CircuitDatasetInfo {
  if (json == null) {
    return json
  }
  return {
    name: json['name'],
    version: json['version'],
  }
}

export function CircuitDatasetInfoToJSON(json: any): CircuitDatasetInfo {
  return CircuitDatasetInfoToJSONTyped(json, false)
}

export function CircuitDatasetInfoToJSONTyped(
  value?: CircuitDatasetInfo | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    name: value['name'],
    version: value['version'],
  }
}
