/* tslint:disable */
/* eslint-disable */
/**
 * OwlID Verification Service
 * SD-JWT VC presentation verification, trusted issuer management, and credential revocation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js'
/**
 *
 * @export
 * @interface CreateAdminUserRequest
 */
export interface CreateAdminUserRequest {
  /**
   *
   * @type {string}
   * @memberof CreateAdminUserRequest
   */
  password: string
  /**
   *
   * @type {string}
   * @memberof CreateAdminUserRequest
   */
  username: string
}

/**
 * Check if a given object implements the CreateAdminUserRequest interface.
 */
export function instanceOfCreateAdminUserRequest(value: object): value is CreateAdminUserRequest {
  if (!('password' in value) || value['password'] === undefined) return false
  if (!('username' in value) || value['username'] === undefined) return false
  return true
}

export function CreateAdminUserRequestFromJSON(json: any): CreateAdminUserRequest {
  return CreateAdminUserRequestFromJSONTyped(json, false)
}

export function CreateAdminUserRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreateAdminUserRequest {
  if (json == null) {
    return json
  }
  return {
    password: json['password'],
    username: json['username'],
  }
}

export function CreateAdminUserRequestToJSON(json: any): CreateAdminUserRequest {
  return CreateAdminUserRequestToJSONTyped(json, false)
}

export function CreateAdminUserRequestToJSONTyped(
  value?: CreateAdminUserRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    password: value['password'],
    username: value['username'],
  }
}
