/* tslint:disable */
/* eslint-disable */
/**
 * OwlID Verification Service
 * Token verification, trusted issuer management, and credential revocation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js'
import type { KeyType } from './KeyType.js'
import {
  KeyTypeFromJSON,
  KeyTypeFromJSONTyped,
  KeyTypeToJSON,
  KeyTypeToJSONTyped,
} from './KeyType.js'
import type { Environment } from './Environment.js'
import {
  EnvironmentFromJSON,
  EnvironmentFromJSONTyped,
  EnvironmentToJSON,
  EnvironmentToJSONTyped,
} from './Environment.js'

/**
 *
 * @export
 * @interface CreateApiKeyRequest
 */
export interface CreateApiKeyRequest {
  /**
   *
   * @type {string}
   * @memberof CreateApiKeyRequest
   */
  description?: string | null
  /**
   *
   * @type {Environment}
   * @memberof CreateApiKeyRequest
   */
  environment?: Environment
  /**
   *
   * @type {KeyType}
   * @memberof CreateApiKeyRequest
   */
  keyType?: KeyType
  /**
   *
   * @type {string}
   * @memberof CreateApiKeyRequest
   */
  name: string
  /**
   *
   * @type {Array<string>}
   * @memberof CreateApiKeyRequest
   */
  permissions: Array<string>
}

/**
 * Check if a given object implements the CreateApiKeyRequest interface.
 */
export function instanceOfCreateApiKeyRequest(value: object): value is CreateApiKeyRequest {
  if (!('name' in value) || value['name'] === undefined) return false
  if (!('permissions' in value) || value['permissions'] === undefined) return false
  return true
}

export function CreateApiKeyRequestFromJSON(json: any): CreateApiKeyRequest {
  return CreateApiKeyRequestFromJSONTyped(json, false)
}

export function CreateApiKeyRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreateApiKeyRequest {
  if (json == null) {
    return json
  }
  return {
    description: json['description'] == null ? undefined : json['description'],
    environment: json['environment'] == null ? undefined : EnvironmentFromJSON(json['environment']),
    keyType: json['keyType'] == null ? undefined : KeyTypeFromJSON(json['keyType']),
    name: json['name'],
    permissions: json['permissions'],
  }
}

export function CreateApiKeyRequestToJSON(json: any): CreateApiKeyRequest {
  return CreateApiKeyRequestToJSONTyped(json, false)
}

export function CreateApiKeyRequestToJSONTyped(
  value?: CreateApiKeyRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    description: value['description'],
    environment: EnvironmentToJSON(value['environment']),
    keyType: KeyTypeToJSON(value['keyType']),
    name: value['name'],
    permissions: value['permissions'],
  }
}
