/* tslint:disable */
/* eslint-disable */
/**
 * OwlID Verification Service
 * SD-JWT VC presentation verification, trusted issuer management, and credential revocation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js'
/**
 *
 * @export
 * @interface DcqlClaimQuery
 */
export interface DcqlClaimQuery {
  /**
   *
   * @type {string}
   * @memberof DcqlClaimQuery
   */
  id?: string | null
  /**
   * Claims path pointer (OpenID4VP 1.0 §7). String tokens only —
   * integer indices and wildcards are not exercised by OwlID's
   * flat SD-JWT VC claim set.
   * @type {Array<string>}
   * @memberof DcqlClaimQuery
   */
  path: Array<string>
  /**
   *
   * @type {Array<any>}
   * @memberof DcqlClaimQuery
   */
  values?: Array<any>
}

/**
 * Check if a given object implements the DcqlClaimQuery interface.
 */
export function instanceOfDcqlClaimQuery(value: object): value is DcqlClaimQuery {
  if (!('path' in value) || value['path'] === undefined) return false
  return true
}

export function DcqlClaimQueryFromJSON(json: any): DcqlClaimQuery {
  return DcqlClaimQueryFromJSONTyped(json, false)
}

export function DcqlClaimQueryFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): DcqlClaimQuery {
  if (json == null) {
    return json
  }
  return {
    id: json['id'] == null ? undefined : json['id'],
    path: json['path'],
    values: json['values'] == null ? undefined : json['values'],
  }
}

export function DcqlClaimQueryToJSON(json: any): DcqlClaimQuery {
  return DcqlClaimQueryToJSONTyped(json, false)
}

export function DcqlClaimQueryToJSONTyped(
  value?: DcqlClaimQuery | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    id: value['id'],
    path: value['path'],
    values: value['values'],
  }
}
