/* tslint:disable */
/* eslint-disable */
/**
 * OwlID Verification Service
 * SD-JWT VC presentation verification, trusted issuer management, and credential revocation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js'
import type { OwlPredicate } from './OwlPredicate.js'
import {
  OwlPredicateFromJSON,
  OwlPredicateFromJSONTyped,
  OwlPredicateToJSON,
  OwlPredicateToJSONTyped,
} from './OwlPredicate.js'
import type { DcqlClaimQuery } from './DcqlClaimQuery.js'
import {
  DcqlClaimQueryFromJSON,
  DcqlClaimQueryFromJSONTyped,
  DcqlClaimQueryToJSON,
  DcqlClaimQueryToJSONTyped,
} from './DcqlClaimQuery.js'
import type { DcqlMeta } from './DcqlMeta.js'
import {
  DcqlMetaFromJSON,
  DcqlMetaFromJSONTyped,
  DcqlMetaToJSON,
  DcqlMetaToJSONTyped,
} from './DcqlMeta.js'

/**
 *
 * @export
 * @interface DcqlCredentialQuery
 */
export interface DcqlCredentialQuery {
  /**
   *
   * @type {Array<DcqlClaimQuery>}
   * @memberof DcqlCredentialQuery
   */
  claims?: Array<DcqlClaimQuery>
  /**
   * Credential format identifier. OwlID accepts `dc+sd-jwt` only.
   * @type {string}
   * @memberof DcqlCredentialQuery
   */
  format: string
  /**
   *
   * @type {string}
   * @memberof DcqlCredentialQuery
   */
  id: string
  /**
   *
   * @type {DcqlMeta}
   * @memberof DcqlCredentialQuery
   */
  meta?: DcqlMeta | null
  /**
   * May this query yield more than one credential. Default false.
   * @type {boolean}
   * @memberof DcqlCredentialQuery
   */
  multiple?: boolean | null
  /**
   * OwlID extension under OID4VP §6 "MUST ignore unknown properties":
   * the per-credential predicate dispatch the wallet honours. When
   * present, the wallet substitutes a Midnight on-chain attestation
   * check for the §6.4.1 disclosure obligation, and `claims` is left
   * empty so spec-strict wallets treat the query as "no claims
   * requested". Spec-strict (non-OwlID) wallets ignore this field
   * per §6's closing note.
   * @type {OwlPredicate}
   * @memberof DcqlCredentialQuery
   */
  owlPredicate?: OwlPredicate | null
  /**
   * Defaults to true (OpenID4VP 1.0 §6.1).
   * @type {boolean}
   * @memberof DcqlCredentialQuery
   */
  requireCryptographicHolderBinding?: boolean | null
}

/**
 * Check if a given object implements the DcqlCredentialQuery interface.
 */
export function instanceOfDcqlCredentialQuery(value: object): value is DcqlCredentialQuery {
  if (!('format' in value) || value['format'] === undefined) return false
  if (!('id' in value) || value['id'] === undefined) return false
  return true
}

export function DcqlCredentialQueryFromJSON(json: any): DcqlCredentialQuery {
  return DcqlCredentialQueryFromJSONTyped(json, false)
}

export function DcqlCredentialQueryFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): DcqlCredentialQuery {
  if (json == null) {
    return json
  }
  return {
    claims:
      json['claims'] == null
        ? undefined
        : (json['claims'] as Array<any>).map(DcqlClaimQueryFromJSON),
    format: json['format'],
    id: json['id'],
    meta: json['meta'] == null ? undefined : DcqlMetaFromJSON(json['meta']),
    multiple: json['multiple'] == null ? undefined : json['multiple'],
    owlPredicate:
      json['owl_predicate'] == null ? undefined : OwlPredicateFromJSON(json['owl_predicate']),
    requireCryptographicHolderBinding:
      json['require_cryptographic_holder_binding'] == null
        ? undefined
        : json['require_cryptographic_holder_binding'],
  }
}

export function DcqlCredentialQueryToJSON(json: any): DcqlCredentialQuery {
  return DcqlCredentialQueryToJSONTyped(json, false)
}

export function DcqlCredentialQueryToJSONTyped(
  value?: DcqlCredentialQuery | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    claims:
      value['claims'] == null
        ? undefined
        : (value['claims'] as Array<any>).map(DcqlClaimQueryToJSON),
    format: value['format'],
    id: value['id'],
    meta: DcqlMetaToJSON(value['meta']),
    multiple: value['multiple'],
    owl_predicate: OwlPredicateToJSON(value['owlPredicate']),
    require_cryptographic_holder_binding: value['requireCryptographicHolderBinding'],
  }
}
