/* tslint:disable */
/* eslint-disable */
/**
 * OwlID Verification Service
 * SD-JWT VC presentation verification, trusted issuer management, and credential revocation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js'
/**
 * Get metrics
 * Snapshot of the verification service's running metrics.
 * @export
 * @interface MetricsResponse
 */
export interface MetricsResponse {
  /**
   *
   * @type {number}
   * @memberof MetricsResponse
   */
  failedVerifications: number
  /**
   * Successful / total, rounded to two decimal places.
   * @type {number}
   * @memberof MetricsResponse
   */
  successRate: number
  /**
   *
   * @type {number}
   * @memberof MetricsResponse
   */
  successfulVerifications: number
  /**
   *
   * @type {number}
   * @memberof MetricsResponse
   */
  totalVerifications: number
}

/**
 * Check if a given object implements the MetricsResponse interface.
 */
export function instanceOfMetricsResponse(value: object): value is MetricsResponse {
  if (!('failedVerifications' in value) || value['failedVerifications'] === undefined) return false
  if (!('successRate' in value) || value['successRate'] === undefined) return false
  if (!('successfulVerifications' in value) || value['successfulVerifications'] === undefined)
    return false
  if (!('totalVerifications' in value) || value['totalVerifications'] === undefined) return false
  return true
}

export function MetricsResponseFromJSON(json: any): MetricsResponse {
  return MetricsResponseFromJSONTyped(json, false)
}

export function MetricsResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): MetricsResponse {
  if (json == null) {
    return json
  }
  return {
    failedVerifications: json['failedVerifications'],
    successRate: json['successRate'],
    successfulVerifications: json['successfulVerifications'],
    totalVerifications: json['totalVerifications'],
  }
}

export function MetricsResponseToJSON(json: any): MetricsResponse {
  return MetricsResponseToJSONTyped(json, false)
}

export function MetricsResponseToJSONTyped(
  value?: MetricsResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    failedVerifications: value['failedVerifications'],
    successRate: value['successRate'],
    successfulVerifications: value['successfulVerifications'],
    totalVerifications: value['totalVerifications'],
  }
}
