/* tslint:disable */
/* eslint-disable */
/**
 * OwlID Verification Service
 * SD-JWT VC presentation verification, trusted issuer management, and credential revocation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js'
import type { SidecarHealth } from './SidecarHealth.js'
import {
  SidecarHealthFromJSON,
  SidecarHealthFromJSONTyped,
  SidecarHealthToJSON,
  SidecarHealthToJSONTyped,
} from './SidecarHealth.js'

/**
 *
 * @export
 * @interface MidnightStatus
 */
export interface MidnightStatus {
  /**
   * Sidecar health probe outcome.
   * @type {SidecarHealth}
   * @memberof MidnightStatus
   */
  sidecar: SidecarHealth
  /**
   * Sidecar base URL the service is pointed at.
   * @type {string}
   * @memberof MidnightStatus
   */
  sidecarUrl: string
}

/**
 * Check if a given object implements the MidnightStatus interface.
 */
export function instanceOfMidnightStatus(value: object): value is MidnightStatus {
  if (!('sidecar' in value) || value['sidecar'] === undefined) return false
  if (!('sidecarUrl' in value) || value['sidecarUrl'] === undefined) return false
  return true
}

export function MidnightStatusFromJSON(json: any): MidnightStatus {
  return MidnightStatusFromJSONTyped(json, false)
}

export function MidnightStatusFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): MidnightStatus {
  if (json == null) {
    return json
  }
  return {
    sidecar: SidecarHealthFromJSON(json['sidecar']),
    sidecarUrl: json['sidecarUrl'],
  }
}

export function MidnightStatusToJSON(json: any): MidnightStatus {
  return MidnightStatusToJSONTyped(json, false)
}

export function MidnightStatusToJSONTyped(
  value?: MidnightStatus | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    sidecar: SidecarHealthToJSON(value['sidecar']),
    sidecarUrl: value['sidecarUrl'],
  }
}
