/* tslint:disable */
/* eslint-disable */
/**
 * OwlID Verification Service
 * SD-JWT VC presentation verification, trusted issuer management, and credential revocation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js'
/**
 * Holder is a unique human within `(epoch, app_id)` (each hex32).
 * @export
 * @interface OwlPredicateOneOf6
 */
export interface OwlPredicateOneOf6 {
  /**
   *
   * @type {string}
   * @memberof OwlPredicateOneOf6
   */
  appId: string
  /**
   *
   * @type {string}
   * @memberof OwlPredicateOneOf6
   */
  epoch: string
  /**
   *
   * @type {string}
   * @memberof OwlPredicateOneOf6
   */
  kind: OwlPredicateOneOf6KindEnum
}

/**
 * @export
 * @enum {string}
 */
export enum OwlPredicateOneOf6KindEnum {
  unique_personhood = 'unique_personhood',
}

/**
 * Check if a given object implements the OwlPredicateOneOf6 interface.
 */
export function instanceOfOwlPredicateOneOf6(value: object): value is OwlPredicateOneOf6 {
  if (!('appId' in value) || value['appId'] === undefined) return false
  if (!('epoch' in value) || value['epoch'] === undefined) return false
  if (!('kind' in value) || value['kind'] === undefined) return false
  return true
}

export function OwlPredicateOneOf6FromJSON(json: any): OwlPredicateOneOf6 {
  return OwlPredicateOneOf6FromJSONTyped(json, false)
}

export function OwlPredicateOneOf6FromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): OwlPredicateOneOf6 {
  if (json == null) {
    return json
  }
  return {
    appId: json['app_id'],
    epoch: json['epoch'],
    kind: json['kind'],
  }
}

export function OwlPredicateOneOf6ToJSON(json: any): OwlPredicateOneOf6 {
  return OwlPredicateOneOf6ToJSONTyped(json, false)
}

export function OwlPredicateOneOf6ToJSONTyped(
  value?: OwlPredicateOneOf6 | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    app_id: value['appId'],
    epoch: value['epoch'],
    kind: value['kind'],
  }
}
