/* tslint:disable */
/* eslint-disable */
/**
 * OwlID Verification Service
 * SD-JWT VC presentation verification, trusted issuer management, and credential revocation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js'
/**
 * Issuer attested the holder's email is verified.
 * @export
 * @interface OwlPredicateOneOf5
 */
export interface OwlPredicateOneOf5 {
  /**
   *
   * @type {string}
   * @memberof OwlPredicateOneOf5
   */
  kind: OwlPredicateOneOf5KindEnum
}

/**
 * @export
 * @enum {string}
 */
export enum OwlPredicateOneOf5KindEnum {
  email_verified = 'email_verified',
}

/**
 * Check if a given object implements the OwlPredicateOneOf5 interface.
 */
export function instanceOfOwlPredicateOneOf5(value: object): value is OwlPredicateOneOf5 {
  if (!('kind' in value) || value['kind'] === undefined) return false
  return true
}

export function OwlPredicateOneOf5FromJSON(json: any): OwlPredicateOneOf5 {
  return OwlPredicateOneOf5FromJSONTyped(json, false)
}

export function OwlPredicateOneOf5FromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): OwlPredicateOneOf5 {
  if (json == null) {
    return json
  }
  return {
    kind: json['kind'],
  }
}

export function OwlPredicateOneOf5ToJSON(json: any): OwlPredicateOneOf5 {
  return OwlPredicateOneOf5ToJSONTyped(json, false)
}

export function OwlPredicateOneOf5ToJSONTyped(
  value?: OwlPredicateOneOf5 | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    kind: value['kind'],
  }
}
