/* tslint:disable */
/* eslint-disable */
/**
 * OwlID Verification Service
 * SD-JWT VC presentation verification, trusted issuer management, and credential revocation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js'
/**
 * Holder's residence country is in the set.
 * @export
 * @interface OwlPredicateOneOf4
 */
export interface OwlPredicateOneOf4 {
  /**
   *
   * @type {Array<string>}
   * @memberof OwlPredicateOneOf4
   */
  countries: Array<string>
  /**
   *
   * @type {string}
   * @memberof OwlPredicateOneOf4
   */
  kind: OwlPredicateOneOf4KindEnum
}

/**
 * @export
 * @enum {string}
 */
export enum OwlPredicateOneOf4KindEnum {
  residency_in = 'residency_in',
}

/**
 * Check if a given object implements the OwlPredicateOneOf4 interface.
 */
export function instanceOfOwlPredicateOneOf4(value: object): value is OwlPredicateOneOf4 {
  if (!('countries' in value) || value['countries'] === undefined) return false
  if (!('kind' in value) || value['kind'] === undefined) return false
  return true
}

export function OwlPredicateOneOf4FromJSON(json: any): OwlPredicateOneOf4 {
  return OwlPredicateOneOf4FromJSONTyped(json, false)
}

export function OwlPredicateOneOf4FromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): OwlPredicateOneOf4 {
  if (json == null) {
    return json
  }
  return {
    countries: json['countries'],
    kind: json['kind'],
  }
}

export function OwlPredicateOneOf4ToJSON(json: any): OwlPredicateOneOf4 {
  return OwlPredicateOneOf4ToJSONTyped(json, false)
}

export function OwlPredicateOneOf4ToJSONTyped(
  value?: OwlPredicateOneOf4 | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    countries: value['countries'],
    kind: value['kind'],
  }
}
