/* tslint:disable */
/* eslint-disable */
/**
 * OwlID Verification Service
 * SD-JWT VC presentation verification, trusted issuer management, and credential revocation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js'
/**
 * Holder's age is in `[min, max]` inclusive.
 * @export
 * @interface OwlPredicateOneOf1
 */
export interface OwlPredicateOneOf1 {
  /**
   *
   * @type {string}
   * @memberof OwlPredicateOneOf1
   */
  kind: OwlPredicateOneOf1KindEnum
  /**
   *
   * @type {number}
   * @memberof OwlPredicateOneOf1
   */
  max: number
  /**
   *
   * @type {number}
   * @memberof OwlPredicateOneOf1
   */
  min: number
}

/**
 * @export
 * @enum {string}
 */
export enum OwlPredicateOneOf1KindEnum {
  age_range = 'age_range',
}

/**
 * Check if a given object implements the OwlPredicateOneOf1 interface.
 */
export function instanceOfOwlPredicateOneOf1(value: object): value is OwlPredicateOneOf1 {
  if (!('kind' in value) || value['kind'] === undefined) return false
  if (!('max' in value) || value['max'] === undefined) return false
  if (!('min' in value) || value['min'] === undefined) return false
  return true
}

export function OwlPredicateOneOf1FromJSON(json: any): OwlPredicateOneOf1 {
  return OwlPredicateOneOf1FromJSONTyped(json, false)
}

export function OwlPredicateOneOf1FromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): OwlPredicateOneOf1 {
  if (json == null) {
    return json
  }
  return {
    kind: json['kind'],
    max: json['max'],
    min: json['min'],
  }
}

export function OwlPredicateOneOf1ToJSON(json: any): OwlPredicateOneOf1 {
  return OwlPredicateOneOf1ToJSONTyped(json, false)
}

export function OwlPredicateOneOf1ToJSONTyped(
  value?: OwlPredicateOneOf1 | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    kind: value['kind'],
    max: value['max'],
    min: value['min'],
  }
}
