/* tslint:disable */
/* eslint-disable */
/**
 * OwlID Verification Service
 * SD-JWT VC presentation verification, trusted issuer management, and credential revocation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { OwlPredicateOneOf } from './OwlPredicateOneOf.js'
import {
  instanceOfOwlPredicateOneOf,
  OwlPredicateOneOfFromJSON,
  OwlPredicateOneOfFromJSONTyped,
  OwlPredicateOneOfToJSON,
} from './OwlPredicateOneOf.js'
import type { OwlPredicateOneOf1 } from './OwlPredicateOneOf1.js'
import {
  instanceOfOwlPredicateOneOf1,
  OwlPredicateOneOf1FromJSON,
  OwlPredicateOneOf1FromJSONTyped,
  OwlPredicateOneOf1ToJSON,
} from './OwlPredicateOneOf1.js'
import type { OwlPredicateOneOf2 } from './OwlPredicateOneOf2.js'
import {
  instanceOfOwlPredicateOneOf2,
  OwlPredicateOneOf2FromJSON,
  OwlPredicateOneOf2FromJSONTyped,
  OwlPredicateOneOf2ToJSON,
} from './OwlPredicateOneOf2.js'
import type { OwlPredicateOneOf3 } from './OwlPredicateOneOf3.js'
import {
  instanceOfOwlPredicateOneOf3,
  OwlPredicateOneOf3FromJSON,
  OwlPredicateOneOf3FromJSONTyped,
  OwlPredicateOneOf3ToJSON,
} from './OwlPredicateOneOf3.js'
import type { OwlPredicateOneOf4 } from './OwlPredicateOneOf4.js'
import {
  instanceOfOwlPredicateOneOf4,
  OwlPredicateOneOf4FromJSON,
  OwlPredicateOneOf4FromJSONTyped,
  OwlPredicateOneOf4ToJSON,
} from './OwlPredicateOneOf4.js'
import type { OwlPredicateOneOf5 } from './OwlPredicateOneOf5.js'
import {
  instanceOfOwlPredicateOneOf5,
  OwlPredicateOneOf5FromJSON,
  OwlPredicateOneOf5FromJSONTyped,
  OwlPredicateOneOf5ToJSON,
} from './OwlPredicateOneOf5.js'
import type { OwlPredicateOneOf6 } from './OwlPredicateOneOf6.js'
import {
  instanceOfOwlPredicateOneOf6,
  OwlPredicateOneOf6FromJSON,
  OwlPredicateOneOf6FromJSONTyped,
  OwlPredicateOneOf6ToJSON,
} from './OwlPredicateOneOf6.js'

/**
 * @type OwlPredicate
 * Discriminated union of every Midnight-native predicate the
 * verifier can ask for. Mirrors the TypeScript `OwlPredicate` type
 * in `@owlid/sdk/owl-dcql` — keep both sides in lockstep.
 * @export
 */
export type OwlPredicate =
  | OwlPredicateOneOf
  | OwlPredicateOneOf1
  | OwlPredicateOneOf2
  | OwlPredicateOneOf3
  | OwlPredicateOneOf4
  | OwlPredicateOneOf5
  | OwlPredicateOneOf6

export function OwlPredicateFromJSON(json: any): OwlPredicate {
  return OwlPredicateFromJSONTyped(json, false)
}

export function OwlPredicateFromJSONTyped(json: any, ignoreDiscriminator: boolean): OwlPredicate {
  if (json == null) {
    return json
  }
  if (instanceOfOwlPredicateOneOf(json)) {
    return OwlPredicateOneOfFromJSONTyped(json, true)
  }
  if (instanceOfOwlPredicateOneOf1(json)) {
    return OwlPredicateOneOf1FromJSONTyped(json, true)
  }
  if (instanceOfOwlPredicateOneOf2(json)) {
    return OwlPredicateOneOf2FromJSONTyped(json, true)
  }
  if (instanceOfOwlPredicateOneOf3(json)) {
    return OwlPredicateOneOf3FromJSONTyped(json, true)
  }
  if (instanceOfOwlPredicateOneOf4(json)) {
    return OwlPredicateOneOf4FromJSONTyped(json, true)
  }
  if (instanceOfOwlPredicateOneOf5(json)) {
    return OwlPredicateOneOf5FromJSONTyped(json, true)
  }
  if (instanceOfOwlPredicateOneOf6(json)) {
    return OwlPredicateOneOf6FromJSONTyped(json, true)
  }

  return {} as any
}

export function OwlPredicateToJSON(json: any): any {
  return OwlPredicateToJSONTyped(json, false)
}

export function OwlPredicateToJSONTyped(
  value?: OwlPredicate | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  if (instanceOfOwlPredicateOneOf(value)) {
    return OwlPredicateOneOfToJSON(value as OwlPredicateOneOf)
  }
  if (instanceOfOwlPredicateOneOf1(value)) {
    return OwlPredicateOneOf1ToJSON(value as OwlPredicateOneOf1)
  }
  if (instanceOfOwlPredicateOneOf2(value)) {
    return OwlPredicateOneOf2ToJSON(value as OwlPredicateOneOf2)
  }
  if (instanceOfOwlPredicateOneOf3(value)) {
    return OwlPredicateOneOf3ToJSON(value as OwlPredicateOneOf3)
  }
  if (instanceOfOwlPredicateOneOf4(value)) {
    return OwlPredicateOneOf4ToJSON(value as OwlPredicateOneOf4)
  }
  if (instanceOfOwlPredicateOneOf5(value)) {
    return OwlPredicateOneOf5ToJSON(value as OwlPredicateOneOf5)
  }
  if (instanceOfOwlPredicateOneOf6(value)) {
    return OwlPredicateOneOf6ToJSON(value as OwlPredicateOneOf6)
  }

  return {}
}
