/* tslint:disable */
/* eslint-disable */
/**
 * OwlID Verification Service
 * SD-JWT VC presentation verification, trusted issuer management, and credential revocation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js'
/**
 *
 * @export
 * @interface PredicateInfo
 */
export interface PredicateInfo {
  /**
   *
   * @type {string}
   * @memberof PredicateInfo
   */
  attribute: string
  /**
   *
   * @type {string}
   * @memberof PredicateInfo
   */
  id: string
  /**
   *
   * @type {string}
   * @memberof PredicateInfo
   */
  label: string
  /**
   *
   * @type {string}
   * @memberof PredicateInfo
   */
  op: string
  /**
   * DCQL claim-path route token. This — not `attribute` — is what a
   * verifier MUST put on the DCQL claim path: the holder SDK and the
   * verifier route on it (`age_over_18`, `verification_level`, …).
   * @type {string}
   * @memberof PredicateInfo
   */
  route: string
  /**
   * JSON-encoded wire value the holder drops onto `PredicateRequest.value`.
   * `GreaterOrEqual` predicates carry a number (e.g. `"18"`); `InSet`
   * predicates carry a registered dataset name (e.g. `"\"eu\""`).
   * @type {string}
   * @memberof PredicateInfo
   */
  value: string
}

/**
 * Check if a given object implements the PredicateInfo interface.
 */
export function instanceOfPredicateInfo(value: object): value is PredicateInfo {
  if (!('attribute' in value) || value['attribute'] === undefined) return false
  if (!('id' in value) || value['id'] === undefined) return false
  if (!('label' in value) || value['label'] === undefined) return false
  if (!('op' in value) || value['op'] === undefined) return false
  if (!('route' in value) || value['route'] === undefined) return false
  if (!('value' in value) || value['value'] === undefined) return false
  return true
}

export function PredicateInfoFromJSON(json: any): PredicateInfo {
  return PredicateInfoFromJSONTyped(json, false)
}

export function PredicateInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PredicateInfo {
  if (json == null) {
    return json
  }
  return {
    attribute: json['attribute'],
    id: json['id'],
    label: json['label'],
    op: json['op'],
    route: json['route'],
    value: json['value'],
  }
}

export function PredicateInfoToJSON(json: any): PredicateInfo {
  return PredicateInfoToJSONTyped(json, false)
}

export function PredicateInfoToJSONTyped(
  value?: PredicateInfo | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    attribute: value['attribute'],
    id: value['id'],
    label: value['label'],
    op: value['op'],
    route: value['route'],
    value: value['value'],
  }
}
