/* tslint:disable */
/* eslint-disable */
/**
 * OwlID Verification Service
 * SD-JWT VC presentation verification, trusted issuer management, and credential revocation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js'
/**
 *
 * @export
 * @interface RelayProofResponse
 */
export interface RelayProofResponse {
  /**
   * Submission status — `submitted` for fire-and-forget relays, or
   * a terminal finalization status (`SucceedEntirely` |
   * `FailEntirely` | `FailFallible`) when the sidecar awaited the
   * finalization itself. Holder polls
   * `GET /predicates/tx/{txId}/status` to await finalization.
   * @type {string}
   * @memberof RelayProofResponse
   */
  status: string
  /**
   * Chain transaction id.
   * @type {string}
   * @memberof RelayProofResponse
   */
  txId: string
}

/**
 * Check if a given object implements the RelayProofResponse interface.
 */
export function instanceOfRelayProofResponse(value: object): value is RelayProofResponse {
  if (!('status' in value) || value['status'] === undefined) return false
  if (!('txId' in value) || value['txId'] === undefined) return false
  return true
}

export function RelayProofResponseFromJSON(json: any): RelayProofResponse {
  return RelayProofResponseFromJSONTyped(json, false)
}

export function RelayProofResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): RelayProofResponse {
  if (json == null) {
    return json
  }
  return {
    status: json['status'],
    txId: json['txId'],
  }
}

export function RelayProofResponseToJSON(json: any): RelayProofResponse {
  return RelayProofResponseToJSONTyped(json, false)
}

export function RelayProofResponseToJSONTyped(
  value?: RelayProofResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    status: value['status'],
    txId: value['txId'],
  }
}
