/* tslint:disable */
/* eslint-disable */
/**
 * OwlID Verification Service
 * SD-JWT VC presentation verification, trusted issuer management, and credential revocation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js'
/**
 * Holder self-revocation request — a presentation of the credential to
 * revoke (issuer JWS + KB-JWT proof-of-possession) bound to a fresh server
 * `challenge` and the self-revoke audience.
 * @export
 * @interface RevokeOwnCredentialRequest
 */
export interface RevokeOwnCredentialRequest {
  /**
   * Challenge from `GET /verify/challenge` — also the KB-JWT `nonce`.
   * @type {string}
   * @memberof RevokeOwnCredentialRequest
   */
  challenge: string
  /**
   * SD-JWT VC presentation: `<issuer-jwt>~<disclosures…>~<kb-jwt>`.
   * @type {string}
   * @memberof RevokeOwnCredentialRequest
   */
  presentation: string
  /**
   *
   * @type {string}
   * @memberof RevokeOwnCredentialRequest
   */
  reason?: string | null
}

/**
 * Check if a given object implements the RevokeOwnCredentialRequest interface.
 */
export function instanceOfRevokeOwnCredentialRequest(
  value: object,
): value is RevokeOwnCredentialRequest {
  if (!('challenge' in value) || value['challenge'] === undefined) return false
  if (!('presentation' in value) || value['presentation'] === undefined) return false
  return true
}

export function RevokeOwnCredentialRequestFromJSON(json: any): RevokeOwnCredentialRequest {
  return RevokeOwnCredentialRequestFromJSONTyped(json, false)
}

export function RevokeOwnCredentialRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): RevokeOwnCredentialRequest {
  if (json == null) {
    return json
  }
  return {
    challenge: json['challenge'],
    presentation: json['presentation'],
    reason: json['reason'] == null ? undefined : json['reason'],
  }
}

export function RevokeOwnCredentialRequestToJSON(json: any): RevokeOwnCredentialRequest {
  return RevokeOwnCredentialRequestToJSONTyped(json, false)
}

export function RevokeOwnCredentialRequestToJSONTyped(
  value?: RevokeOwnCredentialRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    challenge: value['challenge'],
    presentation: value['presentation'],
    reason: value['reason'],
  }
}
