/* tslint:disable */
/* eslint-disable */
/**
 * OwlID Verification Service
 * Token verification, trusted issuer management, and credential revocation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js'
/**
 *
 * @export
 * @interface SidecarHealth
 */
export interface SidecarHealth {
  /**
   * `true` if the sidecar reports it is connected to the chain.
   * @type {boolean}
   * @memberof SidecarHealth
   */
  connected?: boolean | null
  /**
   * Error message when reachable=false. Generic — no internal stack.
   * @type {string}
   * @memberof SidecarHealth
   */
  error?: string | null
  /**
   * Round-trip latency of the health probe, in milliseconds.
   * @type {number}
   * @memberof SidecarHealth
   */
  latencyMs?: number | null
  /**
   * `true` if the sidecar responded; `false` if HTTP failed.
   * @type {boolean}
   * @memberof SidecarHealth
   */
  reachable: boolean
}

/**
 * Check if a given object implements the SidecarHealth interface.
 */
export function instanceOfSidecarHealth(value: object): value is SidecarHealth {
  if (!('reachable' in value) || value['reachable'] === undefined) return false
  return true
}

export function SidecarHealthFromJSON(json: any): SidecarHealth {
  return SidecarHealthFromJSONTyped(json, false)
}

export function SidecarHealthFromJSONTyped(json: any, ignoreDiscriminator: boolean): SidecarHealth {
  if (json == null) {
    return json
  }
  return {
    connected: json['connected'] == null ? undefined : json['connected'],
    error: json['error'] == null ? undefined : json['error'],
    latencyMs: json['latencyMs'] == null ? undefined : json['latencyMs'],
    reachable: json['reachable'],
  }
}

export function SidecarHealthToJSON(json: any): SidecarHealth {
  return SidecarHealthToJSONTyped(json, false)
}

export function SidecarHealthToJSONTyped(
  value?: SidecarHealth | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    connected: value['connected'],
    error: value['error'],
    latencyMs: value['latencyMs'],
    reachable: value['reachable'],
  }
}
