/* tslint:disable */
/* eslint-disable */
/**
 * OwlID Verification Service
 * Token verification, trusted issuer management, and credential revocation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js'
/**
 *
 * @export
 * @interface ToggleResponse
 */
export interface ToggleResponse {
  /**
   *
   * @type {boolean}
   * @memberof ToggleResponse
   */
  enabled: boolean
}

/**
 * Check if a given object implements the ToggleResponse interface.
 */
export function instanceOfToggleResponse(value: object): value is ToggleResponse {
  if (!('enabled' in value) || value['enabled'] === undefined) return false
  return true
}

export function ToggleResponseFromJSON(json: any): ToggleResponse {
  return ToggleResponseFromJSONTyped(json, false)
}

export function ToggleResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ToggleResponse {
  if (json == null) {
    return json
  }
  return {
    enabled: json['enabled'],
  }
}

export function ToggleResponseToJSON(json: any): ToggleResponse {
  return ToggleResponseToJSONTyped(json, false)
}

export function ToggleResponseToJSONTyped(
  value?: ToggleResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    enabled: value['enabled'],
  }
}
