/* tslint:disable */
/* eslint-disable */
/**
 * OwlID Verification Service
 * SD-JWT VC presentation verification, trusted issuer management, and credential revocation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js'
/**
 *
 * @export
 * @interface TrustedIssuerInfo
 */
export interface TrustedIssuerInfo {
  /**
   * When this key was registered — lets the UI distinguish rotated
   * keys that otherwise share the same display name.
   * @type {Date}
   * @memberof TrustedIssuerInfo
   */
  addedAt: Date
  /**
   *
   * @type {string}
   * @memberof TrustedIssuerInfo
   */
  description?: string | null
  /**
   *
   * @type {boolean}
   * @memberof TrustedIssuerInfo
   */
  isActive: boolean
  /**
   *
   * @type {string}
   * @memberof TrustedIssuerInfo
   */
  name: string
  /**
   *
   * @type {string}
   * @memberof TrustedIssuerInfo
   */
  publicKey: string
}

/**
 * Check if a given object implements the TrustedIssuerInfo interface.
 */
export function instanceOfTrustedIssuerInfo(value: object): value is TrustedIssuerInfo {
  if (!('addedAt' in value) || value['addedAt'] === undefined) return false
  if (!('isActive' in value) || value['isActive'] === undefined) return false
  if (!('name' in value) || value['name'] === undefined) return false
  if (!('publicKey' in value) || value['publicKey'] === undefined) return false
  return true
}

export function TrustedIssuerInfoFromJSON(json: any): TrustedIssuerInfo {
  return TrustedIssuerInfoFromJSONTyped(json, false)
}

export function TrustedIssuerInfoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): TrustedIssuerInfo {
  if (json == null) {
    return json
  }
  return {
    addedAt: new Date(json['addedAt']),
    description: json['description'] == null ? undefined : json['description'],
    isActive: json['isActive'],
    name: json['name'],
    publicKey: json['publicKey'],
  }
}

export function TrustedIssuerInfoToJSON(json: any): TrustedIssuerInfo {
  return TrustedIssuerInfoToJSONTyped(json, false)
}

export function TrustedIssuerInfoToJSONTyped(
  value?: TrustedIssuerInfo | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    addedAt: value['addedAt'].toISOString(),
    description: value['description'],
    isActive: value['isActive'],
    name: value['name'],
    publicKey: value['publicKey'],
  }
}
