/* tslint:disable */
/* eslint-disable */
/**
 * OwlID Verification Service
 * SD-JWT VC presentation verification, trusted issuer management, and credential revocation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js'
/**
 *
 * @export
 * @interface TxStatusResponse
 */
export interface TxStatusResponse {
  /**
   * Latest known phase. One of: `queued | balancing | submitting |
   * submitted | balance-failed | submit-failed | SucceedEntirely |
   * FailEntirely | FailFallible`. The system uses SSE end-to-end for
   * these updates — see `GET /predicates/tx/{tx_id}/events`.
   * @type {string}
   * @memberof TxStatusResponse
   */
  status: string
  /**
   *
   * @type {string}
   * @memberof TxStatusResponse
   */
  txId: string
}

/**
 * Check if a given object implements the TxStatusResponse interface.
 */
export function instanceOfTxStatusResponse(value: object): value is TxStatusResponse {
  if (!('status' in value) || value['status'] === undefined) return false
  if (!('txId' in value) || value['txId'] === undefined) return false
  return true
}

export function TxStatusResponseFromJSON(json: any): TxStatusResponse {
  return TxStatusResponseFromJSONTyped(json, false)
}

export function TxStatusResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): TxStatusResponse {
  if (json == null) {
    return json
  }
  return {
    status: json['status'],
    txId: json['txId'],
  }
}

export function TxStatusResponseToJSON(json: any): TxStatusResponse {
  return TxStatusResponseToJSONTyped(json, false)
}

export function TxStatusResponseToJSONTyped(
  value?: TxStatusResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    status: value['status'],
    txId: value['txId'],
  }
}
