/* tslint:disable */
/* eslint-disable */
/**
 * OwlID Verification Service
 * SD-JWT VC presentation verification, trusted issuer management, and credential revocation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js'
import type { DcqlRequest } from './DcqlRequest.js'
import {
  DcqlRequestFromJSON,
  DcqlRequestFromJSONTyped,
  DcqlRequestToJSON,
  DcqlRequestToJSONTyped,
} from './DcqlRequest.js'

/**
 * DCQL verification request (OpenID4VP 1.0 §6 + §8.1).
 * @export
 * @interface VerifyDcqlRequest
 */
export interface VerifyDcqlRequest {
  /**
   * Expected KB-JWT `aud` — when set, applies to every entry.
   * @type {string}
   * @memberof VerifyDcqlRequest
   */
  audience?: string | null
  /**
   * Server-generated nonce bound into every KB-JWT in the bundle.
   * @type {string}
   * @memberof VerifyDcqlRequest
   */
  challenge: string
  /**
   * The DCQL query the wallet was solving. The verifier re-checks
   * per-credential constraints (`format`, `meta.vct_values`, `claims`)
   * and the `credential_sets` solver against the actual responses.
   * @type {DcqlRequest}
   * @memberof VerifyDcqlRequest
   */
  query: DcqlRequest
  /**
   * OID4VP verifier `client_id` (typically the response_uri). Folded
   * into the on-chain attestation key for nationality / residency
   * predicates so two verifiers asking the same allowed-set produce
   * distinct keys. Required when the DCQL `claims` contain a
   * `nationality_in` / `resident_in` path; ignored otherwise.
   * @type {string}
   * @memberof VerifyDcqlRequest
   */
  verifierId?: string | null
  /**
   * DCQL vp_token — keyed by the DCQL `credentials[].id` from
   * `query`. Per OID4VP 1.0 §8.1, each value is ALWAYS an array of
   * one or more SD-JWT VC presentations
   * (`<issuer-JWT>~<disclosure>~…~<KB-JWT>`), even when the
   * credential query did not set `multiple: true`.
   * @type {{ [key: string]: Array<string>; }}
   * @memberof VerifyDcqlRequest
   */
  vpToken: { [key: string]: Array<string> }
}

/**
 * Check if a given object implements the VerifyDcqlRequest interface.
 */
export function instanceOfVerifyDcqlRequest(value: object): value is VerifyDcqlRequest {
  if (!('challenge' in value) || value['challenge'] === undefined) return false
  if (!('query' in value) || value['query'] === undefined) return false
  if (!('vpToken' in value) || value['vpToken'] === undefined) return false
  return true
}

export function VerifyDcqlRequestFromJSON(json: any): VerifyDcqlRequest {
  return VerifyDcqlRequestFromJSONTyped(json, false)
}

export function VerifyDcqlRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): VerifyDcqlRequest {
  if (json == null) {
    return json
  }
  return {
    audience: json['audience'] == null ? undefined : json['audience'],
    challenge: json['challenge'],
    query: DcqlRequestFromJSON(json['query']),
    verifierId: json['verifierId'] == null ? undefined : json['verifierId'],
    vpToken: json['vpToken'],
  }
}

export function VerifyDcqlRequestToJSON(json: any): VerifyDcqlRequest {
  return VerifyDcqlRequestToJSONTyped(json, false)
}

export function VerifyDcqlRequestToJSONTyped(
  value?: VerifyDcqlRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    audience: value['audience'],
    challenge: value['challenge'],
    query: DcqlRequestToJSON(value['query']),
    verifierId: value['verifierId'],
    vpToken: value['vpToken'],
  }
}
