/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * A signed, issued credential containing a Merkle tree of attributes.
 *
 * Use `generateProof()` for Ed25519-signed tokens, or `prepareToken()`
 * followed by `Token.finalizeWebauthn()` / `Token.finalizeRingSig()`
 * for WebAuthn or ring-signature flows.
 */
export declare class Credential {
  /**
   * Generate a proof token signed with Ed25519.
   *
   * Performs selective disclosure (Merkle proofs) and/or ZK predicate proofs
   * as specified in the request, then signs the result with the owner's keypair.
   *
   * @param request - What to prove: disclosed attributes, predicates, trusted issuers, and challenge.
   * @param keypair - The credential owner's `KeyPair` for signing.
   * @param ttlSeconds - Token time-to-live in seconds (e.g., `3600` for 1 hour).
   * @returns A signed `Token` ready for verification or compact encoding.
   * @throws If a requested attribute doesn't exist or a predicate is invalid.
   */
  prove(request: ProofRequest, keypair: KeyPair, ttlSeconds: number): Token
  /**
   * Prepare a token for two-phase signing (WebAuthn or ring signature).
   *
   * Phase 1: Call this to build the token payload without a signature.
   * Phase 2: Use `Token.finalizeWebauthn()` or `Token.finalizeRingSig()`
   * to attach the signature.
   *
   * @param request - What to prove (same as `generateProof`).
   * @param ttlSeconds - Token time-to-live in seconds.
   * @returns A `PreparedToken` containing the challenge to sign.
   * @throws If a requested attribute doesn't exist or a predicate is invalid.
   */
  prepare(request: ProofRequest, ttlSeconds: number): PreparedToken
  /**
   * Get the Merkle root hash of this credential's attributes.
   *
   * This is the unique fingerprint of the credential content. Used as the
   * credential identifier for revocation.
   *
   * @returns 64 hex characters (SHA-256 Merkle root).
   */
  rootHash(): string
  /**
   * Serialize to a JSON string for storage.
   *
   * @returns JSON string that can be restored with `Credential.fromJson()`.
   */
  toJson(): string
  /**
   * Restore a `Credential` from a JSON string.
   *
   * @param json - JSON previously obtained from `proofDocument.toJson()`.
   * @throws If the JSON is invalid or malformed.
   */
  static fromJson(json: string): Credential
}

/**
 * An unsigned document containing identity attributes.
 *
 * Create a `Document` from a JSON object of attributes, then call `.issue()`
 * with an issuer keypair to produce a signed `Credential`.
 *
 * @example
 * ```js
 * const doc = Document.fromJson(JSON.stringify({
 *   issuerKey: issuerKp.publicKey().toHex(),
 *   ownerKey: ownerKp.publicKey().toHex(),
 *   name: 'Alice Johnson',
 *   dateOfBirth: '1999-01-15',
 * }))
 * const proofDoc = doc.issue(issuerKeyPair)
 * ```
 */
export declare class Document {
  /**
   * Create a document from a JSON string of attributes.
   *
   * The JSON must be a flat object with string keys and JSON-compatible values.
   * Must include `issuerKey` and `ownerKey` (hex public keys).
   *
   * @param attributesJson - A `JSON.stringify()`'d object of attributes.
   * @returns A new unsigned `Document`.
   * @throws If the string is not valid JSON or not an object.
   */
  static fromJson(attributesJson: string): Document
  /**
   * Issue the document by signing it with an issuer keypair.
   *
   * Builds a Merkle tree over the attributes and signs the root.
   *
   * @param issuerKeypair - The issuer's `KeyPair` used to sign.
   * @returns A signed `Credential` ready for proof generation.
   */
  issue(issuerKeypair: KeyPair): Credential
}

/**
 * An Ed25519 keypair for signing and verification.
 *
 * Use `KeyPair.generate()` to create a new random keypair, or
 * `KeyPair.fromHex()` to restore one from a saved private key.
 */
export declare class KeyPair {
  /**
   * Generate a new random Ed25519 keypair.
   *
   * @returns A new `KeyPair` with a cryptographically random private key.
   *
   * @example
   * ```js
   * const kp = KeyPair.generate()
   * console.log(kp.publicKey().toHex()) // 64 hex chars
   * ```
   */
  static generate(): KeyPair
  /**
   * Restore a keypair from a hex-encoded 32-byte Ed25519 seed.
   *
   * @param privateKeyHex - 64 hex characters representing the 32-byte seed.
   * @returns The restored `KeyPair`.
   * @throws If the hex string is invalid or not exactly 32 bytes.
   */
  static fromHex(privateKeyHex: string): KeyPair
  /**
   * Get the public key for this keypair.
   *
   * @returns The corresponding `PublicKey`.
   */
  publicKey(): PublicKey
  /**
   * Get the hex-encoded 32-byte private key seed.
   *
   * @returns 64 hex characters. Store securely — this is the secret key material.
   */
  toHex(): string
  /**
   * Sign a message with this keypair.
   *
   * @param message - The message bytes to sign.
   * @returns An Ed25519 `Signature` (64 bytes).
   */
  sign(message: Buffer): Signature
}

/**
 * A prepared token awaiting a signature (WebAuthn or ring signature).
 *
 * Created by `credential.prepare()`. Contains the unsigned token payload
 * and the challenge to present to the signing mechanism.
 */
export declare class PreparedToken {
  /**
   * Get the challenge for signing (base64url-encoded SHA-256 of the payload).
   *
   * Pass this as the WebAuthn assertion challenge.
   *
   * @returns Base64url-encoded challenge string.
   */
  challenge(): string
  /**
   * Get the serialized payload as a JSON string (for debugging/inspection).
   *
   * @returns JSON string of the unsigned token payload.
   */
  payloadJson(): string
  /**
   * Serialize to JSON for storage or cross-context transfer.
   *
   * @returns JSON string that can be restored with `PreparedToken.fromJson()`.
   */
  toJson(): string
  /**
   * Restore a `PreparedToken` from a JSON string.
   *
   * @param json - JSON previously obtained from `preparedToken.toJson()`.
   * @throws If the JSON is invalid or malformed.
   */
  static fromJson(json: string): PreparedToken
}

/** An Ed25519 public key for signature verification. */
export declare class PublicKey {
  /**
   * Create a public key from a 64-character hex string.
   *
   * @param hex - 64 hex characters (32 bytes).
   * @throws If the hex is invalid or the wrong length.
   */
  static fromHex(hex: string): PublicKey
  /**
   * Convert to a 64-character hex string.
   *
   * @returns 64 hex characters. Use this value for `ProofRequest.trustedIssuers`.
   */
  toHex(): string
  /**
   * Verify an Ed25519 signature on a message.
   *
   * Returns `false` for invalid signatures instead of throwing.
   *
   * @param message - The original message bytes.
   * @param signature - The signature to verify.
   * @returns `true` if the signature is valid, `false` otherwise.
   */
  verify(message: Buffer, signature: Signature): boolean
}

/** An Ed25519 signature (64 bytes). */
export declare class Signature {
  /**
   * Create a signature from a 128-character hex string (64 bytes).
   *
   * @param hex - 128 hex characters.
   * @throws If the hex is invalid or the wrong length.
   */
  static fromHex(hex: string): Signature
  /**
   * Convert to a 128-character hex string.
   *
   * @returns 128 hex characters (64 bytes).
   */
  toHex(): string
}

/**
 * A verifiable proof token for presentation to verifiers.
 *
 * Contains selective disclosure proofs, optional ZK predicate proofs,
 * and a cryptographic signature (Ed25519, WebAuthn P-256, or ring signature).
 *
 * Supports two serialization formats:
 * - **Compact** (`OID1:...`): optimized for QR codes, uses CBOR + zstd + Base45.
 * - **JSON**: full fidelity, for storage and debugging.
 */
export declare class Token {
  /**
   * Encode to compact format for QR codes and size-constrained transports.
   *
   * Pipeline: Token → CBOR → zstd(dict) → Base45 → `OID1:` prefix.
   * Typical sizes: ~500-1000 chars for selective disclosure,
   * ~1000-1500 chars with ZK proofs.
   *
   * @returns A compact string starting with `OID1:`.
   * @throws If encoding fails.
   */
  toCompact(): string
  /**
   * Decode a token from compact format.
   *
   * @param compact - A compact string starting with `OID1:`.
   * @throws If the input is malformed, corrupted, or uses an unsupported version.
   */
  static fromCompact(compact: string): Token
  /**
   * Serialize the token to a JSON string.
   *
   * @returns JSON string that can be restored with `Token.fromJson()`.
   */
  toJson(): string
  /**
   * Restore a `Token` from a JSON string.
   *
   * @param json - JSON previously obtained from `token.toJson()`.
   * @throws If the JSON is invalid or malformed.
   */
  static fromJson(json: string): Token
  /**
   * Get disclosed attributes as a JSON string.
   *
   * @returns JSON object string. Parse with `JSON.parse()`.
   */
  subjects(): string
  /**
   * Get the challenge this token is bound to.
   *
   * @returns The challenge string from the original proof request.
   */
  challenge(): string
  /**
   * Get the credential root hash (hex).
   *
   * This is the credential identifier — use it for revocation checks.
   *
   * @returns 64 hex characters (SHA-256 Merkle root).
   */
  rootHash(): string
  /** Get the number of ZK proofs attached to this token. */
  zkProofCount(): number
  /** Get the token's time-to-live in seconds. */
  ttl(): number
  /** Get activation time as unix epoch seconds. */
  activationTime(): number
  /**
   * Verify the token's proofs, signature, expiration, and issuer trust.
   *
   * Checks: (1) Merkle proofs are valid, (2) ZK predicate proofs are valid,
   * (3) signature is valid, (4) token is not expired, (5) issuer is trusted,
   * (6) credential is not revoked.
   *
   * @param trustedIssuers - Array of trusted issuer `PublicKey` objects.
   * @param challenge - The challenge string used when generating the proof.
   * @param revokedHashes - Optional array of revoked credential root hashes (hex).
   * @returns JSON string of disclosed attributes. Parse with `JSON.parse()`.
   * @throws If any verification check fails.
   *
   * @example
   * ```js
   * const json = token.verify([issuerPk], challenge)
   * const disclosed = JSON.parse(json)
   * console.log(disclosed.name) // 'Alice'
   * ```
   */
  verify(
    trustedIssuers: Array<PublicKey>,
    challenge: string,
    revokedHashes?: Array<string> | undefined | null,
  ): string
  /**
   * Finalize a prepared token with a WebAuthn (FIDO2) signature.
   *
   * Completes the two-phase signing flow started by `credential.prepare()`.
   * Use the challenge from `preparedToken.challenge()` as the WebAuthn assertion challenge.
   *
   * @param prepared - The `PreparedToken` from `credential.prepare()`.
   * @param webauthnSig - The `WebAuthnSignatureData` from `navigator.credentials.get()`.
   * @param credentialPublicKey - Hex-encoded P-256 public key from WebAuthn registration.
   * @returns A finalized `Token` with a WebAuthn P-256 signature.
   * @throws If the signature data is invalid.
   */
  static finalizeWebauthn(
    prepared: PreparedToken,
    webauthnSig: WebAuthnSignatureData,
    credentialPublicKey: string,
  ): Token
  /**
   * Finalize a prepared token with a ring signature for anonymous owner authentication.
   *
   * Creates a proof that the signer is one of the ring members without revealing
   * which specific member signed.
   *
   * @param prepared - The `PreparedToken` from `credential.prepare()`.
   * @param privateKeyHex - Hex-encoded 32-byte private key of the signer.
   * @param ringPublicKeysHex - Array of hex-encoded 32-byte public keys forming
   *   the anonymity set. Must include the signer's public key.
   * @returns A finalized `Token` with a ring signature.
   * @throws If any hex key is invalid or the signer's key is not in the ring.
   */
  static finalizeRingSig(
    prepared: PreparedToken,
    privateKeyHex: string,
    ringPublicKeysHex: Array<string>,
  ): Token
}

/**
 * Hash data with BLAKE3 (faster than SHA-256, equally secure).
 *
 * @param data - The bytes to hash.
 * @returns 64 hex characters (256-bit digest).
 */
export declare function blake3(data: Buffer): string

/**
 * A predicate to prove in zero knowledge.
 *
 * Supported operators:
 * - `"GreaterOrEqual"` — proves the attribute value >= threshold.
 *   For `dateOfBirth`, the value is an age (e.g., `"18"`).
 * - `"InSet"` — proves the attribute value is in a set.
 *   The value is a JSON array (e.g., `JSON.stringify(["NL", "DE", "FR"])`).
 */
export interface PredicateRequest {
  /** Credential attribute name (e.g., `"dateOfBirth"`, `"nationality"`). */
  attribute: string
  /** Predicate operator: `"GreaterOrEqual"` or `"InSet"`. */
  op: string
  /** JSON-encoded threshold or target value. */
  value: string
}

/**
 * Specifies what to prove in a proof token.
 *
 * @example
 * ```js
 * const request = {
 *   disclose: ['name', 'nationality'],
 *   predicates: [{
 *     attribute: 'dateOfBirth',
 *     op: 'GreaterOrEqual',
 *     value: '18',
 *   }],
 *   trustedIssuers: [issuerPk.toHex()],
 *   challenge: serverChallenge,
 * }
 * ```
 */
export interface ProofRequest {
  /** Attribute names to reveal as plaintext via Merkle selective disclosure. */
  disclose: Array<string>
  /** ZK predicate proofs — prove facts about attributes without revealing values. */
  predicates: Array<PredicateRequest>
  /** Trusted issuer public keys as hex strings. */
  trustedIssuers: Array<string>
  /** Random challenge string for replay prevention (hex from server). */
  challenge: string
}

/**
 * Hash data with SHA-256.
 *
 * @param data - The bytes to hash.
 * @returns 64 hex characters (256-bit digest).
 */
export declare function sha256(data: Buffer): string

/**
 * WebAuthn signature data from `navigator.credentials.get()`.
 *
 * All fields are Base64-encoded byte arrays from the WebAuthn assertion response.
 */
export interface WebAuthnSignatureData {
  /** Base64-encoded authenticator data. */
  authenticatorData: string
  /** Base64-encoded client data JSON. */
  clientDataJson: string
  /** Base64-encoded ECDSA P-256 signature. */
  signature: string
}
