// AUTO-GENERATED by scripts/sync-midnight-assets.ts — do not edit.
// Content hash per predicate ZK artifact. The SDK requests
// `<circuit>.<hash>.<ext>` so a recompiled circuit gets a fresh, cache-busting
// URL; the verification-service strips the hash before lookup.
export const ASSET_HASHES: Record<string, string> = {
  'attestAgeGte.bzkir': '1388b3dd548dddf3',
  'attestAgeGte.prover': '0d379d69e9e48e9e',
  'attestAgeGte.verifier': '6becf79f42a4daaa',
  'attestKycGte.bzkir': '327d983a9f2fcf58',
  'attestKycGte.prover': '81c50e4fd493355b',
  'attestKycGte.verifier': '16377486be5632b5',
  'attestResidencyIn.bzkir': 'f311d35ef51aa5aa',
  'attestResidencyIn.prover': '714111e57fcb5123',
  'attestResidencyIn.verifier': '87cd000981668fab',
  'attestEmailVerified.bzkir': '920f547b7335fce4',
  'attestEmailVerified.prover': '5102b470297cf84e',
  'attestEmailVerified.verifier': '29353a67983c0611',
  'attestNationalityIn.bzkir': '55fe885e368a2e93',
  'attestNationalityIn.prover': 'b47bfcd016cf3c6e',
  'attestNationalityIn.verifier': 'cb581fe6c661a9ed',
  'attestAgeRange.bzkir': '5699821294ca8df9',
  'attestAgeRange.prover': '8b0f61fe5cf32e7a',
  'attestAgeRange.verifier': '0cbc4ad84474e7e4',
  'attestUniquePersonhood.bzkir': 'd53b1c00b98d8482',
  'attestUniquePersonhood.prover': 'd45c5f7e07a8cd66',
  'attestUniquePersonhood.verifier': '31060bcdd55ce2a8',
}
