/* tslint:disable */
/* eslint-disable */
/**
 * OwlID Issuer Service
 * Identity verification and credential issuance
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js'
import type { SessionStatus } from './SessionStatus.js'
import {
  SessionStatusFromJSON,
  SessionStatusFromJSONTyped,
  SessionStatusToJSON,
  SessionStatusToJSONTyped,
} from './SessionStatus.js'

/**
 * Response from callback handlers
 * @export
 * @interface CallbackResponse
 */
export interface CallbackResponse {
  /**
   *
   * @type {string}
   * @memberof CallbackResponse
   */
  redirectUrl?: string | null
  /**
   *
   * @type {string}
   * @memberof CallbackResponse
   */
  sessionId: string
  /**
   *
   * @type {SessionStatus}
   * @memberof CallbackResponse
   */
  status: SessionStatus
  /**
   *
   * @type {boolean}
   * @memberof CallbackResponse
   */
  success: boolean
}

/**
 * Check if a given object implements the CallbackResponse interface.
 */
export function instanceOfCallbackResponse(value: object): value is CallbackResponse {
  if (!('sessionId' in value) || value['sessionId'] === undefined) return false
  if (!('status' in value) || value['status'] === undefined) return false
  if (!('success' in value) || value['success'] === undefined) return false
  return true
}

export function CallbackResponseFromJSON(json: any): CallbackResponse {
  return CallbackResponseFromJSONTyped(json, false)
}

export function CallbackResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CallbackResponse {
  if (json == null) {
    return json
  }
  return {
    redirectUrl: json['redirectUrl'] == null ? undefined : json['redirectUrl'],
    sessionId: json['sessionId'],
    status: SessionStatusFromJSON(json['status']),
    success: json['success'],
  }
}

export function CallbackResponseToJSON(json: any): CallbackResponse {
  return CallbackResponseToJSONTyped(json, false)
}

export function CallbackResponseToJSONTyped(
  value?: CallbackResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    redirectUrl: value['redirectUrl'],
    sessionId: value['sessionId'],
    status: SessionStatusToJSON(value['status']),
    success: value['success'],
  }
}
