/* tslint:disable */
/* eslint-disable */
/**
 * OwlID Issuer Service
 * Identity verification and credential issuance
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js'
/**
 * Request to create a verification session
 * @export
 * @interface CreateSessionRequest
 */
export interface CreateSessionRequest {
  /**
   *
   * @type {string}
   * @memberof CreateSessionRequest
   */
  providerId: string
}

/**
 * Check if a given object implements the CreateSessionRequest interface.
 */
export function instanceOfCreateSessionRequest(value: object): value is CreateSessionRequest {
  if (!('providerId' in value) || value['providerId'] === undefined) return false
  return true
}

export function CreateSessionRequestFromJSON(json: any): CreateSessionRequest {
  return CreateSessionRequestFromJSONTyped(json, false)
}

export function CreateSessionRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreateSessionRequest {
  if (json == null) {
    return json
  }
  return {
    providerId: json['providerId'],
  }
}

export function CreateSessionRequestToJSON(json: any): CreateSessionRequest {
  return CreateSessionRequestToJSONTyped(json, false)
}

export function CreateSessionRequestToJSONTyped(
  value?: CreateSessionRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    providerId: value['providerId'],
  }
}
