/* tslint:disable */
/* eslint-disable */
/**
 * OwlID Issuer Service
 * Identity verification and credential issuance
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js'
/**
 * SAML redirect: received callback, processing
 * @export
 * @interface FlowStateOneOf1
 */
export interface FlowStateOneOf1 {
  /**
   *
   * @type {string}
   * @memberof FlowStateOneOf1
   */
  relayState: string
  /**
   *
   * @type {string}
   * @memberof FlowStateOneOf1
   */
  type: FlowStateOneOf1TypeEnum
}

/**
 * @export
 * @enum {string}
 */
export enum FlowStateOneOf1TypeEnum {
  saml_processing = 'saml_processing',
}

/**
 * Check if a given object implements the FlowStateOneOf1 interface.
 */
export function instanceOfFlowStateOneOf1(value: object): value is FlowStateOneOf1 {
  if (!('relayState' in value) || value['relayState'] === undefined) return false
  if (!('type' in value) || value['type'] === undefined) return false
  return true
}

export function FlowStateOneOf1FromJSON(json: any): FlowStateOneOf1 {
  return FlowStateOneOf1FromJSONTyped(json, false)
}

export function FlowStateOneOf1FromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): FlowStateOneOf1 {
  if (json == null) {
    return json
  }
  return {
    relayState: json['relayState'],
    type: json['type'],
  }
}

export function FlowStateOneOf1ToJSON(json: any): FlowStateOneOf1 {
  return FlowStateOneOf1ToJSONTyped(json, false)
}

export function FlowStateOneOf1ToJSONTyped(
  value?: FlowStateOneOf1 | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    relayState: value['relayState'],
    type: value['type'],
  }
}
