/* tslint:disable */
/* eslint-disable */
/**
 * OwlID Issuer Service
 * Identity verification and credential issuance
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js'
/**
 * Verification completed successfully
 * @export
 * @interface FlowStateOneOf10
 */
export interface FlowStateOneOf10 {
  /**
   *
   * @type {string}
   * @memberof FlowStateOneOf10
   */
  type: FlowStateOneOf10TypeEnum
}

/**
 * @export
 * @enum {string}
 */
export enum FlowStateOneOf10TypeEnum {
  completed = 'completed',
}

/**
 * Check if a given object implements the FlowStateOneOf10 interface.
 */
export function instanceOfFlowStateOneOf10(value: object): value is FlowStateOneOf10 {
  if (!('type' in value) || value['type'] === undefined) return false
  return true
}

export function FlowStateOneOf10FromJSON(json: any): FlowStateOneOf10 {
  return FlowStateOneOf10FromJSONTyped(json, false)
}

export function FlowStateOneOf10FromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): FlowStateOneOf10 {
  if (json == null) {
    return json
  }
  return {
    type: json['type'],
  }
}

export function FlowStateOneOf10ToJSON(json: any): FlowStateOneOf10 {
  return FlowStateOneOf10ToJSONTyped(json, false)
}

export function FlowStateOneOf10ToJSONTyped(
  value?: FlowStateOneOf10 | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    type: value['type'],
  }
}
