/* tslint:disable */
/* eslint-disable */
/**
 * OwlID Issuer Service
 * Identity verification and credential issuance
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js'
/**
 * Form: processing submission
 * @export
 * @interface FlowStateOneOf9
 */
export interface FlowStateOneOf9 {
  /**
   *
   * @type {string}
   * @memberof FlowStateOneOf9
   */
  type: FlowStateOneOf9TypeEnum
}

/**
 * @export
 * @enum {string}
 */
export enum FlowStateOneOf9TypeEnum {
  form_processing = 'form_processing',
}

/**
 * Check if a given object implements the FlowStateOneOf9 interface.
 */
export function instanceOfFlowStateOneOf9(value: object): value is FlowStateOneOf9 {
  if (!('type' in value) || value['type'] === undefined) return false
  return true
}

export function FlowStateOneOf9FromJSON(json: any): FlowStateOneOf9 {
  return FlowStateOneOf9FromJSONTyped(json, false)
}

export function FlowStateOneOf9FromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): FlowStateOneOf9 {
  if (json == null) {
    return json
  }
  return {
    type: json['type'],
  }
}

export function FlowStateOneOf9ToJSON(json: any): FlowStateOneOf9 {
  return FlowStateOneOf9ToJSONTyped(json, false)
}

export function FlowStateOneOf9ToJSONTyped(
  value?: FlowStateOneOf9 | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    type: value['type'],
  }
}
