/* tslint:disable */
/* eslint-disable */
/**
 * OwlID Issuer Service
 * Identity verification and credential issuance
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js'
/**
 * SAML redirect: waiting for assertion callback
 * @export
 * @interface FlowStateOneOf
 */
export interface FlowStateOneOf {
  /**
   * Relay state to include in SAML request
   * @type {string}
   * @memberof FlowStateOneOf
   */
  relayState: string
  /**
   *
   * @type {string}
   * @memberof FlowStateOneOf
   */
  type: FlowStateOneOfTypeEnum
}

/**
 * @export
 * @enum {string}
 */
export enum FlowStateOneOfTypeEnum {
  saml_pending = 'saml_pending',
}

/**
 * Check if a given object implements the FlowStateOneOf interface.
 */
export function instanceOfFlowStateOneOf(value: object): value is FlowStateOneOf {
  if (!('relayState' in value) || value['relayState'] === undefined) return false
  if (!('type' in value) || value['type'] === undefined) return false
  return true
}

export function FlowStateOneOfFromJSON(json: any): FlowStateOneOf {
  return FlowStateOneOfFromJSONTyped(json, false)
}

export function FlowStateOneOfFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): FlowStateOneOf {
  if (json == null) {
    return json
  }
  return {
    relayState: json['relayState'],
    type: json['type'],
  }
}

export function FlowStateOneOfToJSON(json: any): FlowStateOneOf {
  return FlowStateOneOfToJSONTyped(json, false)
}

export function FlowStateOneOfToJSONTyped(
  value?: FlowStateOneOf | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    relayState: value['relayState'],
    type: value['type'],
  }
}
