/* tslint:disable */
/* eslint-disable */
/**
 * OwlID Issuer Service
 * Identity verification and credential issuance
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js'
/**
 * OIDC redirect: callback received, exchanging code + verifying
 * the ID token against the provider JWKS.
 * @export
 * @interface FlowStateOneOf7
 */
export interface FlowStateOneOf7 {
  /**
   *
   * @type {string}
   * @memberof FlowStateOneOf7
   */
  state: string
  /**
   *
   * @type {string}
   * @memberof FlowStateOneOf7
   */
  type: FlowStateOneOf7TypeEnum
}

/**
 * @export
 * @enum {string}
 */
export enum FlowStateOneOf7TypeEnum {
  oidc_processing = 'oidc_processing',
}

/**
 * Check if a given object implements the FlowStateOneOf7 interface.
 */
export function instanceOfFlowStateOneOf7(value: object): value is FlowStateOneOf7 {
  if (!('state' in value) || value['state'] === undefined) return false
  if (!('type' in value) || value['type'] === undefined) return false
  return true
}

export function FlowStateOneOf7FromJSON(json: any): FlowStateOneOf7 {
  return FlowStateOneOf7FromJSONTyped(json, false)
}

export function FlowStateOneOf7FromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): FlowStateOneOf7 {
  if (json == null) {
    return json
  }
  return {
    state: json['state'],
    type: json['type'],
  }
}

export function FlowStateOneOf7ToJSON(json: any): FlowStateOneOf7 {
  return FlowStateOneOf7ToJSONTyped(json, false)
}

export function FlowStateOneOf7ToJSONTyped(
  value?: FlowStateOneOf7 | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    state: value['state'],
    type: value['type'],
  }
}
