/* tslint:disable */
/* eslint-disable */
/**
 * OwlID Issuer Service
 * Identity verification and credential issuance
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js'
/**
 * Request to issue a credential
 * @export
 * @interface IssueCredentialRequest
 */
export interface IssueCredentialRequest {
  /**
   * OpenID4VCI batch issuance for unlinkability: mint this many
   * one-time-use SD-JWT VCs (same holder `cnf`, distinct issuer JWT ⇒
   * distinct `credential_id`, each independently revocable). The
   * holder presents each to at most one verifier so presentations
   * cannot be correlated. Default 1; clamped to 1..=64.
   * @type {number}
   * @memberof IssueCredentialRequest
   */
  batchSize?: number | null
  /**
   * Key algorithm: "p256" (WebAuthn default) or "ed25519"
   * @type {string}
   * @memberof IssueCredentialRequest
   */
  keyAlgorithm?: string
  /**
   * Owner's public key (hex)
   * @type {string}
   * @memberof IssueCredentialRequest
   */
  ownerPublicKey: string
}

/**
 * Check if a given object implements the IssueCredentialRequest interface.
 */
export function instanceOfIssueCredentialRequest(value: object): value is IssueCredentialRequest {
  if (!('ownerPublicKey' in value) || value['ownerPublicKey'] === undefined) return false
  return true
}

export function IssueCredentialRequestFromJSON(json: any): IssueCredentialRequest {
  return IssueCredentialRequestFromJSONTyped(json, false)
}

export function IssueCredentialRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): IssueCredentialRequest {
  if (json == null) {
    return json
  }
  return {
    batchSize: json['batchSize'] == null ? undefined : json['batchSize'],
    keyAlgorithm: json['keyAlgorithm'] == null ? undefined : json['keyAlgorithm'],
    ownerPublicKey: json['ownerPublicKey'],
  }
}

export function IssueCredentialRequestToJSON(json: any): IssueCredentialRequest {
  return IssueCredentialRequestToJSONTyped(json, false)
}

export function IssueCredentialRequestToJSONTyped(
  value?: IssueCredentialRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    batchSize: value['batchSize'],
    keyAlgorithm: value['keyAlgorithm'],
    ownerPublicKey: value['ownerPublicKey'],
  }
}
