/* tslint:disable */
/* eslint-disable */
/**
 * OwlID Issuer Service
 * Identity verification and credential issuance
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js'
import type { ProviderFlowType } from './ProviderFlowType.js'
import {
  ProviderFlowTypeFromJSON,
  ProviderFlowTypeFromJSONTyped,
  ProviderFlowTypeToJSON,
  ProviderFlowTypeToJSONTyped,
} from './ProviderFlowType.js'
import type { VerificationLevel } from './VerificationLevel.js'
import {
  VerificationLevelFromJSON,
  VerificationLevelFromJSONTyped,
  VerificationLevelToJSON,
  VerificationLevelToJSONTyped,
} from './VerificationLevel.js'

/**
 * Public provider record exposed over OpenAPI (`GET /providers`).
 *
 * Combines the static `ProviderDescriptor` from the trait with runtime
 * state — flow type, verification level, and the operator-controlled
 * `enabled` flag (toggled via `POST /admin/providers/{id}/{enable,disable}`
 * and persisted in the `provider_settings` table).
 * @export
 * @interface ProviderInfo
 */
export interface ProviderInfo {
  /**
   *
   * @type {string}
   * @memberof ProviderInfo
   */
  country: string
  /**
   *
   * @type {string}
   * @memberof ProviderInfo
   */
  description: string
  /**
   *
   * @type {string}
   * @memberof ProviderInfo
   */
  id: string
  /**
   *
   * @type {string}
   * @memberof ProviderInfo
   */
  name: string
  /**
   *
   * @type {Array<VerificationLevel>}
   * @memberof ProviderInfo
   */
  verificationLevels: Array<VerificationLevel>
  /**
   * `false` if the operator has disabled this provider; consumers must
   * not start a new verification session against it.
   * @type {boolean}
   * @memberof ProviderInfo
   */
  enabled: boolean
  /**
   *
   * @type {ProviderFlowType}
   * @memberof ProviderInfo
   */
  flowType: ProviderFlowType
  /**
   *
   * @type {VerificationLevel}
   * @memberof ProviderInfo
   */
  verificationLevel: VerificationLevel
}

/**
 * Check if a given object implements the ProviderInfo interface.
 */
export function instanceOfProviderInfo(value: object): value is ProviderInfo {
  if (!('country' in value) || value['country'] === undefined) return false
  if (!('description' in value) || value['description'] === undefined) return false
  if (!('id' in value) || value['id'] === undefined) return false
  if (!('name' in value) || value['name'] === undefined) return false
  if (!('verificationLevels' in value) || value['verificationLevels'] === undefined) return false
  if (!('enabled' in value) || value['enabled'] === undefined) return false
  if (!('flowType' in value) || value['flowType'] === undefined) return false
  if (!('verificationLevel' in value) || value['verificationLevel'] === undefined) return false
  return true
}

export function ProviderInfoFromJSON(json: any): ProviderInfo {
  return ProviderInfoFromJSONTyped(json, false)
}

export function ProviderInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProviderInfo {
  if (json == null) {
    return json
  }
  return {
    country: json['country'],
    description: json['description'],
    id: json['id'],
    name: json['name'],
    verificationLevels: (json['verificationLevels'] as Array<any>).map(VerificationLevelFromJSON),
    enabled: json['enabled'],
    flowType: ProviderFlowTypeFromJSON(json['flowType']),
    verificationLevel: VerificationLevelFromJSON(json['verificationLevel']),
  }
}

export function ProviderInfoToJSON(json: any): ProviderInfo {
  return ProviderInfoToJSONTyped(json, false)
}

export function ProviderInfoToJSONTyped(
  value?: ProviderInfo | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    country: value['country'],
    description: value['description'],
    id: value['id'],
    name: value['name'],
    verificationLevels: (value['verificationLevels'] as Array<any>).map(VerificationLevelToJSON),
    enabled: value['enabled'],
    flowType: ProviderFlowTypeToJSON(value['flowType']),
    verificationLevel: VerificationLevelToJSON(value['verificationLevel']),
  }
}
