/* tslint:disable */
/* eslint-disable */
/**
 * OwlID Issuer Service
 * Identity verification and credential issuance
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js'
import type { RecoveryBackupResponse } from './RecoveryBackupResponse.js'
import {
  RecoveryBackupResponseFromJSON,
  RecoveryBackupResponseFromJSONTyped,
  RecoveryBackupResponseToJSON,
  RecoveryBackupResponseToJSONTyped,
} from './RecoveryBackupResponse.js'

/**
 *
 * @export
 * @interface RecoveryBackupsResponse
 */
export interface RecoveryBackupsResponse {
  /**
   *
   * @type {Array<RecoveryBackupResponse>}
   * @memberof RecoveryBackupsResponse
   */
  backups: Array<RecoveryBackupResponse>
}

/**
 * Check if a given object implements the RecoveryBackupsResponse interface.
 */
export function instanceOfRecoveryBackupsResponse(value: object): value is RecoveryBackupsResponse {
  if (!('backups' in value) || value['backups'] === undefined) return false
  return true
}

export function RecoveryBackupsResponseFromJSON(json: any): RecoveryBackupsResponse {
  return RecoveryBackupsResponseFromJSONTyped(json, false)
}

export function RecoveryBackupsResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): RecoveryBackupsResponse {
  if (json == null) {
    return json
  }
  return {
    backups: (json['backups'] as Array<any>).map(RecoveryBackupResponseFromJSON),
  }
}

export function RecoveryBackupsResponseToJSON(json: any): RecoveryBackupsResponse {
  return RecoveryBackupsResponseToJSONTyped(json, false)
}

export function RecoveryBackupsResponseToJSONTyped(
  value?: RecoveryBackupsResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    backups: (value['backups'] as Array<any>).map(RecoveryBackupResponseToJSON),
  }
}
