/* tslint:disable */
/* eslint-disable */
/**
 * OwlID Issuer Service
 * Identity verification and credential issuance
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js'
/**
 *
 * @export
 * @interface RecoveryBackupRequest
 */
export interface RecoveryBackupRequest {
  /**
   *
   * @type {string}
   * @memberof RecoveryBackupRequest
   */
  ciphertext: string
  /**
   *
   * @type {string}
   * @memberof RecoveryBackupRequest
   */
  credentialId: string
  /**
   *
   * @type {string}
   * @memberof RecoveryBackupRequest
   */
  encryptionVersion: string
  /**
   *
   * @type {string}
   * @memberof RecoveryBackupRequest
   */
  keyLabel: string
  /**
   *
   * @type {any}
   * @memberof RecoveryBackupRequest
   */
  metadata?: any | null
}

/**
 * Check if a given object implements the RecoveryBackupRequest interface.
 */
export function instanceOfRecoveryBackupRequest(value: object): value is RecoveryBackupRequest {
  if (!('ciphertext' in value) || value['ciphertext'] === undefined) return false
  if (!('credentialId' in value) || value['credentialId'] === undefined) return false
  if (!('encryptionVersion' in value) || value['encryptionVersion'] === undefined) return false
  if (!('keyLabel' in value) || value['keyLabel'] === undefined) return false
  return true
}

export function RecoveryBackupRequestFromJSON(json: any): RecoveryBackupRequest {
  return RecoveryBackupRequestFromJSONTyped(json, false)
}

export function RecoveryBackupRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): RecoveryBackupRequest {
  if (json == null) {
    return json
  }
  return {
    ciphertext: json['ciphertext'],
    credentialId: json['credentialId'],
    encryptionVersion: json['encryptionVersion'],
    keyLabel: json['keyLabel'],
    metadata: json['metadata'] == null ? undefined : json['metadata'],
  }
}

export function RecoveryBackupRequestToJSON(json: any): RecoveryBackupRequest {
  return RecoveryBackupRequestToJSONTyped(json, false)
}

export function RecoveryBackupRequestToJSONTyped(
  value?: RecoveryBackupRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    ciphertext: value['ciphertext'],
    credentialId: value['credentialId'],
    encryptionVersion: value['encryptionVersion'],
    keyLabel: value['keyLabel'],
    metadata: value['metadata'],
  }
}
