/* tslint:disable */
/* eslint-disable */
/**
 * OwlID Issuer Service
 * Identity verification and credential issuance
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js'
/**
 *
 * @export
 * @interface RecoveryBackupResponse
 */
export interface RecoveryBackupResponse {
  /**
   *
   * @type {string}
   * @memberof RecoveryBackupResponse
   */
  ciphertext: string
  /**
   *
   * @type {string}
   * @memberof RecoveryBackupResponse
   */
  credentialId: string
  /**
   *
   * @type {string}
   * @memberof RecoveryBackupResponse
   */
  encryptionVersion: string
  /**
   *
   * @type {string}
   * @memberof RecoveryBackupResponse
   */
  id: string
  /**
   *
   * @type {string}
   * @memberof RecoveryBackupResponse
   */
  keyLabel: string
  /**
   *
   * @type {string}
   * @memberof RecoveryBackupResponse
   */
  updatedAt: string
}

/**
 * Check if a given object implements the RecoveryBackupResponse interface.
 */
export function instanceOfRecoveryBackupResponse(value: object): value is RecoveryBackupResponse {
  if (!('ciphertext' in value) || value['ciphertext'] === undefined) return false
  if (!('credentialId' in value) || value['credentialId'] === undefined) return false
  if (!('encryptionVersion' in value) || value['encryptionVersion'] === undefined) return false
  if (!('id' in value) || value['id'] === undefined) return false
  if (!('keyLabel' in value) || value['keyLabel'] === undefined) return false
  if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false
  return true
}

export function RecoveryBackupResponseFromJSON(json: any): RecoveryBackupResponse {
  return RecoveryBackupResponseFromJSONTyped(json, false)
}

export function RecoveryBackupResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): RecoveryBackupResponse {
  if (json == null) {
    return json
  }
  return {
    ciphertext: json['ciphertext'],
    credentialId: json['credentialId'],
    encryptionVersion: json['encryptionVersion'],
    id: json['id'],
    keyLabel: json['keyLabel'],
    updatedAt: json['updatedAt'],
  }
}

export function RecoveryBackupResponseToJSON(json: any): RecoveryBackupResponse {
  return RecoveryBackupResponseToJSONTyped(json, false)
}

export function RecoveryBackupResponseToJSONTyped(
  value?: RecoveryBackupResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    ciphertext: value['ciphertext'],
    credentialId: value['credentialId'],
    encryptionVersion: value['encryptionVersion'],
    id: value['id'],
    keyLabel: value['keyLabel'],
    updatedAt: value['updatedAt'],
  }
}
