/* tslint:disable */
/* eslint-disable */
/**
 * OwlID Issuer Service
 * Identity verification and credential issuance
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Verification assurance levels per eIDAS regulation
 * @export
 * @enum {string}
 */
export enum VerificationLevel {
  low = 'low',
  substantial = 'substantial',
  high = 'high',
}

export function instanceOfVerificationLevel(value: any): boolean {
  for (const key in VerificationLevel) {
    if (Object.prototype.hasOwnProperty.call(VerificationLevel, key)) {
      if (VerificationLevel[key as keyof typeof VerificationLevel] === value) {
        return true
      }
    }
  }
  return false
}

export function VerificationLevelFromJSON(json: any): VerificationLevel {
  return VerificationLevelFromJSONTyped(json, false)
}

export function VerificationLevelFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): VerificationLevel {
  return json as VerificationLevel
}

export function VerificationLevelToJSON(value?: VerificationLevel | null): any {
  return value as any
}

export function VerificationLevelToJSONTyped(
  value: any,
  ignoreDiscriminator: boolean,
): VerificationLevel {
  return value as VerificationLevel
}
